import type { Row } from "./schema";

/**
 * Non-engineering career paths: accounting and finance, marketing, HR, UX,
 * product management and business analysis. Professional-body rules, exam
 * structures and fees change, so answers send people to the body's own site
 * for those details and never quote them.
 */
export const businessRoleRows: Row[] = [
  [
    "accountant-roadmap",
    "How do I become an accountant?",
    ["Give me an accountant roadmap", "What should I learn to work in accounting?", "How do I start a career in accounting?", "Accountant career path for beginners", "How do I get an accounting job as a fresher?"],
    "accounting-finance",
    "roadmap",
    "Accounting is the discipline of recording, classifying, summarising and reporting financial activity so that people can make decisions and meet legal obligations. The path has three layers: fundamentals, tools and compliance, then qualifications.\n\nPhase 1: fundamentals. Learn the accounting equation, double-entry bookkeeping, debits and credits, the chart of accounts, journals and ledgers, the trial balance, and how the income statement, balance sheet and cash-flow statement connect. Work through a full month of transactions for an imaginary small business by hand and then in a spreadsheet, closing the books and producing all three statements. Khan Academy's finance section and a full financial accounting course cover this free.\n\nPhase 2: tools and compliance. Spreadsheet skills are non-negotiable: lookups, pivot tables, reconciliation layouts and error checking. Learn one accounting package used locally (in India that is commonly Tally; elsewhere QuickBooks, Xero or SAP modules). Understand the basics of indirect tax filing (GST in India), payroll, TDS and bank reconciliation, using the official government portals as your reference rather than summaries.\n\nPhase 3: qualifications. A commerce degree is the usual base. Professional routes include Chartered Accountancy through ICAI, cost accountancy through ICMAI, ACCA, or CPA depending on the country you want to work in. Each body publishes its own current structure, registration rules and fees; read those pages directly and do not rely on second-hand summaries, including this one.\n\nPortfolio and experience: an articleship or an internship at a firm, bookkeeping for a small business or a family enterprise, and a documented month-end close you performed. Keep a reconciliation you completed and be ready to walk through it.\n\nYou are ready for entry-level accounting work when you can close a month without guidance, explain every line of a balance sheet to a non-accountant, spot an unbalanced entry quickly, and describe how a tax filing you prepared was checked.",
    ["khanFinance", "icai", "icmai", "acca", "gst", "incomeTax", "excelSupport", "tally", "blsOoh"],
    ["accountant", "accounting", "bookkeeping", "financial statements", "tally", "gst", "roadmap"],
    ["yYX4bvQSqbo", "v-djL7SPw4c"],
  ],
  [
    "chartered-accountant-path",
    "How do I become a chartered accountant in India?",
    ["What is the route to becoming a CA?", "How does the CA course work?", "Roadmap for chartered accountancy"],
    "accounting-finance",
    "roadmap",
    "Chartered Accountancy in India is administered by the Institute of Chartered Accountants of India (ICAI). The route is a sequence of examination levels combined with a period of practical training (articleship) under a practising chartered accountant, plus required training modules. The exact levels, entry routes after school or graduation, exemptions, registration windows, attempt rules and fees are set by ICAI and revised periodically, so read the current scheme on icai.org before planning; treat any other summary, including videos, as an overview only.\n\nHow to prepare well regardless of scheme details: build genuine strength in accounting fundamentals, law, taxation and costing rather than memorising past papers; practise full-length answers under time; and treat articleship as real professional training, choosing a firm where you will see audits, tax work and client interaction rather than only data entry.\n\nAlternatives worth comparing honestly: cost and management accountancy through ICMAI, company secretaryship through ICSI, ACCA for international mobility, and a commerce degree plus industry accounting roles. Each has a different time commitment and different employer recognition.\n\nUse your preparation years to build spreadsheet, accounting-software and tax-portal skills; many CA students reach qualification with strong theory and weak tools.\n\nI will not state pass rates, durations or fees; check ICAI directly and confirm your own eligibility with them.",
    ["icai", "icmai", "icsi", "acca", "khanFinance"],
    ["chartered accountant", "ca", "icai", "articleship", "accounting", "india"],
    ["CqZSxeo9gUQ"],
  ],
  [
    "financial-analyst-roadmap",
    "How do I become a financial analyst?",
    ["Financial analyst roadmap", "What should I learn for financial analyst jobs?", "How do I start a career in finance as an analyst?"],
    "accounting-finance",
    "roadmap",
    "Financial analysts turn accounting data and business assumptions into decisions: budgets, forecasts, valuations and performance reviews. The role rewards numeracy, spreadsheet craft and clear communication.\n\nPhase 1: accounting literacy. You must read the three financial statements fluently and understand how a change in one flows into the others. If you do not have a commerce background, start with a full accounting fundamentals course.\n\nPhase 2: analysis skills. Ratio analysis, working-capital analysis, variance analysis against budget, time value of money, discounted cash flow and basic valuation. Learn to build a linked three-statement model in a spreadsheet from scratch; the free Wall Street Prep and similar crash courses walk through it.\n\nPhase 3: tools. Advanced spreadsheet functions and modelling conventions, then SQL and a BI tool for pulling and presenting data, and increasingly Python for automation. Presentation matters: learn to make a one-page summary a manager can act on.\n\nPhase 4: domain and credentials. Corporate finance (FP&A) and investment roles differ; read job descriptions for both. Credentials such as the CFA programme or an MBA are common in investment-side roles; check the CFA Institute site for the current programme structure and costs and decide based on the roles you want.\n\nPortfolio: a full model for a listed company from its public filings with a written thesis, a budget-versus-actual dashboard, and a short valuation memo. Ready when you can explain where every number in your model comes from and what assumption it is most sensitive to.",
    ["khanFinance", "cfa", "excelSupport", "sqlbolt", "powerbi", "sebi"],
    ["financial analyst", "finance", "financial modelling", "fp&a", "valuation", "roadmap"],
    ["Rmi9fwkJjHw", "64A6HJDEbKA"],
  ],
  [
    "accounting-interview-prep",
    "How do I prepare for an accounting job interview?",
    ["What is asked in accountant interviews?", "Accounting interview questions for freshers", "How do I prepare for an accounts executive interview?"],
    "accounting-finance",
    "interview",
    "Accounting interviews test fundamentals, tool fluency and attention to detail. Expect three kinds of questions.\n\nConcepts: golden rules of accounting and the accounting equation, journal entries for common transactions (purchase on credit, depreciation, accrued expenses, prepaid items, bad debts), the difference between the three statements and how they link, accrual versus cash basis, and treatment of specific items such as provisions or fixed-asset disposal. Practise by writing the entry, not just naming the rule.\n\nPractical: bank reconciliation walkthroughs, spotting an error in a trial balance, spreadsheet tasks (lookups, pivot summaries, reconciliation layouts), and questions about the accounting software the employer uses. Be honest about which package you know and how quickly you learn tools.\n\nCompliance: basics of the taxes you would handle in that role (indirect tax filing cycles, TDS concepts, payroll deductions). Refer to official portals rather than memorised rates, because rates change and interviewers respect accuracy over confident guesses.\n\nBehavioural: an error you caught before it reached a client, how you handle month-end pressure, and how you keep records organised.\n\nBring a reconciliation or close you performed (with confidential details removed) and be ready to explain your checks step by step. Precision in your own examples matters more than breadth of theory.",
    ["khanFinance", "gst", "incomeTax", "excelSupport", "tally"],
    ["accounting", "interview", "journal entries", "reconciliation", "accounts executive"],
    ["hTU6HE64Wd0"],
  ],
  [
    "accounting-fresher-evidence",
    "How can an accounting fresher show practical skills without experience?",
    ["What can a commerce graduate show employers besides a degree?", "How do I build accounting experience on my own?"],
    "portfolio",
    "portfolio",
    "Accounting employers want proof you can do the work carefully, and you can produce that proof without a job.\n\nKeep books for a real small entity: a family business, a shop, a club, a freelancer. Record a full quarter, reconcile the bank, produce statements, and file or shadow the filing of any returns. Keep a sanitised copy as a work sample.\n\nBuild a complete practice set: invent a small company, post a month of varied transactions, run through adjustments (depreciation, accruals, prepayments, bad debts), close the period and produce the three statements with schedules. Do it once by hand and once in a spreadsheet with checks that flag imbalances.\n\nLearn one accounting package thoroughly and document what you can do in it: ledgers, vouchers, GST-ready invoicing, reports. Screenshots of a sample company in the software are acceptable evidence.\n\nDo an internship or articleship, even short, and write down exactly which tasks you performed.\n\nOn the résumé, describe these as work: 'Maintained books and monthly bank reconciliations for a retail shop; prepared quarterly GST working.' In interviews, walk through your reconciliation checks. This evidence separates you from graduates who only list subjects studied.",
    ["excelSupport", "tally", "gst", "khanFinance"],
    ["accounting", "fresher", "experience", "portfolio", "commerce graduate"],
    ["m_SH0TOLsIc"],
  ],
  [
    "seo-specialist-roadmap",
    "How do I become an SEO specialist?",
    ["SEO specialist roadmap", "What should I learn to work in search engine optimisation?", "How do I start an SEO career?"],
    "digital-marketing",
    "roadmap",
    "SEO is the practice of making web pages discoverable and useful for search, which today means content quality, technical health and authority signals, increasingly evaluated alongside AI-generated answers.\n\nPhase 1: how search works. Read Google's SEO Starter Guide and the Moz beginner guide end to end. Learn crawling, indexing, ranking signals as publicly documented, and what Google says about helpful content.\n\nPhase 2: the three pillars. Technical SEO (site structure, crawlability, page speed, structured data, sitemaps, canonicalisation); on-page and content (keyword research, search intent, content briefs, internal linking, titles and headings); and off-page (digital PR, earning links ethically). Learn to use Search Console and an analytics tool to measure results.\n\nPhase 3: practice on something real. Build or take over a small site (a niche blog, a local business you help, a nonprofit) and improve its search performance over three months, documenting hypotheses, changes and outcomes. Screenshots of Search Console trends you caused are your portfolio.\n\nPhase 4: adjacent skills. Basic HTML, spreadsheet analysis, writing, and an understanding of paid search so you can advise on the mix.\n\nCertifications from Google Skillshop, HubSpot Academy and Semrush Academy are free and useful for vocabulary; treat them as study aids, not proof of results.\n\nReady when you can audit a site and prioritise fixes by impact, write a content brief from keyword research, and explain a ranking change with data rather than guesses.",
    ["seo", "mozSeo", "semrushAcademy", "skillshop", "googleAnalyticsHelp", "ahrefsBlog", "backlinko"],
    ["seo", "search engine optimisation", "digital marketing", "content", "search console", "roadmap"],
    ["xsVTqzratPs"],
  ],
  [
    "digital-marketing-interview-prep",
    "How do I prepare for a digital marketing interview?",
    ["What is asked in digital marketing interviews?", "Digital marketing interview questions for freshers", "How do I prepare for a performance marketing role interview?"],
    "digital-marketing",
    "interview",
    "Marketing interviews test whether you can think in terms of audience, channel and measurement, and whether you can show results.\n\nExpect: definitions with reasoning (what is the difference between SEO and SEM, when would you use each; what is CTR, CPC, CPA, ROAS and which matters when); channel questions (how would you launch a campaign for X on a small budget; how do you decide between Meta and Google Ads); analytics (how do you know a campaign worked; what would you check if traffic rose but conversions fell); content (write a headline for this product; critique this landing page); and tools (which ad platforms, analytics and email tools you have actually used).\n\nPrepare a portfolio: campaigns you ran, even tiny ones for a friend's business or a personal project, with the objective, the audience, the creative, the budget scale, and the measured result. If you have never run a campaign, run one for a small budget before the interview and bring the numbers.\n\nPractical tasks are common: a short audit of the company's own channels. Do it before the interview: their site, their ads, their social presence, and three improvements you would make.\n\nFree certifications from Google Skillshop and HubSpot Academy help with vocabulary; results and analysis help with getting the job.",
    ["skillshop", "hubspotAcademy", "googleAnalyticsHelp", "seo", "semrushAcademy"],
    ["digital marketing", "interview", "performance marketing", "campaigns", "analytics"],
    ["h95cQkEWBx0"],
  ],
  [
    "marketing-portfolio",
    "How do I build a digital marketing portfolio with no clients?",
    ["What can I show employers for a marketing role?", "How do I get marketing experience without a job?"],
    "portfolio",
    "portfolio",
    "Marketing evidence is results plus reasoning, and you can generate both on your own.\n\nCreate a small property you control: a niche blog, a YouTube channel, a newsletter or a local community page. Set a measurable goal, run content and small paid experiments, and record what happened month by month. Even modest numbers with honest analysis beat claims without data.\n\nOffer a free or low-cost campaign to a local business, a nonprofit or a friend's venture, scoped tightly (one channel, one month, one goal), and document it as a case study: objective, audience, creative, budget scale, results, what you would change.\n\nProduce a written audit of a real brand's digital presence: SEO health, ad creative, social cadence, landing pages, email. Show prioritised recommendations with expected impact.\n\nCollect certificates from Google Skillshop and HubSpot Academy as evidence of tool familiarity, but lead with the case studies.\n\nPresent everything on a single page or a short slide deck: three case studies, each one screen, with screenshots of dashboards. Hiring managers read results first and tools last.",
    ["skillshop", "hubspotAcademy", "seo", "googleAnalyticsHelp"],
    ["marketing", "portfolio", "case study", "campaign", "experience"],
    ["kunkYTKFNtI"],
  ],
  [
    "technical-recruiter-roadmap",
    "How do I become a technical recruiter?",
    ["Recruiter roadmap for beginners", "What should I learn to work in talent acquisition?", "How do I start a career in recruitment?"],
    "human-resources",
    "roadmap",
    "Recruiting is sales, research and judgment applied to people. Technical recruiting adds enough domain knowledge to talk credibly with engineers and hiring managers.\n\nPhase 1: the hiring process. Learn how a role gets defined, how a job description is written, sourcing, screening, structured interviews, offer and onboarding. Read how large employers describe their own hiring (Google publishes its process) to see what structured interviewing looks like.\n\nPhase 2: sourcing and tools. Boolean search, LinkedIn Recruiter concepts, applicant tracking systems, and outreach writing that gets replies. Practise by building candidate lists for imaginary roles and writing outreach messages.\n\nPhase 3: technical literacy. You do not need to code, but you must understand what frontend, backend, data, DevOps and QA roles actually do, which skills cluster together, and what a realistic job description looks like. The developer roadmaps site is a fast way to learn the map.\n\nPhase 4: judgment and ethics. Structured screening questions, bias awareness, candidate experience, confidentiality, and closing offers honestly.\n\nEntry routes: recruitment agencies hire freshers and train them; HR internships; coordinator roles in in-house talent teams. Professional bodies such as SHRM and CIPD publish free material on hiring practice.\n\nReady when you can take a vague hiring request and turn it into a clear role, source ten relevant profiles in an hour, and explain to a candidate why a role fits without overselling.",
    ["googleHiring", "linkedinTalentBlog", "shrm", "cipd", "developerRoadmap"],
    ["recruiter", "talent acquisition", "hr", "recruitment", "sourcing", "roadmap"],
    ["RLVaBrFxhhA"],
  ],
  [
    "hr-interview-prep",
    "How do I prepare for an HR executive interview?",
    ["What is asked in HR job interviews?", "How do I prepare for a human resources role interview?", "HR generalist interview questions preparation"],
    "human-resources",
    "interview",
    "Interviews for HR roles test process knowledge, judgment in people situations and communication.\n\nProcess: recruitment lifecycle, onboarding, payroll and statutory compliance basics for your country, leave and attendance policies, performance management cycles, and exit processes. Know the vocabulary and the sequence.\n\nSituations: 'An employee complains about a manager', 'Two team members are in conflict', 'A high performer resigns'. Answer with a fair process: listen, document, check policy, involve the right people, follow up. Avoid taking sides in the answer.\n\nTools: HRIS systems, spreadsheets for headcount and attrition analysis, and job boards or applicant tracking systems you have used.\n\nKnowledge: basic employment law relevant to the role, kept accurate; say when you would consult a specialist rather than guessing.\n\nBehavioural: confidentiality, handling pressure from managers, and a time you improved a process.\n\nIf you are a fresher, bring evidence: an internship, a college placement cell role, or a documented project such as a mock onboarding plan. Read SHRM or CIPD factsheets for standard practice, and practise explaining a policy in plain language, which is much of the daily job.",
    ["shrm", "cipd", "hrci", "writing"],
    ["hr", "human resources", "interview", "hr executive", "generalist"],
    ["c1npicEPaHw", "zIm_k9j0C50"],
  ],
  [
    "ui-designer-roadmap",
    "How do I become a UI designer?",
    ["UI designer roadmap", "What should I learn for UI/UX designer jobs?", "How do I become a product designer?", "How do I get into UI design without a design degree?"],
    "ui-ux",
    "roadmap",
    "UI design is the craft of visual interfaces: layout, typography, colour, components and interaction states, informed by usability. Most job descriptions ask for UI and UX together, so learn both, with the emphasis that matches the roles you want.\n\nPhase 1: fundamentals. Visual hierarchy, spacing systems, typography, colour and contrast (including accessibility requirements), grids and responsive layout. Study existing products deliberately: recreate three screens you admire in Figma and write down why each decision works.\n\nPhase 2: tools and systems. Figma properly: components, variants, auto layout, prototyping. Learn what a design system is by reading Material Design and Apple's Human Interface Guidelines, then build a small system of your own.\n\nPhase 3: UX basics. User flows, wireframes, usability testing with five people, and writing a case study that explains the problem, the process and the outcome. Read Nielsen Norman Group articles regularly.\n\nPhase 4: collaboration. Learn enough HTML and CSS to know what is cheap or expensive to build, and how to hand off designs to developers with specifications.\n\nPortfolio: three case studies, each showing a problem, research or constraints, iterations, the final design and what you learned. A self-initiated redesign is fine if labelled honestly. Recruiters look at craft first and process second, so polish matters.\n\nReady when you can design a responsive screen from a brief in a day, defend each decision with a usability reason, and hand it off cleanly.",
    ["figmaHelp", "figmaLibrary", "material", "hig", "nngroup", "lawsOfUx", "a11y", "growGoogle"],
    ["ui design", "ux", "product design", "figma", "design system", "portfolio", "roadmap"],
    ["c9Wg6Cb_YlU", "QJBP2uy8LcU"],
  ],
  [
    "ux-interview-prep",
    "How do I prepare for a UX designer interview?",
    ["What happens in a UX design interview?", "How do I present my design portfolio in interviews?", "UX interview preparation plan"],
    "ui-ux",
    "interview",
    "UX interviews usually include a portfolio presentation, a design exercise (whiteboard or take-home), and conversations about process and collaboration.\n\nPortfolio presentation: pick two case studies and rehearse a ten-minute walk-through of each: the problem, constraints, research, options considered, the decision, the outcome and what you would change. Interviewers interrupt with 'why', so know the reasons behind every screen. Show iterations, not only the final polish.\n\nDesign exercise: 'Design a way for commuters to report delays.' Clarify the goal and users, sketch the flow before screens, think aloud about trade-offs, and say what you would test. Time management and reasoning matter more than pixel quality.\n\nCritique: you may be asked to critique an existing product. Structure it: goal, user, what works, what fails, prioritised fixes.\n\nProcess questions: how you work with product managers and engineers, how you handle disagreement, how you decide when research is enough, and how you measure success after launch.\n\nAccessibility and design systems questions are common; have an example of each from your own work.\n\nPractise with a peer acting as a sceptical engineer. The Nielsen Norman Group articles on usability heuristics give you a shared vocabulary for critique.",
    ["nngroup", "lawsOfUx", "figmaLibrary", "a11y"],
    ["ux", "interview", "portfolio presentation", "design exercise", "critique"],
    ["R7urbI0iqb0"],
  ],
  [
    "ai-product-manager-roadmap",
    "How do I become an AI product manager?",
    ["What should a product manager learn about AI?", "AI product management roadmap", "How do I move into product management for AI products?"],
    "product-management",
    "roadmap",
    "AI product management is ordinary product management plus enough understanding of models to make good decisions about what to build, how to evaluate it and where it will fail.\n\nStart with product fundamentals if you lack them: discovery, defining problems and success metrics, prioritisation, writing clear specifications, working with engineering and design, and shipping iteratively. Marty Cagan's SVPG articles and the Atlassian product guides are free grounding.\n\nAdd AI literacy: what language models and classifiers can and cannot do, how retrieval and fine-tuning differ, what evaluation looks like, why outputs are probabilistic, and how cost and latency shape features. Build one small AI feature yourself with a model API so the constraints are real to you.\n\nLearn AI-specific product skills: writing evaluation criteria, designing for uncertainty in the interface (confidence, citations, easy correction), handling safety and privacy requirements, and deciding when a deterministic feature is better than an AI one.\n\nPortfolio: a written product spec for an AI feature including success metrics, an evaluation plan and a risk section, plus a small prototype. If you are already a PM, propose an AI improvement at work and run a measured pilot.\n\nReady when you can explain to an executive why an AI feature's quality cannot be promised as a percentage without an evaluation set, and to an engineer what 'good enough' means for the user.",
    ["svpg", "product", "productplan", "genaiBeginners", "claudeDocs", "dlaiShortCourses"],
    ["ai product manager", "product management", "llm", "evaluation", "roadmap"],
    ["KjYCEiBTHFo"],
  ],
  [
    "product-manager-interview-prep",
    "How do I prepare for a product manager interview?",
    ["What is asked in PM interviews?", "How do I answer product sense questions?", "Product management interview preparation plan"],
    "product-management",
    "interview",
    "Product manager interviews typically cover product sense, execution and analytics, technical understanding, and behavioural stories.\n\nProduct sense: 'Improve a product you use daily' or 'Design a product for X'. Structure: clarify the goal, identify user segments and pick one, list their problems, prioritise, propose solutions, define success metrics, name risks. Practise aloud with a timer until the structure is automatic.\n\nExecution and analytics: 'A metric dropped 20% overnight; what do you do?' Answer by checking data integrity first, segmenting by platform, region, cohort and release, forming hypotheses and describing how you would confirm each. Know your funnel metrics and how to define a north-star metric.\n\nTechnical: explain how a feature you shipped works under the hood, discuss trade-offs with engineers, and show you can read a basic architecture diagram. Deep coding is rarely required.\n\nBehavioural: stories about influencing without authority, cutting scope, handling a failed launch, and disagreeing with leadership. Use concrete outcomes.\n\nPrepare a one-page summary of two products you shipped or built, with the decisions you owned. If you have not shipped anything, build and launch something small and treat it with the same rigour; it becomes your material.\n\nSVPG and ProductPlan's learning centre cover the frameworks; practice partners cover the delivery.",
    ["svpg", "productplan", "product", "scrumGuide"],
    ["product manager", "interview", "product sense", "metrics", "execution"],
    ["5nAeyqNuZYU"],
  ],
  [
    "business-analyst-interview-prep",
    "How do I prepare for a business analyst interview?",
    ["What is asked in BA interviews?", "Business analyst interview questions preparation", "How do I prepare for a business analysis role interview?"],
    "business-analysis",
    "interview",
    "Business analyst interviews test whether you can turn an unclear request into clear requirements and communicate with both business and technical people.\n\nCore topics: requirements elicitation techniques (interviews, workshops, observation, document analysis), writing user stories with acceptance criteria, use cases, process mapping (as-is and to-be), gap analysis, prioritisation methods, and how you handle changing requirements. Know the difference between functional and non-functional requirements with examples.\n\nTools: process diagrams (BPMN basics), wireframing tools, backlog tools such as Jira, and SQL for checking data, which is increasingly expected.\n\nScenario questions: 'A stakeholder wants a feature that conflicts with another team's needs' or 'The requirements keep changing'. Answer with a process: understand the underlying need, quantify impact, facilitate a decision with the right people, document it.\n\nCase exercise: you may be given a short business problem to analyse live. Ask clarifying questions, structure the problem, identify stakeholders and data needed, and propose next steps.\n\nAgile knowledge: the Scrum Guide is short and worth reading before the interview.\n\nBring a sample artefact you produced: a requirements document, a process map or a set of user stories from a project, internship or a self-initiated analysis of a real process. The IIBA's BABOK guide provides the standard vocabulary if you want to align your answers with it.",
    ["iiba", "scrumGuide", "sqlbolt", "writing", "productplan"],
    ["business analyst", "interview", "requirements", "user stories", "process mapping"],
    ["UBVzucVpG7k"],
  ],
  [
    "developer-to-product-manager",
    "How can a software developer move into product management?",
    ["I am an engineer; how do I become a product manager?", "What should a developer learn to switch to product management?"],
    "career-switching",
    "roadmap",
    "Developers bring technical credibility and an understanding of feasibility, which product teams value. The gap is customer discovery, prioritisation across the business, and communication with non-technical stakeholders.\n\nLearn the discipline: product discovery, problem framing, writing specifications that describe outcomes rather than solutions, success metrics, and roadmapping under uncertainty. SVPG's articles and the Atlassian product management guide cover the mental models.\n\nPractise inside your current role: volunteer to write the problem statement for the next feature, sit in on customer calls, run a small usability test, propose a metric for a feature and report on it after launch. Ask your product manager to let you own a small slice end to end. These are the experiences a hiring manager wants to hear about.\n\nBuild communication habits: present to non-engineers, write clear one-page documents, and learn to say no with reasons.\n\nInternal moves are the most common route because your judgment is already trusted. Externally, associate PM roles and technical PM roles (platforms, developer tools, AI infrastructure) suit developers best.\n\nReady when you can describe a user problem without proposing the solution, prioritise ten requests with a defensible method, and explain why you shipped less than the team could build.",
    ["svpg", "product", "productplan", "scrumGuide", "writing"],
    ["developer", "product manager", "career switch", "product management"],
    ["5nAeyqNuZYU"],
  ],
  [
    "marketing-to-product-management",
    "How do I move from marketing into product management?",
    ["Can a marketer become a product manager?", "What should a marketing professional learn to switch to product?"],
    "career-switching",
    "roadmap",
    "Marketers already understand customers, positioning and metrics; the transition is towards owning what gets built and working closely with engineering.\n\nBuild the missing skills: writing specifications with acceptance criteria, prioritisation frameworks, basic technical literacy (how web and mobile apps are built, what an API is, why some changes are expensive), analytics beyond campaign metrics (funnels, retention, experiment design), and agile delivery practices such as Scrum.\n\nUse your position: product marketing is the natural bridge. Get involved in launch planning, customer research synthesis and feature prioritisation discussions. Volunteer to write the customer problem statement for a feature and to define its success metric.\n\nBuild evidence: a written product spec for an improvement to a product you know, a small prototype or no-code build, and a case study of a launch where you influenced scope.\n\nTarget roles where your background is an advantage: growth product management, consumer products, and companies where marketing and product already collaborate.\n\nReady when you can explain a trade-off between two features in terms of user value and engineering cost, and describe how you would validate an idea before building it.",
    ["svpg", "product", "productplan", "scrumGuide"],
    ["marketing", "product management", "career switch", "product marketing"],
  ],
  [
    "ux-vs-product-management",
    "Should I choose UX design or product management?",
    ["UX designer vs product manager: which career fits me?", "What is the difference between a UX designer and a product manager?"],
    "career-guidance",
    "comparison",
    "Both roles care about users and outcomes, but they own different decisions. A UX designer owns how the experience works and looks: research synthesis, flows, interfaces, usability. A product manager owns what gets built and why: problem selection, priorities, success metrics, trade-offs across business, engineering and design.\n\nChoose UX design if you enjoy making things tangible, iterating on interfaces, observing users, and you want a craft you can point to. Choose product management if you enjoy deciding between competing needs, working with numbers and strategy, and persuading people without authority, and you are comfortable owning outcomes you do not directly produce.\n\nDaily reality differs: designers spend more time in tools and with users; PMs spend more time in documents, meetings and data. Entry routes differ too: design portfolios open UX doors; product roles more often come from adjacent experience (engineering, marketing, analytics, design) or associate programmes.\n\nTest it: design one feature end to end (UX) and write the spec, metrics and prioritisation for it (PM). Notice which part you did not want to stop doing.",
    ["nngroup", "svpg", "product", "figmaLibrary"],
    ["ux", "product management", "comparison", "career choice", "design"],
    ["c9Wg6Cb_YlU", "5nAeyqNuZYU"],
  ],
  [
    "business-analyst-vs-product-manager",
    "What is the difference between a business analyst and a product manager?",
    ["Business analyst or product manager: which should I aim for?", "BA vs PM career comparison"],
    "career-guidance",
    "comparison",
    "A business analyst clarifies and documents what a business needs and how a solution should behave: requirements, processes, acceptance criteria, stakeholder alignment. A product manager decides what should be built and in what order, owns the product's success metrics, and is accountable for outcomes.\n\nOverlap is large in smaller companies; in larger ones the roles sit side by side, with the BA often deeper in detail and the PM broader in strategy.\n\nChoose business analysis if you like precision, process, and being the person who removes ambiguity; it also suits people entering from operations, finance or consulting. Choose product management if you want ownership of direction and are comfortable with judgment calls and accountability.\n\nMovement between them is common: BA to PM is a frequent progression once you have shown judgment about priorities, and PMs often benefit from BA-style rigour.\n\nPractical test: for a feature you know, write the requirements document (BA work) and then write the one-page 'why this, why now, how we will know it worked' memo (PM work). The one that felt like your natural voice is your answer.",
    ["iiba", "svpg", "productplan", "scrumGuide"],
    ["business analyst", "product manager", "comparison", "requirements", "career choice"],
    ["UBVzucVpG7k", "5nAeyqNuZYU"],
  ],
  [
    "accounting-vs-finance-career",
    "Should I build a career in accounting or in finance?",
    ["Accounting vs finance: which career should I choose?", "What is the difference between accounting and finance jobs?"],
    "accounting-finance",
    "comparison",
    "Accounting records and reports what happened; finance decides what to do with money next. They share fundamentals and diverge in daily work.\n\nAccounting careers (bookkeeping, financial accounting, audit, tax, controllership) reward accuracy, process discipline and knowledge of standards and regulation. Work is cyclical around closes and filings, professional qualifications carry weight, and the skills are portable across every industry.\n\nFinance careers (financial analysis and planning, corporate finance, treasury, investment analysis) reward modelling, judgment under uncertainty and persuasion. Work is more project-based and forward-looking, spreadsheets and presentations dominate, and credentials such as the CFA programme or an MBA are common on the investment side.\n\nChoose accounting if you like being right, closing loops and clear rules. Choose finance if you like building arguments from assumptions and influencing decisions. Many people start in accounting for its structured entry routes and move into finance once they read statements fluently; the reverse is rarer.\n\nRead ten job descriptions for each and note which tasks you would happily do on a dull Tuesday; that is a better guide than prestige.",
    ["khanFinance", "icai", "cfa", "acca", "blsOoh"],
    ["accounting", "finance", "comparison", "career choice", "cfa", "ca"],
    ["yYX4bvQSqbo", "64A6HJDEbKA"],
  ],
  [
    "hr-generalist-vs-recruiter",
    "Should I become an HR generalist or a recruiter?",
    ["HR generalist vs recruiter career", "What is the difference between HR and recruitment roles?"],
    "human-resources",
    "comparison",
    "Recruiting is one function within human resources, and the two career paths feel different day to day.\n\nRecruiters spend their time sourcing, screening, coordinating interviews and closing offers. The work is target-driven, fast and externally focused; success is measurable in hires and time-to-fill; agencies offer quick entry and training. It suits people who enjoy outreach, persuasion and pace.\n\nHR generalists handle the employee lifecycle after hiring: onboarding, policies, payroll and compliance coordination, performance cycles, employee relations, engagement. The work is process-heavy, internally focused and judgment-heavy; it suits people who like fairness, structure and long relationships.\n\nProgression differs: recruiters grow into talent acquisition leadership or specialise (technical, executive search); generalists grow into HR business partner or specialist roles (compensation, learning, employee relations).\n\nMany people start in recruiting because entry is easier, then move into generalist work; the reverse is also possible. Professional bodies such as SHRM and CIPD describe both tracks. Try a short internship or project in each if you can; the pace difference usually decides it.",
    ["shrm", "cipd", "linkedinTalentBlog"],
    ["hr", "recruiter", "generalist", "comparison", "career choice"],
    ["c1npicEPaHw", "RLVaBrFxhhA"],
  ],
];
