import type { Row } from "./schema";

/**
 * Technology and career-path comparisons. Every answer gives the trade-offs
 * and a way for the asker to decide from their own evidence; none declares a
 * universal winner or quotes market statistics.
 */
export const comparisonRows: Row[] = [
  [
    "python-vs-java-backend",
    "Should I learn Python or Java for backend development?",
    ["Python vs Java for backend jobs", "Which is better for backend, Python or Java?", "Java or Python for a backend developer career?"],
    "software-engineering",
    "comparison",
    "Both are mainstream backend languages with long futures; the choice should follow the jobs you want and the way you like to work.\n\nPython (Django, FastAPI, Flask) is faster to learn, concise, and dominant wherever backend work touches data, automation or machine learning. Startups and data-heavy products lean towards it. Its weaknesses are performance in CPU-bound work and looser structure in large codebases, which typing and discipline mitigate.\n\nJava (Spring Boot) is verbose but strongly typed and structured, with mature tooling and a huge footprint in banks, insurers, enterprises and large service companies. It teaches object-oriented design and concurrency rigorously, and those concepts transfer to C#, Kotlin and Go. Its weakness is a slower start and more ceremony.\n\nDecide with evidence: read thirty backend job descriptions in your target city and count the languages; check which one your college or current employer uses; and try building the same small API in both over two weekends. Choose the one where you finished and wanted to keep going.\n\nWhichever you pick, the transferable skills matter more: HTTP, databases and SQL, testing, Git, containers and deployment. Learn those deeply and a second language becomes a few weeks of syntax.",
    ["python", "fastapi", "javaLearn", "springGuides", "developerRoadmap"],
    ["python", "java", "backend", "comparison", "spring", "django"],
    ["rfscVS0vtbw", "grEKMHGYyns"],
  ],
  [
    "react-vs-angular",
    "Should I learn React or Angular?",
    ["React vs Angular for frontend jobs", "Which frontend framework should I learn first, React or Angular?", "Is Angular or React better for my career?"],
    "software-engineering",
    "comparison",
    "React is a library for building interfaces that you assemble with your own choices of router, state and tooling; Angular is a complete, opinionated framework with everything included and TypeScript from the start.\n\nReact has the larger share of job descriptions in most markets and the larger ecosystem, and its concepts carry into React Native for mobile and Next.js for full-stack work. The cost is decision fatigue: you must learn to choose libraries and structure projects yourself.\n\nAngular is common in enterprises and large service companies, especially where teams value consistency and long-term maintainability. It teaches structure, dependency injection and TypeScript discipline. The cost is a steeper initial curve and fewer, though often stable, openings.\n\nDecide by reading local job descriptions and by trying the official tutorial of each for a weekend. If you are undecided and have no local signal, React is the more common default because its fundamentals transfer widely.\n\nEither way, spend most of your effort on JavaScript, TypeScript, HTTP, accessibility and testing; a developer who understands those switches frameworks in weeks.",
    ["react", "typescript", "javascriptInfo", "webDev", "developerRoadmap"],
    ["react", "angular", "frontend", "comparison", "framework"],
    ["bMknfKXIFA8"],
  ],
  [
    "data-analyst-vs-data-scientist",
    "What is the difference between a data analyst and a data scientist?",
    ["Data analyst vs data scientist: which should I choose?", "Should I become a data analyst or a data scientist?", "Data analyst or data scientist for a beginner?"],
    "data-science",
    "comparison",
    "A data analyst answers questions about what happened and why, using SQL, spreadsheets, BI tools and descriptive statistics, and communicates findings to decision makers. A data scientist builds models to predict or classify, runs experiments and works closer to engineering, using Python or R, statistics and machine learning.\n\nEntry differs: analyst roles are more numerous, accept a wider range of backgrounds, and value business sense and communication; data scientist roles more often expect a quantitative degree or substantial project evidence and deeper statistics.\n\nDaily work differs: analysts spend time on data cleaning, dashboards and stakeholder questions; data scientists spend time on feature engineering, modelling, evaluation and increasingly on deploying models with engineers.\n\nFor most beginners the analyst route is the practical start: it builds the SQL, data-cleaning and business judgment that data science also needs, and internal moves from analyst to scientist are common once you add modelling.\n\nChoose data science directly only if you already have strong mathematics and programming and enjoy modelling more than explaining. Test it: do one Kaggle Learn track for each and notice which one you would continue unpaid.",
    ["kaggleLearn", "sqlbolt", "statLearning", "blsOoh", "googleDataAnalytics"],
    ["data analyst", "data scientist", "comparison", "career choice", "analytics"],
    ["YRJbhFLLPyE", "ua-CiDNNj30"],
  ],
  [
    "data-scientist-vs-ml-engineer",
    "Should I aim for data scientist or machine learning engineer?",
    ["Data scientist vs ML engineer: what is the difference?", "Machine learning engineer or data scientist for my career?"],
    "ai-ml",
    "comparison",
    "Data scientists focus on understanding data and building models that answer questions; machine learning engineers focus on turning models into reliable software that runs in production.\n\nData scientists spend more time on exploration, statistics, experiment design and communication; their output is often analysis, a prototype model and recommendations. Machine learning engineers spend more time on pipelines, training infrastructure, serving, monitoring and performance; their output is a deployed system. Many companies blur the roles, so read each job description rather than the title.\n\nChoose data science if you enjoy statistics, ambiguity and explaining findings, and you are comfortable that your work is judged by insight. Choose ML engineering if you enjoy software engineering, systems and reliability, and you want to see models used at scale.\n\nBackground fit: analysts and statisticians move naturally into data science; software engineers move naturally into ML engineering. Moving between them later is common.\n\nBoth need Python, SQL, machine learning fundamentals and evaluation discipline. Build one project that spans both (a model plus a deployed API with monitoring) and notice which half you spent your best hours on.",
    ["sklearn", "appliedMl", "mlSpecialization", "developerRoadmap"],
    ["data scientist", "machine learning engineer", "comparison", "mlops", "career choice"],
    ["ua-CiDNNj30", "PpiqSDMi4-4"],
  ],
  [
    "ai-engineer-vs-ml-engineer",
    "What is the difference between an AI engineer and a machine learning engineer?",
    ["AI engineer vs ML engineer: which should I become?", "Is AI engineering the same as machine learning engineering?"],
    "ai-ml",
    "comparison",
    "As companies use the titles today, a machine learning engineer trains, tunes and serves models built from data, while an AI engineer builds applications on top of existing foundation models: prompting, retrieval, tool use, agents, evaluation and integration.\n\nML engineering needs deeper mathematics, training infrastructure and data pipeline skills; the work is closer to research engineering and platform work. AI engineering needs strong software engineering, API and systems skills plus enough model understanding to design, evaluate and secure LLM features; the work is closer to product engineering.\n\nBackground fit: data scientists and quantitative graduates lean towards ML engineering; backend and full-stack developers lean towards AI engineering. Both need evaluation discipline, because shipping an unmeasured model or prompt is the most common failure in either job.\n\nThe titles are still settling and overlap in job descriptions, so read the responsibilities: 'train', 'fine-tune', 'feature pipeline' and 'GPU' point to ML engineering; 'RAG', 'agents', 'prompt', 'LLM application' and 'integration' point to AI engineering.\n\nTry both with one weekend each: fine-tune a small model on a task, and build a retrieval-based assistant over documents. Whichever felt like your kind of problem is your answer.",
    ["genaiBeginners", "hfLearn", "llmCourse", "appliedMl", "developerRoadmap"],
    ["ai engineer", "machine learning engineer", "comparison", "llm", "career choice"],
    ["nJ25yl34Uqw", "PpiqSDMi4-4"],
  ],
  [
    "frontend-vs-backend-choice",
    "Should I choose frontend or backend development?",
    ["Frontend vs backend: which is better for a beginner?", "Is backend or frontend a better career?", "How do I decide between frontend and backend?"],
    "software-engineering",
    "comparison",
    "Frontend developers build what users see and touch: layout, interaction, accessibility, performance in the browser. Backend developers build what makes it work: APIs, data models, authentication, business logic, reliability.\n\nFrontend suits people who like visible results, design collaboration, quick feedback and the particular puzzle of making things work across devices and browsers. Backend suits people who like data modelling, systems thinking, correctness and performance, and who are happy when the evidence of good work is that nothing broke.\n\nNeither is easier or more valuable; both have plenty of roles and both are deep. Frontend has more visible ambiguity (design, UX); backend has more invisible complexity (concurrency, data integrity, scale).\n\nMost people should not decide from descriptions. Build a small full-stack app: a form, an API, a database, a deployed page. Notice which bugs you enjoyed chasing. Then read job descriptions for both in your area and compare the skills they repeat with what you enjoyed.\n\nMany developers start on one side and drift to full-stack; starting anywhere is fine as long as you finish projects.",
    ["webDev", "nodeLearn", "fullstackOpen", "developerRoadmap"],
    ["frontend", "backend", "comparison", "career choice", "beginner"],
    ["GxmfcnU3feo"],
  ],
  [
    "javascript-vs-typescript",
    "Should I learn JavaScript or TypeScript first?",
    ["JavaScript vs TypeScript for beginners", "Do I still need to learn JavaScript if I learn TypeScript?", "Is TypeScript replacing JavaScript?"],
    "software-engineering",
    "comparison",
    "TypeScript is JavaScript with types added and compiled away, so there is no real either-or: you must know JavaScript to use TypeScript, and almost every TypeScript job expects both.\n\nLearn JavaScript first until the core is solid: functions, objects, arrays, closures, promises and async/await, modules, the DOM, and the event loop. Trying to learn types at the same time doubles the concepts and makes compiler errors confusing.\n\nMove to TypeScript as soon as you start a project bigger than a few files. Convert an existing JavaScript project gradually and let the compiler teach you: every error it raises is a bug or a misunderstanding you already had.\n\nIn job descriptions, TypeScript appears in most modern frontend and Node roles, so plan to be comfortable with both within your first year. The order is fixed; only the timing is yours to choose.",
    ["javascriptInfo", "typescript", "javascript", "eloquentJs"],
    ["javascript", "typescript", "comparison", "learning order", "beginner"],
    ["jS4aFq5-91M", "30LWjhZzg50"],
  ],
  [
    "django-vs-fastapi",
    "Should I use Django or FastAPI for my backend projects?",
    ["Django vs FastAPI: which should I learn?", "Is FastAPI or Django better for Python backend jobs?"],
    "software-engineering",
    "comparison",
    "Django is a full-featured framework with an ORM, admin interface, authentication, forms and migrations built in. FastAPI is a modern, minimal framework for building typed APIs quickly, and you assemble the rest yourself.\n\nChoose Django when you are building a complete web application with user accounts, an admin area and server-rendered pages, or when job descriptions in your area name Django or Django REST Framework, which is common in established companies. It teaches good defaults and security practices.\n\nChoose FastAPI when you are building APIs for a separate frontend or for machine learning services, want automatic documentation and validation from type hints, and value async performance. It is increasingly common in startups and data teams.\n\nFor learning, FastAPI shows you HTTP and validation with less magic; Django shows you how a full application fits together. Many Python developers know both. If you must pick one for a portfolio, build the project that matches the jobs you want, then spend a weekend on the other so you can discuss the trade-offs in interviews.",
    ["django", "fastapi", "flask", "python"],
    ["django", "fastapi", "python", "backend", "comparison", "framework"],
    ["o0XbHvKxw7Y", "tLKKmouUams"],
  ],
  [
    "sql-vs-nosql",
    "Should I learn SQL or NoSQL databases first?",
    ["SQL vs NoSQL for a beginner developer", "Do I need MongoDB if I know PostgreSQL?", "Which database should I learn first?"],
    "software-engineering",
    "comparison",
    "Learn SQL first. Relational databases are the default in most applications and analytics, SQL appears in the majority of developer, analyst and data job descriptions, and the concepts (schemas, keys, joins, transactions, indexes) are the foundation for understanding any other store.\n\nLearn a document database such as MongoDB when a project genuinely needs flexible schemas or when a job description names it; the learning cost is small once you understand data modelling. Learn key-value and caching stores such as Redis when you need speed or sessions, and know that many teams use them alongside a relational database rather than instead of it.\n\nThe interview question is rarely 'which is better' but 'when would you choose each'. Prepare an answer: consistency and relationships favour relational; very high write volumes, flexible documents or simple key lookups can favour others; and the operational maturity of your team matters more than either.\n\nPractise with PostgreSQL: design a schema for a small domain, write joins and aggregates, add indexes and read the query plan. That single exercise covers more interview ground than a tour of five databases.",
    ["sql", "sqlbolt", "modeSql", "systemDesignPrimer"],
    ["sql", "nosql", "postgresql", "mongodb", "database", "comparison"],
    ["HXV3zeQKqGY"],
  ],
  [
    "python-vs-r-data",
    "Should I learn Python or R for data science?",
    ["Python vs R for data analysis jobs", "Is R still worth learning for data roles?"],
    "data-science",
    "comparison",
    "Python is the general-purpose choice: it covers data analysis, machine learning, automation, web APIs and production deployment with one language, and it dominates job descriptions for data science and machine learning roles. R is a language built for statistics with an exceptional ecosystem for statistical modelling, visualisation and reporting, and it remains strong in academia, research, biostatistics and some analytics teams.\n\nChoose Python if you want the broadest range of roles or expect to work with engineers on deployed systems. Choose R if your target field is research-oriented, if your degree programme uses it, or if the analytics teams you are targeting name it.\n\nLearning one makes the second easy, because the hard parts (statistics, data cleaning judgment, communicating results) transfer. Do not learn both at once as a beginner; pick from local job descriptions and commit for six months.\n\nSQL matters more than this choice for most data roles; make sure it is solid regardless.",
    ["python", "pandas", "kaggleLearn", "statLearning", "sqlbolt"],
    ["python", "r", "data science", "comparison", "statistics"],
    ["r-uOLxNrNk8"],
  ],
  [
    "power-bi-vs-tableau",
    "Should I learn Power BI or Tableau?",
    ["Power BI vs Tableau for data analyst jobs", "Which BI tool should I learn first?"],
    "data-science",
    "comparison",
    "Both are mainstream business intelligence tools and the skills transfer between them: data modelling, calculated measures, chart choice and dashboard design are the same craft.\n\nPower BI is common in organisations that run on Microsoft tooling, is cheaper for teams to adopt, and its free desktop version lets you build full reports for a portfolio. Its query and DAX layers reward analysts who like modelling.\n\nTableau is strong for exploratory visual analysis and polished dashboards, remains common in large enterprises and consultancies, and Tableau Public gives you a shareable portfolio for free.\n\nDecide from job descriptions in your area: count which tool appears more for the roles you want. If they are close, Power BI is the more common default in many markets and easier to practise fully offline. Learn the second tool in a few weeks once you need it; the modelling and design skills are what you are really building.\n\nWhichever you choose, pair it with SQL and spreadsheet skills; the tool alone rarely gets an analyst role.",
    ["powerbi", "tableauTraining", "sqlbolt"],
    ["power bi", "tableau", "bi", "comparison", "data analyst"],
    ["FwjaHCVNBWA", "TPMlZxRRaBQ"],
  ],
  [
    "devops-vs-cloud-engineer",
    "What is the difference between a DevOps engineer and a cloud engineer?",
    ["DevOps vs cloud engineer: which should I choose?", "Should I become a DevOps engineer or a cloud engineer?"],
    "devops",
    "comparison",
    "The titles overlap heavily, but the emphasis differs. A cloud engineer designs, builds and operates infrastructure on a provider such as AWS or Azure: networking, identity, compute, storage, cost and security. A DevOps engineer focuses on the delivery pipeline and the practices around it: CI/CD, automation, containers, monitoring and the collaboration between development and operations.\n\nIn practice most DevOps roles require cloud skills and most cloud roles require automation, so the shared core is large: Linux, networking, scripting, infrastructure as code, containers and monitoring.\n\nChoose the cloud engineering framing if you enjoy architecture, security and infrastructure design, and if certifications and provider depth appeal to you. Choose the DevOps framing if you enjoy automation, developer tooling and improving how teams ship. Site reliability engineering and platform engineering are related specialisations that lean towards reliability and internal platforms respectively.\n\nRead ten job descriptions of each in your area and compare the tool lists; they usually differ less than the titles suggest. Build one project that covers both (Terraform-defined infrastructure plus a CI/CD pipeline plus monitoring) and you will be credible for either.",
    ["awsTraining", "terraform", "githubActions", "devopsRoadmapRepo", "sreBooks"],
    ["devops", "cloud engineer", "comparison", "sre", "platform engineering"],
    ["1J2YOV6LcwY", "6eroP2XGtTI"],
  ],
  [
    "cybersecurity-vs-software-development",
    "Should I choose cybersecurity or software development?",
    ["Cybersecurity vs software engineering as a career", "Is cybersecurity a better career than programming?"],
    "career-guidance",
    "comparison",
    "Software development builds systems; cybersecurity protects them, tests them and responds when they fail. They overlap in application security, where developers and security engineers meet.\n\nDevelopment has more entry-level roles in most markets and a clearer self-taught route: build projects, show code. It suits people who enjoy creating and shipping.\n\nCybersecurity entry roles (SOC analyst, security operations, IT security) usually expect system and network fundamentals first, and offensive roles expect practical lab evidence. It suits people who enjoy investigation, adversarial thinking and operations, and who are comfortable with on-call and incident pressure.\n\nMany strong security engineers started as developers or system administrators, because understanding how systems are built is the foundation for securing them. If you are undecided, learning to program and administer systems keeps both doors open; adding security labs later is easier than the reverse.\n\nTest each: build and deploy a small web app, then attack it in a lab using the PortSwigger academy exercises. Notice which half you kept going back to.",
    ["portswigger", "owaspTop10", "cs50", "security", "developerRoadmap"],
    ["cybersecurity", "software development", "comparison", "career choice"],
    ["9HOpanT0GRs", "GxmfcnU3feo"],
  ],
  [
    "manual-vs-automation-testing",
    "Should I focus on manual testing or automation testing?",
    ["Manual vs automation testing career", "Is manual testing still a viable career?"],
    "qa-testing",
    "comparison",
    "Manual and automated testing are not rival careers; they are two skills in one profession, and the roles with the most options combine them.\n\nManual (exploratory and scripted) testing is where judgment lives: understanding the product, designing test cases from risk, finding the bugs no script anticipated, and communicating clearly. It remains essential, especially for usability, new features and complex workflows. Roles that are purely manual exist but are more numerous in service companies and tend to plateau earlier.\n\nAutomation adds programming: writing maintainable suites, integrating with CI, API and performance testing. It opens SDET and quality engineering roles and is expected in most product companies.\n\nThe practical path: start with strong manual testing fundamentals (test design techniques, bug reporting, exploratory sessions), then learn one language and one automation framework and automate the regression cases you know best. A tester who can decide what to automate is more valuable than one who automates everything.\n\nIf you are already a manual tester, adding automation is the highest-return investment; if you are new, learn both from the start.",
    ["istqb", "testing", "selenium", "testAutomationU"],
    ["manual testing", "automation testing", "qa", "comparison", "sdet"],
    ["sO8eGL6SFsA", "jydYq7oAtD8"],
  ],
  [
    "java-vs-javascript-first",
    "Should I learn Java or JavaScript first?",
    ["Java vs JavaScript for a beginner", "Is Java or JavaScript better to start programming with?"],
    "software-engineering",
    "comparison",
    "Despite the names, these are unrelated languages for different purposes. JavaScript runs in browsers and, with Node, on servers; it is the language of web interfaces. Java is a general-purpose, strongly typed language used heavily in enterprise backends, Android and large systems.\n\nStart with JavaScript if you want to see results in a browser quickly, are drawn to web or full-stack work, or want the fastest path to a portfolio you can share as a link. Start with Java if you want structure and types from day one, are aiming at enterprise backend or Android roles, or your course or local employers favour it.\n\nBoth teach programming fundamentals adequately; JavaScript is more forgiving early and less forgiving later, Java is the reverse. Neither locks you in: the second language of any pair takes weeks once you understand variables, control flow, functions, data structures and debugging.\n\nDecide from what you want to build in the next three months, then commit. Switching languages mid-way is the most common way beginners lose momentum.",
    ["javascriptInfo", "javaLearn", "cs50", "developerRoadmap"],
    ["java", "javascript", "beginner", "comparison", "first language"],
    ["grEKMHGYyns", "jS4aFq5-91M"],
  ],
  [
    "bootcamp-vs-self-taught-vs-degree",
    "Should I self-study, join a bootcamp or get a degree to become a developer?",
    ["Self-taught vs bootcamp vs degree for software jobs", "Is a computer science degree necessary to become a programmer?"],
    "education",
    "comparison",
    "Each route can lead to a developer job; they differ in cost, structure, signalling and what they leave out.\n\nA degree gives depth in fundamentals, time, a credential that some employers and visa systems require, and campus recruitment. It is slow and expensive, and it rarely teaches modern tooling or shipping; you still need projects.\n\nA bootcamp gives structure, pace, peers and a curriculum aimed at jobs, in months. Quality varies enormously; outcomes depend on your effort and the local market. Check any placement claims carefully and ask for verifiable alumni contacts before paying.\n\nSelf-study is the cheapest and most flexible and, with free curricula such as CS50, The Odin Project, Full Stack Open and the OSSU path, it is complete. It demands discipline, a self-built network and stronger portfolio evidence, because you have no credential to lean on.\n\nDecide by constraints: if you have time and want fundamentals, a degree or OSSU-style self-study; if you need structure and can afford it, a bootcamp with verified outcomes; if you are disciplined and budget-limited, self-study with a public portfolio and open-source contributions.\n\nIn every case, employers hire on what you can build and explain; the route is context, not the decision.",
    ["cs50", "odin", "fullstackOpen", "ossu", "freecodecamp"],
    ["bootcamp", "degree", "self-taught", "comparison", "software developer"],
  ],
];
