import type { Row } from "./schema";

/**
 * Data, analytics, machine learning, generative AI and LLM engineering paths.
 * Answers name the skills employers repeat, a concrete portfolio piece and the
 * signals that someone is ready to apply. Nothing here quotes pay or demand.
 */
export const dataAiRows: Row[] = [
  [
    "ai-engineer-roadmap",
    "How do I become an AI engineer?",
    ["AI engineer roadmap", "What should I learn to become an AI engineer?", "How do I get into AI engineering as a developer?", "Give me a roadmap for AI engineering"],
    "ai-ml",
    "roadmap",
    "AI engineering, as job descriptions use the term now, means building products on top of models rather than training models from scratch. It is closer to backend engineering than to research.\n\nPhase 1: engineering foundations. Solid Python, HTTP and APIs, a relational database, Git, testing and Docker. If you already work as a developer you have this; if not, spend the first months here because everything else sits on it.\n\nPhase 2: model APIs and prompting. Learn to call a hosted model (OpenAI, Anthropic, Gemini or an open model through Hugging Face), structure prompts, get JSON out reliably, handle streaming, and manage cost and latency. Understand tokens, context windows, temperature and why outputs vary.\n\nPhase 3: retrieval and tools. Build a retrieval-augmented generation system: chunking, embeddings, a vector store, reranking and citation. Then add tool use so the model can call your functions safely, and learn the basics of agent loops and where they fail.\n\nPhase 4: evaluation and production. Write evaluation sets, measure quality over time, add guardrails for unsafe or off-topic output, log everything, and deploy with monitoring. This is what separates a demo from a product and what senior interviewers probe.\n\nPortfolio: an assistant over a real document set with citations, evaluation results in the README, and a cost-per-query estimate. Generative AI for Beginners and the DeepLearning.AI short courses cover the patterns; the provider documentation covers the details.\n\nReady when you can explain how you would stop a chatbot answering from the wrong document, measure whether a prompt change helped, and keep a user's data out of a provider's training set.",
    ["genaiBeginners", "dlaiShortCourses", "openaiDocs", "claudeDocs", "langchain", "hfLearn", "developerRoadmap"],
    ["ai engineer", "generative ai", "llm", "rag", "agents", "prompting", "roadmap"],
    ["nJ25yl34Uqw", "xZDB1naRUlk"],
  ],
  [
    "llm-engineer-roadmap",
    "How do I become an LLM engineer?",
    ["What should I learn to build applications with large language models?", "LLM engineering roadmap", "How do I specialise in large language models?"],
    "ai-ml",
    "roadmap",
    "LLM engineering spans two overlapping jobs: building applications on models, and adapting or serving the models themselves. Decide which end you want first, because the second needs far more mathematics and hardware access.\n\nApplication track: Python, APIs, prompt design, structured outputs, retrieval-augmented generation, tool calling, agents, evaluation and observability. Study the provider docs for two different model families so you learn what is general and what is vendor-specific.\n\nModel track: linear algebra and probability refreshers, PyTorch, the transformer architecture, tokenisation, attention, training and fine-tuning (LoRA and similar), quantisation, and inference serving. Karpathy's build-GPT lecture and the LLMs-from-scratch repository teach the internals honestly; the Hugging Face course covers the practical library layer.\n\nBoth tracks need evaluation skills: constructing test sets, judging outputs consistently, and understanding failure modes such as hallucination, prompt injection and data leakage.\n\nPortfolio: for the application track, a RAG or agent system with evaluation numbers and a security section. For the model track, a fine-tuned small model on a specific task with before-and-after metrics and a write-up of what did not work.\n\nReady when you can explain attention in plain language, describe when fine-tuning beats retrieval, and show one experiment where you measured rather than guessed.",
    ["llmsFromScratch", "llmCourse", "hfLearn", "transformers", "pytorch", "promptingGuide", "openaiCookbook"],
    ["llm", "large language models", "transformers", "fine-tuning", "rag", "roadmap"],
    ["zjkBMFhNj_g", "sVcwVQRHIc8"],
  ],
  [
    "generative-ai-roadmap",
    "How do I learn generative AI from scratch?",
    ["Give me a generative AI roadmap", "How do I start with generative AI?", "What is a good learning path for generative AI?", "How do I become a generative AI developer?"],
    "ai-ml",
    "roadmap",
    "Generative AI is learnable without a research background if you approach it as building with models first and understanding them second.\n\nWeeks 1-2: concepts. What a language model does, tokens, context, sampling, embeddings, and the difference between text, image and multimodal models. Watch one solid conceptual introduction and read the prompt engineering guide.\n\nWeeks 3-6: building. Call a model API from Python, then build three small things: a summariser with structured output, a question-answering tool over your own files using retrieval, and a tool-calling assistant that can look something up. Learn to log and compare outputs.\n\nWeeks 7-10: depth. Evaluation, guardrails, cost control, caching, and the basics of fine-tuning with open models through Hugging Face. Learn where generative systems fail and how to detect it.\n\nOngoing: read the Generative AI for Beginners lessons in order and the OpenAI Cookbook examples; both are free and current.\n\nPortfolio: one deployed application with an evaluation section and a limitations section. Employers trust candidates who can say what their system gets wrong.\n\nYou have a foundation when you can explain retrieval versus fine-tuning, build a prompt that returns valid JSON every time, and describe one prompt-injection risk and its mitigation.",
    ["genaiBeginners", "promptingGuide", "openaiCookbook", "hfLearn", "dlaiShortCourses", "claudeDocs"],
    ["generative ai", "genai", "llm", "prompting", "beginner", "roadmap"],
    ["mEsleV16qdo", "_ZvnD73m40o"],
  ],
  [
    "machine-learning-learning",
    "How do I learn machine learning from scratch?",
    ["What is a good machine learning study plan for beginners?", "How do I start learning ML?", "Machine learning roadmap for beginners"],
    "ai-ml",
    "roadmap",
    "Learn machine learning in three interleaved strands: mathematics you can use, code you can run, and problems you understand.\n\nMathematics: linear algebra (vectors, matrices, dot products), probability and statistics (distributions, expectation, conditional probability), and basic calculus (derivatives, gradients). You need working intuition, not proofs. Khan Academy and MIT OpenCourseWare cover it free.\n\nCode: Python with NumPy and pandas, then scikit-learn. Implement linear regression and logistic regression by hand once, then use the library. Learn the workflow: split data, train, validate, tune, test, and never touch the test set until the end.\n\nProblems: start with tabular datasets on Kaggle Learn, do the exercises, and enter one beginner competition. Learn to read a confusion matrix and explain precision versus recall in a sentence.\n\nThen deep learning: the fast.ai course or Dive into Deep Learning, with PyTorch. Build one image and one text model.\n\nPortfolio: an end-to-end project on real data with a clear question, feature engineering, honest evaluation, a discussion of leakage and bias, and a simple deployment (an API or a notebook app).\n\nYou have a foundation when you can explain overfitting with an example from your own work, choose an evaluation metric for a business question, and describe why a model that scores well offline might fail in production.",
    ["mlSpecialization", "mlForBeginners", "sklearn", "kaggleLearn", "fastai", "d2l", "ml"],
    ["machine learning", "ml", "scikit-learn", "deep learning", "beginner", "roadmap"],
    ["i_LwzRVP7bg", "7IgVGSaQPaw"],
  ],
  [
    "deep-learning-learning",
    "How do I learn deep learning properly?",
    ["Where do I start with neural networks?", "What is the best way to learn deep learning with PyTorch?", "Deep learning study plan"],
    "ai-ml",
    "roadmap",
    "Learn deep learning code-first, then fill in theory as questions arise; the reverse order loses most people in notation.\n\nStep 1: prerequisites. Comfortable Python, NumPy arrays, basic linear algebra and derivatives, and one classical machine learning project so you already understand training and validation.\n\nStep 2: a code-first course. fast.ai's Practical Deep Learning or the official PyTorch tutorials. Train an image classifier in the first week, then look inside: tensors, autograd, the training loop, loss functions, optimisers and learning rates.\n\nStep 3: architectures with purpose. Convolutional networks for images, recurrent and transformer models for sequences, embeddings for text. For each, build one small project and one experiment that changes a single variable.\n\nStep 4: practice that resembles work. Data pipelines, augmentation, transfer learning from pretrained models, experiment tracking, GPU basics and reproducibility. Dive into Deep Learning is the free textbook to keep beside you.\n\nPortfolio: a project with a baseline, two improvements you can explain, and a write-up of a failure. Interviewers ask about what went wrong more than about what worked.\n\nYou are ready for junior deep learning work when you can write a training loop from memory, explain why a loss stops decreasing, and pick a pretrained model for a new task with reasons.",
    ["fastai", "pytorch", "d2l", "tensorflow", "hfLearn"],
    ["deep learning", "neural networks", "pytorch", "tensorflow", "transformers"],
    ["VyWAvY2CF9c", "V_xro1bcAuA"],
  ],
  [
    "rag-systems-learning",
    "How do I learn to build RAG systems?",
    ["How does retrieval-augmented generation work in practice?", "What should I study to build a document question answering chatbot?", "How do I build a chatbot over my own documents?"],
    "ai-ml",
    "roadmap",
    "Retrieval-augmented generation gives a model your documents at answer time. Learning it well means learning each stage and how it fails.\n\nStage 1: ingestion. Parse documents (PDF, HTML, Markdown), clean them, and split into chunks that keep meaning together. Chunk size and overlap are your first experiment.\n\nStage 2: retrieval. Create embeddings, store them in a vector database or even a local index, and retrieve by similarity. Add keyword search and fuse the results; hybrid retrieval beats either alone on most real corpora. Learn reranking.\n\nStage 3: generation. Build a prompt that answers only from retrieved passages, cites them, and declines when nothing relevant exists. Structured output makes this testable.\n\nStage 4: evaluation. Write twenty to fifty question-answer pairs, measure retrieval hit rate and answer faithfulness, and re-run them after every change. Without this you are guessing.\n\nStage 5: production concerns. Access control on documents, freshness, caching, cost, and prompt injection through the documents themselves.\n\nThe freeCodeCamp RAG course, LangChain and LlamaIndex documentation, and the OpenAI Cookbook cover the mechanics. Build one system over a corpus you know well (course notes, a product manual) so you can judge answer quality yourself. Ready when you can explain why a correct document was not retrieved and fix it.",
    ["langchain", "llamaindex", "openaiCookbook", "genaiBeginners", "dlaiShortCourses"],
    ["rag", "retrieval augmented generation", "embeddings", "vector database", "chatbot", "llm"],
    ["sVcwVQRHIc8"],
  ],
  [
    "prompt-engineering-skill",
    "How do I get good at prompt engineering?",
    ["How do I write better prompts for AI models?", "Is prompt engineering a skill worth learning?", "How do I learn prompt engineering systematically?"],
    "ai-ml",
    "roadmap",
    "Prompt engineering is a real skill but a narrow one: it is the craft of specifying a task clearly to a model and verifying the result. It is worth learning as part of a broader engineering or domain role rather than as a career on its own.\n\nLearn the techniques with names: clear role and task framing, examples (few-shot), asking for step-by-step reasoning, structured output formats, constraints and refusal instructions, and decomposing a task into stages. The Prompt Engineering Guide and each provider's documentation describe these with examples.\n\nThen learn to test. Build a small set of inputs with expected outputs, run each prompt version against all of them, and keep the version that scores best rather than the one that felt best on one example. Track cost and latency alongside quality.\n\nUnderstand the failure modes: hallucination, sensitivity to wording, prompt injection from untrusted content, and drift when the model version changes. Good prompt engineers design for these.\n\nPractice: take a task from your own work (summarising tickets, drafting emails, extracting fields from documents), write three prompt versions, evaluate them, and document the winner and why. That document is portfolio evidence.\n\nYou are competent when your prompts return valid structured output reliably and you can explain how you know a change improved results.",
    ["promptingGuide", "promptGuideRepo", "claudeDocs", "openaiDocs", "dlaiShortCourses"],
    ["prompt engineering", "prompts", "llm", "generative ai", "evaluation"],
    ["_ZvnD73m40o"],
  ],
  [
    "ai-agents-learning",
    "How do I learn to build AI agents?",
    ["What should I study to build agentic AI systems?", "How do LLM agents work and how do I start building them?", "Agentic AI roadmap"],
    "ai-ml",
    "roadmap",
    "An agent is a model in a loop that can decide to call tools, observe results and continue until a goal is met. Learn it after you are comfortable calling a model API and getting structured output, because agents amplify every weakness in prompting.\n\nStart by building the simplest loop yourself without a framework: the model chooses a tool from a small list, your code executes it, the result goes back into the conversation, repeat with a step limit. This teaches you what frameworks hide. Then try one framework to see the patterns it standardises.\n\nLearn the safety mechanics: input validation on tool arguments, permission boundaries, timeouts, maximum steps, cost caps, and human confirmation for anything irreversible. Learn to log every step so failures are debuggable.\n\nStudy retrieval and memory, multi-agent hand-offs, and evaluation of agent runs (did it finish, how many steps, did it use the right tools).\n\nPortfolio: an agent that completes one useful bounded task, such as triaging support emails into a tracker or researching a question across a few allowed sources, with a run log, a test suite of tasks and an honest failure analysis.\n\nReady when you can explain why an agent looped forever and how you prevented it, and describe how you would keep it from taking a harmful action on a bad instruction hidden in a web page.",
    ["genaiBeginners", "claudeDocs", "openaiDocs", "langchain", "dlaiShortCourses"],
    ["ai agents", "agentic ai", "tool calling", "llm", "automation"],
    ["Zy7EXDONlTY"],
  ],
  [
    "python-for-data-analysis",
    "How do I learn Python for data analysis?",
    ["What Python should a data analyst learn?", "How do I learn pandas for analytics work?", "Python for data analytics roadmap"],
    "data-science",
    "roadmap",
    "For analysis work you need a specific slice of Python, not all of it. Learn the language basics (variables, lists, dictionaries, loops, functions, reading files) in the first week, then move straight to the data stack.\n\npandas is the core: loading CSV and Excel files, selecting and filtering rows, handling missing values, groupby and aggregation, merging tables, reshaping with pivot and melt, and working with dates. Practise on messy real data rather than clean tutorial sets; Kaggle datasets and public government data are good sources.\n\nAdd NumPy for arrays and vectorised operations, Matplotlib or Seaborn for charts you can explain, and Jupyter notebooks for exploration. Then learn to turn a notebook into a reusable script with functions.\n\nCombine it with SQL: pull data with a query, finish the analysis in pandas, and know which tool suits which step.\n\nPortfolio: one analysis notebook that starts with a question, documents cleaning decisions, produces three or four charts with interpretations, and ends with a recommendation and its limitations. Publish it with the data source linked.\n\nYou know enough when you can clean a new dataset in an hour, explain a groupby result to a non-technical colleague, and spot when a chart is misleading.",
    ["pandas", "numpy", "kaggleLearn", "automate", "python"],
    ["python", "pandas", "data analysis", "numpy", "jupyter", "analytics"],
    ["r-uOLxNrNk8", "gtjxAH8uaP0"],
  ],
  [
    "power-bi-learning",
    "How do I learn Power BI for analyst jobs?",
    ["What should I practise in Power BI?", "How do I build a Power BI portfolio?", "Is Power BI enough to get a data analyst role?"],
    "data-science",
    "roadmap",
    "Power BI appears in a large share of analyst job descriptions, so learning it well is a practical investment. Learn it as a workflow, not as a list of buttons.\n\nStep 1: data. Connect to files and a database, clean and shape data in Power Query (types, splitting columns, unpivoting, merging queries). Most real Power BI work is data preparation.\n\nStep 2: modelling. Build a star schema with fact and dimension tables, set relationships correctly, and understand why a flat table causes wrong totals. Learn DAX gradually: measures before calculated columns, CALCULATE and filter context, time intelligence.\n\nStep 3: reports. Choose charts for the question, design for the reader (one message per page, consistent colours, clear titles), add slicers and drill-through, and test performance.\n\nStep 4: sharing. Publish to the service, understand workspaces, scheduled refresh and row-level security at a basic level.\n\nMicrosoft Learn's Power BI paths are free and official. Build two dashboards on public datasets: one operational (sales or tickets) and one analytical (trend and segment comparison), each with a short write-up of the decisions and the insight.\n\nPower BI alone rarely secures an analyst role; pair it with SQL and Excel. You are ready when you can explain filter context, fix a wrong total, and defend a chart choice.",
    ["powerbi", "sqlbolt", "excelSupport", "kaggleLearn"],
    ["power bi", "dashboards", "dax", "power query", "data analyst", "bi"],
    ["FwjaHCVNBWA"],
  ],
  [
    "tableau-learning",
    "How do I learn Tableau for data visualisation roles?",
    ["What should I practise in Tableau?", "How do I build a Tableau portfolio?"],
    "data-science",
    "roadmap",
    "Tableau is strongest at exploratory visual analysis, so learn it by asking questions of data rather than by memorising features.\n\nStart with the official free training videos: connecting to data, dimensions versus measures, the marks card, filters, groups and sets. Then learn calculated fields, table calculations, level-of-detail expressions and parameters; these are what separate a basic user from an analyst.\n\nDesign dashboards for a reader: one clear question per view, appropriate chart types, actions that link views, and mobile layouts where relevant. Learn performance basics such as extracts versus live connections.\n\nPublish to Tableau Public; a public profile with three well-designed dashboards on real datasets is a portfolio recruiters can open immediately. Write a short description under each explaining the question and the insight.\n\nPair Tableau with SQL and spreadsheet skills. You are ready when you can build a dashboard from a raw dataset in a few hours, explain a level-of-detail calculation, and justify each chart choice.",
    ["tableauTraining", "sqlbolt", "kaggleLearn"],
    ["tableau", "data visualisation", "dashboards", "analyst", "bi"],
    ["TPMlZxRRaBQ"],
  ],
  [
    "data-analyst-interview-prep",
    "How do I prepare for a data analyst interview?",
    ["What is asked in data analyst interviews?", "How do I practise for an analytics interview?", "Data analyst interview preparation plan"],
    "data-science",
    "interview",
    "Data analyst interviews usually have four parts: a SQL exercise, a case or business question, a discussion of your projects, and behavioural questions.\n\nSQL: practise joins, aggregation with GROUP BY and HAVING, window functions (ROW_NUMBER, LAG, running totals), date handling and subqueries or CTEs. Expect to write queries live and to explain what a result means. SQLBolt and Mode's tutorial cover the syntax; practise on HackerRank or with your own questions against a public dataset.\n\nCase questions: 'Sales dropped last month, how would you investigate?' Structure your answer: clarify the metric, segment the data (time, region, product, channel), check data quality, form hypotheses, and say what you would recommend. Interviewers want the method, not a guess.\n\nProjects: prepare to walk through one analysis end to end: the question, the cleaning decisions, the chart, the insight and what you would do differently. Have the notebook or dashboard ready to share.\n\nStatistics basics come up: mean versus median, distributions, correlation versus causation, A/B test intuition.\n\nBehavioural: stories about communicating a finding a stakeholder did not like, and about a mistake in an analysis and how you caught it.\n\nRun a mock interview with a friend acting as a non-technical manager; explaining a result simply is the skill most candidates underestimate.",
    ["sqlbolt", "modeSql", "hackerrank", "statistics", "kaggleLearn"],
    ["data analyst", "interview", "sql", "case study", "analytics"],
    ["cnjhHZNJEDk"],
  ],
  [
    "data-science-interview-prep",
    "How do I prepare for a data science interview?",
    ["What do data science interviews test?", "Data scientist interview preparation plan", "How do I practise for ML interview rounds?"],
    "data-science",
    "interview",
    "Data science interviews vary by company, but most combine coding, statistics and machine learning, a case study, and a project deep-dive.\n\nCoding: Python and SQL exercises, usually data manipulation rather than algorithm puzzles. Practise pandas transformations and SQL window functions until they are quick.\n\nStatistics and probability: hypothesis testing, p-values and their misuse, confidence intervals, distributions, Bayes' rule, and experiment design. Be able to explain each with an example, not just a definition.\n\nMachine learning: bias-variance trade-off, cross-validation, regularisation, feature engineering, evaluation metrics and when to use each, handling imbalanced data, leakage, and the reasoning behind choosing a simple model. Expect 'how would you build a model to predict X' questions; answer with the full workflow including how you would measure success in the business.\n\nCase study: define the metric, discuss data availability and quality, propose an approach, and mention risks. Practise out loud.\n\nProject deep-dive: choose a project where you made real decisions. Interviewers probe the weakest part, so know your limitations and what you would improve.\n\nAn Introduction to Statistical Learning and the scikit-learn user guide are the two references that cover the most ground for this preparation.",
    ["statLearning", "sklearn", "statistics", "kaggleLearn", "techInterviewHandbook"],
    ["data science", "interview", "statistics", "machine learning", "case study"],
    ["xxpc-HPKN28"],
  ],
  [
    "ml-engineer-interview-prep",
    "How do I prepare for a machine learning engineer interview?",
    ["What is asked in ML engineer interviews?", "How do I prepare for an ML system design round?"],
    "ai-ml",
    "interview",
    "Machine learning engineer interviews add engineering depth to data science questions: coding rounds closer to software interviews, ML fundamentals, an ML system design round, and discussion of production experience.\n\nCoding: data structures and algorithms at a moderate level, plus Python fluency. NeetCode-style practice for a few weeks is usually enough for most product companies.\n\nML fundamentals: the same ground as data science interviews, with more emphasis on training dynamics, optimisation, regularisation and model debugging.\n\nML system design: 'Design a recommendation system' or 'Design fraud detection'. Structure: clarify the goal and constraints, define online and offline metrics, describe data collection and features, choose a model family with reasons, plan training and serving, and cover monitoring, retraining and failure handling. The Applied ML repository shows how real companies made these decisions.\n\nProduction: be ready to discuss feature stores, batch versus real-time inference, model versioning, drift and A/B testing, even if your experience is from a personal project that you deployed.\n\nPrepare one project where you can describe the full lifecycle honestly, including what broke. Practise the system design round aloud with a timer; structure matters more than reaching a perfect architecture.",
    ["appliedMl", "neetcode", "sklearn", "systemDesignPrimer", "techInterviewHandbook"],
    ["machine learning engineer", "interview", "ml system design", "mlops"],
    ["PpiqSDMi4-4"],
  ],
  [
    "data-analytics-portfolio",
    "What should a data analytics portfolio contain?",
    ["How do I build a data analyst portfolio with no work experience?", "Which projects impress for data analyst roles?"],
    "portfolio",
    "portfolio",
    "A strong analytics portfolio shows judgment, not tool coverage. Three finished projects beat ten notebooks.\n\nProject 1: an end-to-end analysis. Start from a real question on a messy public dataset, document the cleaning decisions, produce a few clear charts with interpretations, and end with a recommendation and its limitations. Publish the notebook and a short summary.\n\nProject 2: a dashboard. Build it in Power BI or Tableau on operational-style data (sales, tickets, deliveries), design it for a specific reader, and explain the insight a manager would act on.\n\nProject 3: SQL depth. Answer a set of business questions against a relational dataset using joins, window functions and CTEs, and present the queries with the reasoning.\n\nAcross all three: state the question first, show your cleaning steps, prefer simple charts done well, write in plain language, and include what you could not conclude. Host everything where a recruiter can open it in one click: a GitHub README with images, a Tableau Public profile, or a simple site.\n\nIf you have domain experience (retail, healthcare, finance), use data from that domain; it turns a student exercise into evidence of judgment.",
    ["kaggleLearn", "sqlbolt", "powerbi", "tableauTraining", "appIdeas"],
    ["data analyst", "portfolio", "projects", "dashboard", "sql", "analytics"],
  ],
  [
    "ml-portfolio-projects",
    "What machine learning projects should I put in my portfolio?",
    ["Which ML projects impress employers?", "How do I make my machine learning portfolio stand out?"],
    "portfolio",
    "portfolio",
    "Employers are tired of the same tutorial datasets. Choose projects that show the parts of machine learning that matter at work: framing, data quality, evaluation and deployment.\n\nProject ideas that demonstrate judgment: a prediction problem on data you collected or combined yourself (scraped listings, public transport delays, local weather and sales); a text classification task with an honest error analysis; a recommendation or ranking system with offline and simulated online metrics; or a model you deployed as an API with monitoring for input drift.\n\nFor each project include: the question and who would use the answer; a strong baseline before any complex model; the evaluation metric and why; a leakage check; results with confidence rather than a single number; a failure analysis; and how you would ship it. A short README with these sections is worth more than a large notebook.\n\nAvoid: unexplained high accuracy, no baseline, training on the test set, and ten models with no discussion.\n\nOne project with a deployed endpoint and a monitoring page shows more than any certificate. Keep the code reproducible: a requirements file, fixed seeds and a script that recreates the results.",
    ["kaggleLearn", "appliedMl", "sklearn", "hundredDaysMl", "awesomeDataScience"],
    ["machine learning", "portfolio", "projects", "evaluation", "deployment"],
  ],
  [
    "genai-portfolio-projects",
    "What generative AI projects should I build for my portfolio?",
    ["Which LLM projects impress employers?", "How do I show generative AI skills to recruiters?"],
    "portfolio",
    "portfolio",
    "Generative AI portfolios are judged on rigour, because anyone can wire a chatbot together in an afternoon. Build projects that show evaluation, safety and product thinking.\n\nStrong choices: a retrieval-augmented assistant over a real document set with citations, a test set and reported accuracy; a structured-extraction pipeline that turns messy documents into validated records with error rates; an agent that completes one bounded task with logs and guardrails; or a fine-tuned small model compared honestly against prompting a larger one on the same task.\n\nEvery project should include: the user and the task; the architecture in one diagram; the evaluation method and results; cost and latency per request; a security section (prompt injection, data privacy, what the system refuses); and a limitations section written candidly.\n\nDeploy at least one project so a reviewer can try it, with rate limits so it cannot run up your bill. The Generative AI for Beginners course and the provider cookbooks show reference implementations to learn from, but your write-up of trade-offs is what a hiring manager reads.\n\nAvoid demos with no evaluation, projects that only wrap an API call, and anything that claims accuracy without a test set.",
    ["genaiBeginners", "openaiCookbook", "dlaiShortCourses", "langchain", "claudeDocs"],
    ["generative ai", "portfolio", "llm", "rag", "projects", "evaluation"],
  ],
  [
    "data-analyst-to-data-scientist",
    "How do I move from data analyst to data scientist?",
    ["I am a data analyst; how do I become a data scientist?", "What should an analyst learn to transition into data science?"],
    "career-switching",
    "roadmap",
    "You already have the hardest part: the habit of asking clear questions of messy data and explaining results to people. The gap is usually statistics depth, modelling, and engineering hygiene.\n\nStatistics: move from descriptive work to inference and experiments. Hypothesis testing, confidence intervals, regression with interpretation, and A/B test design and pitfalls. An Introduction to Statistical Learning is the right level.\n\nModelling: learn the scikit-learn workflow properly (splitting, pipelines, cross-validation, tuning, metrics), then feature engineering and model interpretation. Do one classification and one regression project on data from your own work if you can share it.\n\nEngineering: write reusable Python modules instead of notebooks, use Git, add tests for data transformations, and learn to package a model behind a simple API.\n\nUse your position: volunteer for the analysis that needs a model, propose an experiment, and pair with any data scientist in the company. Internal transitions are the most common route because your domain knowledge is already trusted.\n\nUpdate your résumé to show modelling and experiment work by outcome, not tool list. You are ready when you can defend a model choice to a sceptical stakeholder and explain its failure modes in plain language.",
    ["statLearning", "sklearn", "kaggleLearn", "statistics", "python"],
    ["data analyst", "data scientist", "career switch", "statistics", "modelling"],
  ],
  [
    "developer-to-ai-engineer",
    "How can a backend developer move into AI engineering?",
    ["I am a software developer; how do I switch to AI engineering?", "What should a developer learn to work on LLM applications?"],
    "career-switching",
    "roadmap",
    "Backend developers are well placed for AI engineering because most of the job is systems work around a model. You do not need to become a researcher.\n\nKeep: your API design, database, testing, deployment and security skills. They are the differentiator between you and a data scientist moving the other way.\n\nAdd, in order: calling model APIs with structured outputs and streaming; embeddings and retrieval (chunking, vector search, hybrid search, reranking); tool calling and simple agent loops; evaluation harnesses that run a prompt across a test set; and observability for cost, latency and quality. Learn the basics of how transformers work so you can reason about context limits and failure modes, but prioritise building.\n\nDo it inside your current job if possible: propose a small assistant over internal documentation, a classification helper for tickets, or a search improvement. Measured results from a real system are the strongest evidence you can bring to an interview.\n\nPortfolio otherwise: one RAG application with an evaluation section and a security section, deployed.\n\nReady when you can explain how you would prevent prompt injection through user-uploaded documents, measure whether a prompt change helped, and control cost under load.",
    ["genaiBeginners", "openaiDocs", "claudeDocs", "langchain", "dlaiShortCourses"],
    ["backend developer", "ai engineer", "career switch", "llm", "rag"],
    ["xZDB1naRUlk"],
  ],
  [
    "data-engineering-tools",
    "Which tools should a beginner data engineer learn first?",
    ["What is the data engineering tool stack for beginners?", "Should I learn Spark or Airflow first?"],
    "data-science",
    "roadmap",
    "Learn data engineering tools in the order the data flows, and only after SQL and Python are solid, because every tool below assumes both.\n\nFirst, batch pipelines with plain Python: read from a source, transform, load into PostgreSQL, and schedule it. Understand idempotency, incremental loads and backfills before any orchestrator; they are the concepts interviewers test.\n\nSecond, orchestration with Apache Airflow (or a lighter alternative): DAGs, tasks, retries, scheduling and alerting. Run it locally with Docker.\n\nThird, a warehouse and modelling: understand columnar storage, partitioning and star schemas; use dbt or plain SQL models to build clean tables from raw ones, with tests.\n\nFourth, scale: Apache Spark for datasets that do not fit in memory, and the basics of streaming with Kafka if job descriptions in your area mention it.\n\nAlongside: Docker, Git, cloud storage and IAM basics on one provider, and data quality checks.\n\nPortfolio: a pipeline that ingests a public API daily, models it into analytics tables with tests, and exposes a dashboard, with documentation of failures handled. Ready when you can explain how you would recover from a failed run without duplicating data.",
    ["airflow", "spark", "sql", "docker", "python", "developerRoadmap"],
    ["data engineering", "airflow", "spark", "pipelines", "etl", "tools"],
    ["PHsC_t0j1dU"],
  ],
];
