import type { Row } from "./schema";

// Study-route questions. Admission rules, fees and recognition differ by country
// and change, so these answers describe how to decide and where to verify, never
// what a specific programme costs or requires.
export const educationRows: Row[] = [
  ["after-12th-technology", "What should I study after school if I want a technology career?", ["I finished school and want to work in tech. What should I choose?", "Which course should I take after higher secondary for IT?"], "education", "roadmap", "There is more than one legitimate route, and the degree title matters less than what you build while studying. Computing degrees, mathematics or statistics, and several engineering branches all lead into technology work, as do diploma and vocational routes in many countries.\n\nChoose using two filters. First, which subjects can you tolerate on a difficult day, since interest sustains effort far better than prestige. Second, which routes are actually recognised and available where you intend to work; entry requirements and recognition differ by country, so check an official education authority rather than relying on forum advice.\n\nWhatever you pick, start building in the first year rather than waiting for placement season. Learn one language, use version control, and finish small projects. Graduates who can show working code and explain it are in a different position from those who can only show a transcript, regardless of which programme they attended.", ["apprentice", "occupations"], ["after school", "degree choice", "higher secondary", "study route", "technology"]],

  ["after-btech-options", "What are my options after an engineering degree?", ["I just finished B.Tech. What should I do next?", "What should an engineering graduate do after graduating?"], "education", "roadmap", "You have four broad directions: enter the job market now, specialise through a postgraduate programme, build independent skills and evidence for a few months before applying, or move towards research. None is automatically better and the right one depends on what is currently missing.\n\nIf you can already demonstrate a relevant skill, applying now is usually stronger than adding a qualification, because early work experience compounds. If you cannot yet show anything you have built, a short focused period of building evidence often beats a long expensive programme.\n\nBe careful about choosing further study to postpone a decision; it is an expensive way to defer one. Before committing, speak to people currently doing the job that the programme is supposed to lead to, and read job postings for that role to see whether they ask for the qualification at all.", ["occupations", "apprentice"], ["engineering graduate", "after graduation", "postgraduate", "options", "decision"]],

  ["after-mca", "What should I do after an MCA?", ["I completed MCA. How do I get a good technical job?", "What should an MCA graduate focus on?"], "education", "roadmap", "An MCA gives you breadth. The most common gap at this point is depth in one area plus evidence that you can finish something, so treat the months after graduating as a specialisation period rather than a general application period.\n\nPick one direction — backend, data, cloud, testing, or mobile are all reasonable — and go deep enough to build two solid projects with tests, documentation, and a deployed or runnable result. Depth in one area interviews far better than a list of every technology covered in coursework.\n\nAt the same time, rewrite your resume around what you have built rather than what you studied. Academic projects count if you describe your specific contribution and the decisions you made. Apply steadily while you build rather than waiting until you feel finished, because interview feedback will tell you where the remaining gaps really are.", ["python", "git"], ["MCA", "postgraduate", "specialisation", "projects", "job search"]],

  ["after-bsc-science", "What career options do I have after a science degree?", ["I have a B.Sc and do not know what to do next", "What can a science graduate do besides research?"], "education", "roadmap", "A science degree trains you in exactly the skills several growing fields want: careful measurement, scepticism about results, and comfort with quantitative reasoning. The task is translating that into a job market vocabulary.\n\nData analysis is the most direct bridge, because you already understand variability and evidence. Quality and regulatory work, laboratory and technical roles, scientific writing, teaching, and technical support in scientific software all also value the degree directly. Financial and operational analysis take the same reasoning skills.\n\nAdd one practical toolset — spreadsheets to a high standard, then a query language — and rebuild one of your laboratory or project analyses as a documented piece of work someone else could follow. That single artefact converts a general science degree into a specific, checkable claim on your resume.", ["statistics", "sql", "occupations"], ["science degree", "B.Sc", "options", "analysis", "transition"]],

  ["after-bcom", "What should I do after a commerce degree?", ["I have a B.Com. What career paths are open to me?", "What can a commerce graduate do besides accounting?"], "education", "roadmap", "Commerce graduates have more directions available than the traditional accounting route, because financial literacy is useful in many functions. Accounting and audit, financial analysis, taxation, banking operations, business analysis, and revenue or sales operations all draw on the degree.\n\nProfessional qualifications exist in most countries for the accounting and audit routes; their structure, duration, and recognition vary, so check the relevant professional body's own pages rather than summaries. Do not commit to a multi-year qualification before confirming that the work it leads to appeals to you.\n\nIf you prefer analysis to compliance, add spreadsheet depth and a query language, then rebuild a financial analysis as a documented model with clear assumptions. Finance-plus-data is a well-established combination and lets you use the degree rather than working around it.", ["spreadsheet", "sql"], ["commerce", "B.Com", "finance", "accounting", "analysis"]],

  ["after-mba-direction", "How do I choose a direction after an MBA?", ["I finished an MBA and feel unfocused. What now?", "How do I use my MBA effectively?"], "education", "guidance", "An MBA broadens your options, which is exactly why it can feel directionless afterwards. Narrowing is the work now, and it is better done by elimination than by aspiration.\n\nSeparate the decision into three axes: function, such as product, operations, finance, marketing, or strategy; industry; and organisation size, since a small company and a large one demand very different behaviour. Fixing any two of the three makes the search tractable.\n\nUse the qualification's real advantage, which is access. Alumni will usually take a short conversation, and a specific question about their week produces far better information than a request for general advice. Ten of those conversations will narrow your direction faster than further reading, and they build the network that most post-programme roles actually come through.", ["product", "ilo"], ["MBA", "direction", "function", "networking", "decision"]],

  ["masters-abroad-or-work", "Should I take a postgraduate course abroad or start working?", ["Is studying overseas worth it or should I get a job first?", "How do I decide between overseas study and work experience?"], "education", "guidance", "Decide by what the qualification is meant to buy. Studying abroad is a reasonable investment when the field genuinely requires the deeper qualification, when the specialisation is unavailable locally, or when you have a specific long-term reason to be in that country.\n\nIt is a poor investment when it is chosen mainly to escape a difficult job search, because the same search will be waiting afterwards with more financial pressure behind it. Work experience often improves your position more cheaply, and some employers support study later.\n\nWhatever you decide, verify the practical details with official sources: immigration rules, work rights during and after study, recognition of the qualification, and total cost including living expenses. These change and vary by country, and no forum or agent should be your only source. Speak to recent graduates of the specific programme about what actually happened next for them.", ["ilo"], ["overseas study", "postgraduate", "work experience", "decision", "planning"]],

  ["online-degree-value", "Is an online degree taken seriously?", ["Will employers accept a degree completed online?", "Is a distance qualification worth doing?"], "education", "guidance", "It depends far more on the awarding institution's recognition than on the delivery format. A qualification from a properly accredited institution is generally treated as the qualification it says it is; one from an unaccredited provider may be worth very little regardless of the effort involved.\n\nCheck accreditation with the relevant national authority yourself rather than trusting the provider's marketing. Also check whether your intended field or employer type has specific requirements, since regulated professions often do.\n\nOnline study demands more self-management, so build external structure: fixed study times, a study group, and deadlines you report to someone. And as with any qualification, pair it with visible evidence of applied skill. A recognised online degree plus a portfolio of finished work is a strong combination; a qualification of any kind with nothing to show is a weaker one.", ["apprentice"], ["online degree", "accreditation", "distance learning", "recognition", "self study"]],

  ["bootcamp-decision", "Are intensive coding courses worth the cost?", ["Should I join a bootcamp to change careers?", "How do I evaluate an intensive training programme?"], "education", "guidance", "An intensive programme mainly buys structure, pace, and a cohort. If you have repeatedly failed to make progress alone and can afford the cost without financial strain, that structure can be worth paying for. If you are already learning steadily by yourself, the marginal benefit is smaller.\n\nEvaluate providers sceptically. Ask exactly how outcome figures are calculated, what counts as a relevant placement, what proportion of starters are included, and what happens to those who do not finish. Ask to speak to graduates the provider did not select for you, and treat any guaranteed-outcome language as a reason for more caution rather than less.\n\nBe realistic about what happens afterwards. Graduating from any programme is the beginning of a job search, not the end of one. Whatever you choose, the evidence you build during it — finished projects you can explain — is what you will actually be interviewed on.", ["apprentice"], ["bootcamp", "training", "career change", "evaluation", "outcomes"]],

  ["no-degree-path", "Can I get a technical job without a degree?", ["Is it possible to work in technology without a formal qualification?", "How do I compete without a degree?"], "education", "guidance", "It is possible in many technical fields, and it is harder in specific ways that are worth naming honestly rather than glossing over. Some employers filter on qualifications, some roles are regulated, and some countries' work-permit routes reference formal education. Those constraints are real and you should check them for your own situation.\n\nWhere it works, it works through evidence. A body of finished, explainable work, visible contributions to shared projects, and a clear account of what you can do replaces the credential as a signal. Small organisations and referral-based hiring are generally more open to this than large structured graduate processes.\n\nBuild the network deliberately, because it substitutes for the filter you do not pass. Contribute publicly, help people in communities related to your field, and let people see how you work. Many people in this position also add a recognised qualification later, once employment makes it affordable and optional rather than urgent.", ["jobs", "apprentice"], ["no degree", "self taught", "evidence", "hiring filters", "portfolio"]],

  ["diploma-progression", "How do I progress from a diploma into better roles?", ["I have a diploma rather than a degree. How do I advance?", "What should a diploma holder focus on to grow?"], "education", "roadmap", "A diploma often gets you into practical work sooner, which is a genuine advantage as long as you keep growing after entry. The risk is plateauing in a role that stops teaching you anything new.\n\nTreat your first years as paid learning. Volunteer for the unfamiliar task, document what you build, and keep a record of problems you solved with enough detail to describe them later. Practical experience is persuasive, but only if you can articulate it.\n\nIn parallel, check whether progression in your field commonly references a further qualification, and whether your employer supports part-time study. Many people move up through a combination of demonstrated work and a later qualification taken while employed, which is far less financially risky than pausing a career to study full time.", ["apprentice"], ["diploma", "progression", "practical experience", "further study", "growth"]],

  ["college-project-value", "How do I make my college project count for job applications?", ["Are academic projects useful on a resume?", "How should I present my final year project?"], "education", "portfolio", "Academic projects count when they are described as engineering work rather than as coursework. Reviewers are trying to learn what you can do, and a project title alone tells them nothing.\n\nDescribe your specific contribution rather than the team's collective output, since a shared credit for something you did not build is both misleading and easy to expose in an interview. Name the problem, your role, the decisions you made, and what you would change. If it was guided closely by a supervisor, say so honestly and focus on the parts you drove.\n\nThen make it inspectable. Put the code somewhere readable, write a short readme explaining how to run it, and clean up the obvious rough edges. A modest project you can discuss in depth is more valuable than an ambitious one you cannot explain, and preparing that explanation is itself good interview practice.", ["git"], ["college project", "final year", "academic", "resume", "presentation"]],

  ["study-while-working", "How do I study for a qualification while working full time?", ["Can I do a course alongside a job?", "How do I manage part-time study and work?"], "education", "roadmap", "Assume less available time than you expect, because study competes with rest rather than with idleness. Plans that require energy you will not have after a full day are the ones that collapse.\n\nProtect two or three fixed slots a week and treat them as appointments rather than intentions. Front-load the difficult material into whichever slot you are freshest for, and use tired time for review and practice rather than new concepts. Tell people close to you what you are doing so the time is defended.\n\nCheck whether your employer offers study support, adjusted hours, or examination leave; many do and few advertise it. Plan for a bad month rather than hoping for none, and prefer a longer timetable you complete over an aggressive one you abandon. Consistency over a year outperforms intensity over a fortnight.", ["writing"], ["part time study", "working", "time management", "qualification", "balance"]],
];
