import type { Row } from "./schema";

// Interview formats and frequently asked questions. Answers describe how to
// prepare and reason; they never promise an outcome or supply a script to recite.
export const interviewRows: Row[] = [
  ["hr-round-preparation", "How do I prepare for an HR interview round?", ["What does the HR round assess?", "How should I handle a screening call with a recruiter?"], "interviews", "interview", "The early conversation is usually a filter for fit, motivation, availability, and basic alignment on the role. It is short, so being clear matters more than being thorough.\n\nBe ready to summarise your background in about a minute, to say why this role and this organisation specifically, and to describe what you are looking for next. Know your own resume dates and titles precisely, because inconsistencies here get flagged. Have neutral, prepared answers for notice period, location or travel expectations, and any gaps.\n\nAsk your own questions too: the team's shape, what the process looks like from here, and what success in the role would mean. Treat the recruiter as an ally rather than an obstacle; they usually want to present a strong candidate and will often tell you what the hiring manager cares about if you ask.", ["writing"], ["HR round", "screening call", "recruiter", "fit", "motivation"]],

  ["why-this-company", "How do I answer why I want to work here?", ["What should I say when asked why this organisation?", "How do I show genuine interest in a company?"], "interviews", "interview", "Generic praise is the weakest possible answer, because it could be said to anyone. The interviewer is checking whether you have thought specifically about this role and would still want it after understanding it properly.\n\nBuild the answer from three parts: something specific about what they do or how they work that you can name accurately, something about this role that fits where you are heading, and something you bring that is relevant to their situation. One sentence each is enough.\n\nFind the specifics from their own material: product documentation, engineering or company blog, recent public announcements, and the job description's wording. If you genuinely cannot find a specific reason, that is worth noticing before the interview rather than during it. Honest interest in the problem the team is solving is more convincing than admiration of the organisation's reputation.", ["writing"], ["why this company", "motivation", "research", "interview answer", "fit"]],

  ["why-should-we-hire-you", "How do I answer why they should hire me?", ["What is a good response to why you are the right candidate?", "How do I make my case at the end of an interview?"], "interviews", "interview", "Treat it as a summary rather than a plea. The interviewer is offering you a chance to connect your evidence to their problem, so use it deliberately instead of restating your resume.\n\nName the two or three things this role most clearly needs, based on the description and on what has come up during the conversation. For each, give one short piece of concrete evidence from your own experience. Close by saying what you would want to focus on first if you joined, which shows you have been thinking about the work rather than the offer.\n\nAvoid superlatives you cannot support and avoid claiming to be the best candidate, since you have no information about the others. Confident specificity is more persuasive than confident generality, and it is much easier to deliver honestly.", ["writing"], ["why hire you", "closing", "evidence", "interview answer", "summary"]],

  ["five-year-question", "How do I answer where I see myself in a few years?", ["What should I say about my long-term plans in an interview?", "How do I answer questions about my future goals?"], "interviews", "interview", "The question is usually checking two things: whether your direction is compatible with the role, and whether you think beyond the immediate. It is not asking for a precise prediction, and pretending to certainty you do not have sounds rehearsed.\n\nAnswer in terms of capability rather than titles. Describe the kind of problems you want to be trusted with, the depth you want to reach, and the sort of responsibility that appeals to you. Then connect it to this role by naming what you would learn here that leads in that direction.\n\nBe honest but sensible. If you are genuinely undecided between two directions, saying so while explaining how you plan to decide reads as self-aware. If your real plan is unrelated to the role, that is worth reflecting on privately, because the mismatch will surface either in the interview or a few months into the job.", ["writing"], ["long term goals", "five years", "ambition", "interview answer", "direction"]],

  ["why-leaving-current-job", "How do I answer the interview question about why I am leaving my job?", ["What should I say about wanting to leave my employer?", "How do I explain looking for a new role without criticising my employer?", "How do I answer why I am leaving my current job?"], "interviews", "interview", "Keep it brief, forward-looking, and free of complaint. Interviewers listen for whether you speak about colleagues fairly, because they are imagining how you would describe them later.\n\nFrame it as movement towards something: a kind of work you want more of, a scale or domain you want to learn, a level of responsibility your current role cannot offer. If the real reason is negative — poor management, no growth, a difficult environment — translate it into what you are seeking instead, which is honest without being disparaging.\n\nOne or two sentences is the right length. If pressed for detail, stay factual and unemotional; describing a genuine problem without editorialising is fine and often respected. Then return the conversation to the role you are interviewing for.", ["writing"], ["why leaving", "reason", "professionalism", "interview answer", "framing"]],

  ["take-home-assignment", "How should I approach a take-home assignment?", ["What do employers look for in a take-home task?", "How much effort should I put into a technical assignment?"], "interviews", "interview", "Read the brief twice and note explicitly what is being assessed. Most take-home tasks reward clarity, correctness on the stated requirements, and judgement about scope far more than extra features.\n\nRespect the suggested time. Going far beyond it disadvantages other candidates and often signals poor prioritisation rather than enthusiasm. If you run out of time, deliver something working and write down what you would do next and why — that note is frequently the most valuable part of the submission.\n\nInclude a short readme covering how to run it, the decisions you made, the tradeoffs you accepted, and anything you deliberately left out. Add tests for the important path. If the brief is ambiguous, ask one clarifying question rather than guessing silently; asking is usually part of what is being observed.", ["testing", "git"], ["take home", "assignment", "scope", "readme", "tradeoffs"]],

  ["pair-programming-interview", "How do I handle a live coding or pair programming interview?", ["What should I do during a collaborative coding session?", "How is pair programming assessed in interviews?"], "interviews", "interview", "The assessment is mostly about how you work with another person on an unfamiliar problem, not whether you produce optimal code silently.\n\nStart by restating the problem and confirming your understanding, then agree an approach before writing anything. Think aloud so the interviewer can follow your reasoning and help when you drift; treating them as a colleague rather than an examiner is usually the intent. Write something simple that works before optimising, and say that is what you are doing.\n\nWhen stuck, say what you are considering and what you would check next rather than going quiet. Accept hints gracefully — ignoring them looks worse than needing them. If you notice a bug in your own code, name it and fix it; catching your own mistakes is a positive signal, not an admission of weakness.", ["git"], ["pair programming", "live coding", "collaboration", "thinking aloud", "interview"]],

  ["aptitude-test-preparation", "How do I prepare for an aptitude or assessment test?", ["What should I practise for a written assessment round?", "How do I get ready for a numerical and logical reasoning test?"], "interviews", "roadmap", "These tests are usually about speed under time pressure on a narrow set of question types, so familiarity matters more than raw intelligence. Practising the format is the most effective preparation.\n\nFind out what the assessment covers before preparing; quantitative reasoning, logical patterns, verbal comprehension, and situational judgement are common but the mix varies. Practise with a timer from the start, because pacing is what most people lose marks on, not difficulty. Learn which question types you are slow at and either drill them or plan to skip them.\n\nOn the day, read whether marks are deducted for wrong answers, since that changes whether guessing is sensible. Answer the questions you can do quickly first. If the test is unfamiliar or accessibility adjustments would help you, ask the employer in advance; reasonable organisations accommodate this.", [], ["aptitude test", "assessment", "practice", "timing", "reasoning"]],

  ["group-discussion-round", "How do I do well in a group discussion round?", ["What is assessed in a group discussion?", "How should I behave in a group assessment exercise?"], "interviews", "interview", "Assessors are watching how you behave in a group, not who talks most. Dominating the discussion usually scores worse than contributing thoughtfully and helping the group make progress.\n\nEnter early with something substantive so you are established, then focus on quality over frequency. Build on others' points by name, bring in someone who has not spoken, and summarise where the group has reached when it starts circling. Disagree with the idea rather than the person, and offer a reason.\n\nKeep track of the time and the objective, since groups often run out of time without reaching a conclusion. Offering a structure at the start, or a summary near the end, is a strong and low-risk contribution. Preparing a little on current general topics helps, but composure and listening matter more than knowledge.", ["writing"], ["group discussion", "assessment centre", "teamwork", "communication", "structure"]],

  ["case-interview-preparation", "How do I prepare for a case study interview?", ["What is expected in a business case interview?", "How do I structure an answer to a case question?"], "interviews", "interview", "A case interview assesses structured thinking out loud. The interviewer wants to see how you break an ambiguous problem into parts, not whether you reach a predetermined answer.\n\nUse a consistent approach: clarify the objective and any constraints, state your structure before analysing, work through the branches, and check your reasoning against common sense as you go. Say your assumptions explicitly and be willing to revise them when given new information. Where numbers are involved, narrate the arithmetic so an error can be corrected rather than compounding silently.\n\nPractise aloud with another person, because doing cases in your head hides exactly the communication weaknesses being tested. Finish with a short recommendation and the main risk to it. A clear structure and an honest caveat beat a confident answer with hidden assumptions.", ["product"], ["case interview", "structure", "consulting", "problem solving", "assumptions"]],

  ["portfolio-review-interview", "How do I present my portfolio in an interview?", ["How should I walk through my design or project work?", "What do interviewers want from a portfolio presentation?"], "interviews", "interview", "Present a small number of pieces in depth rather than everything you have made. Two or three well-explained projects use the time far better than a gallery.\n\nStructure each one the same way: the problem and who had it, the constraints you worked under, what you did and why, what happened, and what you would change. Be explicit about your own contribution when the work was collaborative, and about anything that was guided or was a personal concept rather than a real engagement.\n\nRehearse against a clock, because most people badly overrun on their favourite project and rush the rest. Prepare for the obvious challenges: why this approach and not the alternative, what you would do with more time, and what you got wrong. Willingness to discuss a weakness in your own work reads as maturity rather than as a flaw.", ["git"], ["portfolio review", "presentation", "projects", "walkthrough", "interview"]],

  ["virtual-interview-setup", "How do I prepare for an online interview?", ["What should I check before a video interview?", "How do I come across well on a remote interview call?"], "interviews", "interview", "Remove the avoidable failures first, because technical problems consume time and composure. Test the platform, camera, microphone, and connection in advance, ideally at the same time of day. Have a backup, such as a phone number to dial in or a mobile connection, and the interviewer's contact details to hand.\n\nSet up so you are easy to follow: light on your face rather than behind you, camera near eye level, a plain background, and notifications silenced. Close anything that might pop up if you share your screen. Keep brief notes just off camera if that helps you, and have a copy of your resume and the job description open.\n\nOn the call, allow a beat before answering to avoid talking over the delay, and look at the camera occasionally rather than only at the faces. If the connection degrades, say so plainly and suggest turning video off; interviewers deal with this constantly and handling it calmly is itself a good signal.", [], ["video interview", "remote", "setup", "technology", "preparation"]],

  ["panel-interview", "How do I handle a panel interview?", ["What should I do when several people interview me at once?", "How do I manage a multi-person interview?"], "interviews", "interview", "A panel is mostly a logistics decision by the employer, but it changes the dynamics. Different people are usually assessing different things, so track who is asking what.\n\nWrite down names as you are introduced and use them. Direct your answer primarily to whoever asked, but include the others with your attention rather than fixing on one person. If a question comes from a specialist, it is reasonable to pitch the detail at their level while adding a sentence that keeps the others with you.\n\nKeep answers a little tighter than in a one-to-one interview, because time is shared. Prepare a question for different roles on the panel, such as one about the technical work and one about the team, and if you do not know who to address a question to, simply say it is for whoever is best placed to answer.", ["writing"], ["panel interview", "multiple interviewers", "attention", "questions", "structure"]],

  ["final-round-preparation", "How do I prepare for a final interview round?", ["What is different about the last stage of a hiring process?", "How do I prepare to meet a senior leader in an interview?"], "interviews", "interview", "Later rounds usually shift from whether you can do the work to whether you fit the team and think beyond your own task. The questions get broader and the assessment is more about judgement than technique.\n\nRe-read everything you have been told across earlier rounds and prepare to go deeper on anything you covered briefly. Be ready to talk about how you make decisions, handle disagreement, prioritise under pressure, and what you would want to understand in your first weeks. If you gave a weak answer earlier, prepare a better one in case it returns.\n\nBring stronger questions than you asked earlier: how the team's priorities are set, what has been hardest recently, how success is measured. Ask about next steps and timelines before you finish. Treat this as a mutual decision point, because by this stage you have enough information to be evaluating them too.", ["writing"], ["final round", "senior interview", "judgement", "questions", "preparation"]],

  ["interview-nerves", "How do I manage interview nerves?", ["I panic in interviews. What can I do?", "How do I stay calm during a job interview?"], "interviews", "interview", "Nerves are largely a preparation and exposure problem rather than a personality flaw. The two things that reduce them most are rehearsing out loud and having done it recently.\n\nPractise answering aloud, ideally to another person, rather than mentally. Prepare the shape of your answers to frequent questions instead of memorising scripts, since forgetting a script is what usually triggers panic. Know your resume well enough that no question about it can surprise you.\n\nIn the room, slow down deliberately. It is entirely acceptable to say you would like a moment to think, to ask for a question to be repeated, or to have water nearby. If you lose your thread, say so and restart the point; interviewers do this themselves. Interviewing early for roles you care less about builds tolerance, so schedule the ones that matter most a little later.", ["wellbeing"], ["nerves", "anxiety", "preparation", "practice", "composure"]],

  ["interview-questions-to-ask-team", "What should I ask to find out what a team is really like?", ["How do I assess a workplace during interviews?", "What questions reveal whether a job is a good fit?"], "interviews", "interview", "Ask about specifics that are hard to answer with a slogan. General questions about culture invite general answers; concrete ones reveal how the team actually operates.\n\nUseful examples: what a normal week looks like, how work is prioritised and by whom, what happened the last time a deadline was at risk, how code or work is reviewed, how decisions get made when people disagree, and why this role is open. Asking what someone finds frustrating often produces the most honest answer of the conversation.\n\nPay attention to how the questions are received as well as to the content of the answers. Hesitation, deflection, or contradiction between interviewers is information. If you can, ask to speak briefly with a potential peer; reasonable employers accommodate this and the conversation is usually the most candid one you will have.", ["writing"], ["questions to ask", "team fit", "culture", "due diligence", "interview"]],

  ["salary-question-avoid-guess", "What should I do if I am asked to justify a figure I gave?", ["How do I explain the range I asked for?", "What if the employer says my expectation is too high?"], "interviews", "current-facts", "Explain the basis rather than defending the number emotionally. A range built on the role's responsibilities, the level, the location, and comparable postings is defensible; a number chosen because it sounded right is not.\n\nIf they say it is above their band, ask what the band is and what determines placement within it. That turns a confrontation into information gathering. You can then decide whether the rest of the package, the work, or the trajectory changes your view, and whether anything else is adjustable.\n\nWhat local rules permit an employer to ask, and what you are required to disclose, differ by country and sometimes by region, so check an authoritative local source. I will not estimate a market figure for you, because a meaningful answer depends on the role, place, and date. Never invent a competing offer to strengthen your position.", ["ilo"], ["salary", "range", "justification", "negotiation", "bands"]],

  ["interview-feedback-request", "How do I ask for feedback after being rejected?", ["Can I ask why I was not selected?", "How do I get useful feedback from an interviewer?"], "interviews", "interview", "Ask once, briefly, and make it easy to answer. A short message thanking them and asking for one specific thing you could improve gets replies far more often than a general request for feedback.\n\nAsk about something concrete: whether the gap was a particular skill, the depth of an answer, or experience level. Some organisations have a policy against giving detailed feedback, so a non-answer is not a snub. Accept whatever you get without arguing; debating a rejection guarantees you learn nothing and closes the door for future roles.\n\nWhere no feedback is available, do your own review while it is fresh: which questions you handled poorly, where you ran out of evidence, and what you would prepare differently. Patterns across several interviews are more reliable than any single opinion anyway.", ["writing"], ["feedback", "rejection", "improvement", "follow up", "learning"]],

  ["reference-preparation", "How do I prepare my references?", ["Who should I ask to be a reference?", "How do professional references work?"], "interviews", "guidance", "Choose people who supervised or worked closely with you and can speak to the specific work, not the most senior person who barely knows you. A direct manager or a project lead is usually the strongest choice.\n\nAsk permission before listing anyone, and ask in a way that lets them decline gracefully, because a lukewarm reference is worse than none. Once they agree, send them the role description, a reminder of what you worked on together, and the two or three things you would like them to be able to speak to. That is helping them prepare, not scripting them.\n\nKeep the list current and tell referees when to expect contact. If your most recent employment ended difficultly, use referees from earlier roles or from adjacent colleagues, and be ready to explain the choice calmly if asked.", ["writing"], ["references", "referees", "preparation", "permission", "hiring process"]],
];
