import type { Row } from "./schema";

/**
 * DevOps, cloud, cybersecurity and QA paths. Certification advice always
 * points at the provider for current scope and fees and never claims a
 * credential is required.
 */
export const opsSecurityQaRows: Row[] = [
  [
    "aws-cloud-engineer-roadmap",
    "How do I become an AWS cloud engineer?",
    ["AWS cloud engineer roadmap", "What should I learn to work with AWS professionally?", "How do I start a cloud engineering career on AWS?"],
    "cloud",
    "roadmap",
    "Cloud engineering on AWS is mostly networking, identity, automation and cost awareness applied to a large catalogue of services. Learn the fundamentals, then a small set of core services deeply, then automation.\n\nFoundations: Linux administration, TCP/IP and DNS, how HTTP and TLS work, and scripting in Bash and Python. Without these, cloud consoles are just buttons.\n\nCore services: IAM (users, roles, policies, least privilege), VPC networking (subnets, route tables, security groups), EC2, S3, RDS, and load balancing. Build a small three-tier application by hand once so you understand every piece, then tear it down.\n\nAutomation: infrastructure as code with Terraform or CloudFormation, containers with Docker, and a CI/CD pipeline that deploys on push. Learn CloudWatch for logs and alarms, and how to read a bill.\n\nCertification: the AWS Cloud Practitioner and Solutions Architect Associate exams map well to this learning path and are widely recognised, but check the current exam guide, version and fee on the AWS certification page before booking. A certificate supports a portfolio; it does not replace one.\n\nPortfolio: a deployed application with Terraform code, a diagram, a cost estimate and a runbook for one failure scenario. Ready when you can explain how traffic reaches your app from the internet, how you would rotate a credential, and what you would do if the monthly bill doubled.",
    ["awsTraining", "awsSkillBuilder", "aws", "terraform", "docker", "githubActions", "linux"],
    ["aws", "cloud engineer", "iam", "vpc", "terraform", "certification", "roadmap"],
    ["SOTamWNgDKc", "SLB_c_ayRMo"],
  ],
  [
    "kubernetes-learning",
    "How do I learn Kubernetes?",
    ["Where do I start with Kubernetes?", "How much Kubernetes do I need for DevOps jobs?", "Kubernetes study plan for beginners"],
    "devops",
    "roadmap",
    "Learn Kubernetes only after Docker makes sense, because Kubernetes is a system for running many containers reliably and its concepts assume you know what a container is.\n\nStep 1: run a local cluster (kind, minikube or Docker Desktop) and deploy one containerised app. Learn Pods, Deployments, Services and how to read kubectl output and logs. The official tutorials' interactive basics module covers exactly this.\n\nStep 2: configuration and state. ConfigMaps, Secrets, environment variables, persistent volumes, and how to update an app without downtime. Break things on purpose (kill a pod, scale to zero, set a wrong image) and watch the cluster respond.\n\nStep 3: networking and exposure. Ingress, DNS inside the cluster, and TLS. Then resource requests and limits, liveness and readiness probes, and namespaces.\n\nStep 4: real workflows. Package with Helm, deploy from a CI pipeline, add monitoring with Prometheus and Grafana, and try one managed cluster on a cloud provider.\n\nPortfolio: a two-service application deployed with manifests or Helm, a CI pipeline, monitoring dashboards and a document explaining how you would roll back a bad release.\n\nYou know enough for junior DevOps roles when you can explain what happens when a pod crashes, debug a service that is not reachable, and describe how requests and limits affect scheduling.",
    ["kubernetesTutorials", "kubernetes", "docker", "githubActions", "devopsExercises"],
    ["kubernetes", "k8s", "containers", "devops", "helm", "deployment"],
    ["X48VuDVv0do", "d6WC5n9G_sM"],
  ],
  [
    "devops-interview-prep",
    "How do I prepare for a DevOps engineer interview?",
    ["What is asked in DevOps interviews?", "DevOps interview preparation plan", "How do I practise for SRE interview rounds?"],
    "devops",
    "interview",
    "DevOps interviews test whether you can run systems, not whether you know tool names. Expect Linux and networking questions, scripting, CI/CD design, containers and orchestration, cloud, and incident scenarios.\n\nLinux and networking: process management, permissions, disk and memory troubleshooting, reading logs, DNS resolution, TCP handshakes, how TLS works, what a load balancer does. Practise on a real machine.\n\nScripting: write a Bash or Python script live to parse logs or automate a task. Keep it simple and explain edge cases.\n\nCI/CD: design a pipeline for a sample app: build, test, security scan, artifact, deploy, rollback. Discuss branching strategies and environment promotion.\n\nContainers and Kubernetes: Dockerfile best practices, image size, what happens when a pod fails, how you would debug a service that is unreachable.\n\nCloud and IaC: IAM least privilege, networking layout, Terraform state and modules, cost.\n\nScenarios: 'The site is slow', 'Deploy failed at 2 a.m.', 'A secret leaked'. Answer with a method: observe, form a hypothesis, test, mitigate, then fix root cause and write a post-mortem.\n\nThe DevOps Exercises repository has thousands of practice questions; Google's SRE books explain the reasoning behind good answers. Prepare two real stories about an outage or a pipeline you improved.",
    ["devopsExercises", "sreBooks", "kubernetes", "terraform", "linux"],
    ["devops", "interview", "sre", "ci/cd", "kubernetes", "linux"],
    ["j5Zsa_eOXeY"],
  ],
  [
    "devops-portfolio",
    "How do I build a DevOps portfolio without a job?",
    ["What DevOps projects can I show employers?", "How do I get DevOps experience on my own?"],
    "portfolio",
    "portfolio",
    "DevOps evidence is about repeatability and operations, which you can demonstrate on your own infrastructure.\n\nProject 1: take any small application (yours or an open-source one) and build its full delivery path: Dockerfile with a small image, CI pipeline that lints, tests and builds, a container registry, and deployment to a cloud VM or managed Kubernetes with infrastructure defined in Terraform.\n\nProject 2: observability. Add structured logging, metrics with Prometheus, a Grafana dashboard, and an alert that fires when the app is unhealthy. Document what each alert means and what to do about it.\n\nProject 3: reliability. Write a runbook, practise a rollback, set up automated backups and test a restore, and record a short incident post-mortem from something you broke deliberately.\n\nPublish the repositories with architecture diagrams and a README that reads like an operations guide. Include a cost section; running this cheaply is itself a skill.\n\nContributing infrastructure improvements to an open-source project (a CI fix, a Dockerfile, a Helm chart) is another credible route, and it gives you code review experience.\n\nRecruiters cannot run your cluster, so screenshots of dashboards, pipeline runs and a live URL matter.",
    ["docker", "githubActions", "terraform", "kubernetesTutorials", "devopsRoadmapRepo"],
    ["devops", "portfolio", "projects", "ci/cd", "terraform", "monitoring"],
  ],
  [
    "soc-analyst-roadmap",
    "How do I become a SOC analyst?",
    ["Security operations analyst roadmap", "What should I learn for a security analyst job?", "How do I get an entry-level cybersecurity analyst role?"],
    "cybersecurity",
    "roadmap",
    "A security operations centre analyst watches alerts, investigates suspicious activity and escalates real incidents. It is the most common entry point into cybersecurity, and it rewards system fundamentals more than hacking skill.\n\nPhase 1: how systems work. Networking (TCP/IP, DNS, HTTP, common ports), Windows and Linux administration, Active Directory basics, and how logs are produced. If you cannot read a firewall log or a Windows event, start here.\n\nPhase 2: security concepts. The attack lifecycle, common attack techniques (phishing, credential theft, malware behaviour, lateral movement), and defensive controls. The MITRE ATT&CK framework gives you the vocabulary analysts use daily.\n\nPhase 3: tools and practice. SIEM basics (searching, correlation, alert tuning), packet analysis with Wireshark, endpoint detection concepts, and threat intelligence sources. TryHackMe's SOC paths and Hack The Box labs give hands-on practice in a legal environment.\n\nPhase 4: evidence. Build a home lab with a SIEM ingesting logs from a couple of machines, generate benign attacks against your own lab, and write investigation reports.\n\nCertifications such as CompTIA Security+ and ISC2's entry credential map to this level; confirm current exam content and cost with the provider. Google's cybersecurity certificate is another structured beginner path.\n\nReady when you can explain how you would triage a phishing alert from first look to escalation, and read a log line and say what happened.",
    ["security", "tryhackme", "hackthebox", "comptiaSecurity", "isc2", "growGoogle", "owaspTop10"],
    ["soc analyst", "cybersecurity", "security analyst", "siem", "incident response", "roadmap"],
    ["9HOpanT0GRs", "_DVVNOGYtmU"],
  ],
  [
    "ethical-hacker-roadmap",
    "How do I become an ethical hacker?",
    ["Penetration tester roadmap", "What should I learn to become a penetration tester?", "How do I start in offensive security legally?"],
    "cybersecurity",
    "roadmap",
    "Ethical hacking means testing systems you are authorised to test and reporting what you find so it can be fixed. The legal boundary is part of the job: practise only on labs and platforms built for it, or on systems with written permission.\n\nFoundations: networking, Linux, at least one scripting language (Python), and how web applications work end to end. Most junior penetration testing is web testing, so the OWASP Top Ten and the free PortSwigger Web Security Academy labs are the core curriculum.\n\nSkills: reconnaissance, vulnerability discovery, exploitation basics, privilege escalation, and above all clear reporting with reproduction steps and risk ratings. A finding nobody can reproduce has no value.\n\nPractice: Hack The Box and TryHackMe machines, capture-the-flag events, and bug bounty programmes with explicit rules. Keep write-ups of what you learned from each box.\n\nCertifications in this field are practical exams; check the provider pages for current formats and costs, and treat them as a way to structure study rather than a ticket to a job.\n\nPortfolio: sanitised write-ups of lab machines, a small tool you wrote, and a sample penetration test report on a deliberately vulnerable app.\n\nReady when you can find and explain an injection vulnerability, escalate privileges on a lab machine methodically, and write a report a developer can act on.",
    ["portswigger", "owaspTop10", "owaspCheatSheets", "hackthebox", "tryhackme", "awesomeSecurity"],
    ["ethical hacking", "penetration testing", "offensive security", "owasp", "ctf", "roadmap"],
    ["ug8W0sFiVJo", "3Kq1MIfTWCE"],
  ],
  [
    "cybersecurity-interview-prep",
    "How do I prepare for a cybersecurity interview?",
    ["What questions come up in security analyst interviews?", "Cybersecurity interview preparation for freshers"],
    "cybersecurity",
    "interview",
    "Entry-level security interviews test fundamentals, reasoning and communication. Expect questions on networking (what happens when you type a URL, how TLS works, what a port scan looks like), operating systems (permissions, processes, logs), common attacks and their defences (phishing, injection, credential stuffing, ransomware), security principles (least privilege, defence in depth, CIA triad), and scenario walk-throughs.\n\nScenarios: 'You see an alert for unusual login at 3 a.m.' Answer with a process: verify the alert, gather context, contain if needed, escalate, document. Interviewers want structure and calm, not heroics.\n\nPractical: some interviews include a log excerpt, a packet capture or a vulnerable snippet of code. Practise reading each of those regularly.\n\nKeep current: be able to discuss one recent public incident and what the lessons were, without speculation.\n\nCommunication: explain a technical risk to a non-technical manager in two sentences. This is tested more than candidates expect.\n\nUse the OWASP Cheat Sheets for application security topics and TryHackMe rooms to rehearse hands-on tasks. Prepare stories about a lab investigation and about a time you had to admit you did not know something and found out.",
    ["owaspCheatSheets", "tryhackme", "security", "comptiaSecurity"],
    ["cybersecurity", "interview", "security analyst", "scenarios"],
    ["9HOpanT0GRs"],
  ],
  [
    "playwright-learning",
    "How do I learn Playwright for test automation?",
    ["Where do I start with Playwright?", "Is Playwright a good choice for automation testers?", "Playwright study plan for QA"],
    "qa-testing",
    "roadmap",
    "Playwright is a modern end-to-end testing framework that job descriptions increasingly name alongside Selenium and Cypress. Learn it as a testing discipline, not just a tool.\n\nPrerequisites: JavaScript or TypeScript basics (functions, async/await, objects) and an understanding of HTML structure and CSS selectors. Playwright also supports Python, Java and .NET if your team uses them.\n\nStart with the official Getting Started guide: install, write a first test, run it in three browsers, and read the trace viewer output. Learn locators properly (role-based and text-based locators before CSS), auto-waiting, assertions, fixtures and the page object pattern.\n\nThen the parts real suites need: authentication state reuse, test data setup and teardown, API testing alongside UI tests, parallel execution, retries and flakiness diagnosis, screenshots and videos on failure, and running in CI with GitHub Actions.\n\nPractice on a public demo application or your own project. Write a small suite that covers a login, a form with validation, and a data-driven scenario, and make it run green in CI.\n\nPortfolio: the suite in a public repository with a README explaining structure, how to run it and how you handled flaky tests.\n\nReady when you can explain why a test is flaky and fix it, choose a locator that survives a redesign, and describe what belongs in an end-to-end test versus a unit test.",
    ["testing", "testAutomationU", "githubActions", "typescript"],
    ["playwright", "test automation", "qa", "end-to-end", "typescript"],
    ["jydYq7oAtD8", "788GvvcfwTY"],
  ],
  [
    "qa-interview-prep",
    "How do I prepare for a QA or software testing interview?",
    ["What is asked in manual testing interviews?", "How do I prepare for an automation tester interview?", "QA engineer interview questions preparation"],
    "qa-testing",
    "interview",
    "Testing interviews check how you think about risk, how you communicate defects, and whether you can automate where it pays.\n\nConcepts: test levels (unit, integration, system, acceptance), types (functional, regression, smoke, performance, security), black-box techniques (equivalence partitioning, boundary values, decision tables), the test process, and what a good bug report contains. The free ISTQB Foundation syllabus is a compact checklist of this vocabulary.\n\nPractical exercises: 'Test this login form' or 'Test a lift'. Answer by listing categories of tests (positive, negative, boundary, security, usability, accessibility) and prioritising by risk. Think aloud.\n\nAutomation: be ready to explain your framework structure, locator strategy, waits, data handling, reporting, CI integration and how you keep tests reliable. Expect to write a small test live in your language of choice.\n\nAPI testing: HTTP methods, status codes, validating responses, and tools such as Postman or code-based clients.\n\nSQL basics come up for data validation.\n\nBehavioural: a bug you found that others missed, a disagreement with a developer about severity, and how you handled a release under time pressure.\n\nBring one automation project you can walk through, including a flaky test you fixed and how.",
    ["istqb", "testing", "selenium", "postmanLearning", "testAutomationU"],
    ["qa", "software testing", "interview", "manual testing", "automation"],
    ["sO8eGL6SFsA"],
  ],
  [
    "qa-portfolio",
    "How do I build a portfolio as a software tester?",
    ["What can a QA engineer show as evidence of skill?", "How do I demonstrate testing skills without a job?"],
    "portfolio",
    "portfolio",
    "Testers can show evidence more directly than most roles, because finding and documenting problems is the work.\n\nEvidence 1: a test plan and test cases for a real application (an open-source app or a public demo site), showing risk-based prioritisation, coverage of edge cases and clear expected results.\n\nEvidence 2: well-written bug reports. Pick an open-source project, find genuine defects, and file them with reproduction steps, environment and severity reasoning. Accepted bug reports are public proof of skill.\n\nEvidence 3: an automation suite in a public repository (Playwright, Selenium or Cypress for UI; a code-based API suite) with a README, CI runs and a section on how flakiness was handled.\n\nEvidence 4: exploratory testing notes from a time-boxed session, showing charter, findings and questions raised.\n\nAdd API testing and basic performance checks if you can. Keep everything readable by a hiring manager in ten minutes: a top-level README linking each piece with one paragraph of context.\n\nThis portfolio is stronger than a certificate alone and pairs well with one if you choose to take the ISTQB Foundation exam.",
    ["testing", "selenium", "istqb", "awesomeForBeginners", "postmanLearning"],
    ["qa", "portfolio", "software testing", "bug reports", "automation"],
  ],
  [
    "manual-tester-to-sdet",
    "How do I move from manual testing to an SDET role?",
    ["I am a manual tester; how do I become an automation engineer?", "What should a manual QA learn to get into automation?"],
    "career-switching",
    "roadmap",
    "Software development engineers in test write code, so the transition is learning to program with testing as your first application of it.\n\nStep 1: one language properly. Python or JavaScript/TypeScript are the fastest routes; Java if your company's automation is in Java. Learn variables, control flow, functions, classes, collections, error handling and reading documentation. Spend the first month here even if it feels slow.\n\nStep 2: automate what you already test manually. Take three manual test cases you know well and automate them with Playwright or Selenium. Learn locators, waits, assertions and a page object structure. Then add API tests with a code-based HTTP client.\n\nStep 3: engineering practices. Git, code review, a test framework's fixtures and parametrisation, running in CI, reporting, and handling flaky tests. Read your developers' unit tests and ask questions.\n\nStep 4: depth. Test design for automation, contract testing, basic performance testing, and understanding the application architecture so you can test at the right level.\n\nUse your position: ask to own one automated regression area at work. A manual tester who delivers a reliable automated suite is usually promoted before an outside hire is made.\n\nReady for SDET interviews when you can write a test live, explain your framework's design, and fix a flaky test by reasoning rather than adding sleeps.",
    ["testing", "selenium", "pytest", "jest", "testAutomationU", "githubActions"],
    ["manual testing", "sdet", "automation", "career switch", "qa"],
    ["788GvvcfwTY"],
  ],
  [
    "support-to-devops",
    "How do I move from IT support into DevOps?",
    ["I work in technical support; can I become a DevOps engineer?", "What should a support engineer learn for DevOps roles?"],
    "career-switching",
    "roadmap",
    "Support engineers already have the troubleshooting habit and the user empathy DevOps teams often lack. The gap is automation and systems depth.\n\nStep 1: Linux and scripting. Get comfortable on the command line, understand processes, permissions, services and logs, and write Bash scripts that automate something you do repeatedly at work. Add Python for anything longer than a page.\n\nStep 2: version control and CI. Put your scripts in Git, learn branching and pull requests, and build a small CI pipeline. Understanding how code gets from a laptop to production is the core of the role.\n\nStep 3: containers and cloud. Docker, then one cloud provider's core services and IAM, then Terraform for repeatable infrastructure. Deploy something end to end.\n\nStep 4: operations. Monitoring, alerting, on-call practices, incident write-ups. Your support experience makes you good at this part; document it.\n\nAt work, volunteer for automation tasks, ticket-reduction projects and anything touching deployments or monitoring. Ask to shadow the operations or platform team. Internal moves through a 'junior DevOps' or 'systems engineer' role are common.\n\nReady when you can explain a deployment pipeline you built, debug a service from logs and metrics, and show infrastructure you defined as code.",
    ["linux", "git", "docker", "terraform", "githubActions", "devopsRoadmapRepo"],
    ["it support", "devops", "career switch", "linux", "automation"],
    ["1J2YOV6LcwY"],
  ],
  [
    "security-certification-beginner",
    "Which cybersecurity certification should a beginner consider?",
    ["Is Security+ worth it for a cybersecurity beginner?", "Which entry-level security certification should I start with?"],
    "certifications",
    "certification",
    "For someone entering cybersecurity, the useful question is which credential structures the fundamentals you need and is recognised by the employers you are targeting, not which is 'best'.\n\nThree entry-level options come up most often in job descriptions: CompTIA Security+ (broad security fundamentals, vendor-neutral), ISC2's entry-level Certified in Cybersecurity, and Google's cybersecurity certificate (a structured beginner course rather than a professional credential). For hands-on offensive roles, practical lab-based certifications matter more than multiple-choice ones.\n\nHow to decide: read ten job descriptions for the roles you want in your area and count which credentials they mention; check each provider's page for the current exam objectives, format, cost and renewal rules, since all of these change; and prefer the one whose syllabus fills the gaps you actually have.\n\nWhatever you choose, pair it with hands-on evidence: a home lab, TryHackMe or Hack The Box progress, and investigation write-ups. Interviewers weight demonstrated skill over the certificate, and a certificate without practice is easy to expose in a scenario question.\n\nI cannot tell you whether an employer requires a specific credential; that is on their job description.",
    ["comptiaSecurity", "isc2", "growGoogle", "security", "tryhackme"],
    ["cybersecurity", "certification", "security+", "beginner", "isc2"],
  ],
  [
    "aws-certification-value",
    "Is an AWS certification worth it for cloud jobs?",
    ["Should I get AWS certified before applying for cloud roles?", "Which AWS certification should I start with?"],
    "certifications",
    "certification",
    "An AWS certification is useful when it structures learning you would do anyway and when the employers you target list it. It is not a substitute for having deployed and operated something.\n\nWhere it helps: consultancies and service companies often value certifications because clients ask for them; recruiters use them as a filter for candidates without cloud job titles; and the exam guide is a decent syllabus for fundamentals.\n\nWhere it does not: product companies typically test hands-on ability in interviews, and a certificate without a project behind it invites hard questions.\n\nSequencing: the Cloud Practitioner exam is an orientation; if you are already technical, many people start with the Solutions Architect Associate. Check the AWS certification page for the current exam versions, domains, cost and validity period, because these change and I will not quote them.\n\nStudy plan that works: AWS Skill Builder's free courses plus building a small real system (VPC, compute, database, IAM, monitoring) with Terraform, then practice exams. Put the project on your résumé next to the certificate.\n\nIf budget is tight, the project alone is more persuasive than the certificate alone.",
    ["aws", "awsTraining", "awsSkillBuilder", "terraform"],
    ["aws", "certification", "cloud", "solutions architect", "worth it"],
  ],
  [
    "istqb-value",
    "Is ISTQB worth it for a software tester?",
    ["Should I take the ISTQB Foundation exam?", "Do testers need a certification?"],
    "certifications",
    "certification",
    "The ISTQB Foundation certificate is widely recognised in service companies and gives you the shared vocabulary of testing: levels, types, techniques and process. Its syllabus is free to download, and reading it carefully is valuable whether or not you sit the exam.\n\nIt is worth taking when: job descriptions you are targeting mention it; you are moving into testing from another field and want a structured foundation; or your employer will fund it.\n\nIt is less decisive when: you already have hands-on automation work to show, or you are applying to product companies that interview on practical skills.\n\nWhat it does not do: it does not teach automation, it does not prove you can find defects, and it does not replace a portfolio of test cases, bug reports and an automation suite.\n\nCheck the ISTQB site and your local board for the current syllabus version, exam format and fees. If you take it, treat the preparation as a chance to write example test designs for each technique; those notes become interview material.",
    ["istqb", "testing", "testAutomationU"],
    ["istqb", "certification", "software testing", "qa", "worth it"],
  ],
  [
    "docker-vs-kubernetes-order",
    "Should I learn Docker or Kubernetes first?",
    ["Docker vs Kubernetes: which do I need for DevOps jobs?", "Do I need Kubernetes if I know Docker?"],
    "devops",
    "comparison",
    "Docker first, without exception. Docker is how you package an application into a container; Kubernetes is how you run many containers across machines reliably. Kubernetes concepts (pods, images, volumes, probes) assume you already understand containers, and its learning curve is steep enough without adding that gap.\n\nLearn Docker until you can write a small, secure Dockerfile, use Compose for a multi-service local setup, understand volumes and networking, and debug a container that will not start. That takes a few weeks of regular practice.\n\nThen ask whether you need Kubernetes at all. Many teams run containers on managed platforms without it. Learn Kubernetes when job descriptions you are targeting name it or when your project genuinely needs orchestration. For DevOps and platform roles it is usually expected; for application developers, Docker plus a deployment platform is often enough.\n\nA good middle step is deploying your Docker app to a managed container service, then moving the same app to a local Kubernetes cluster so you see what the orchestrator adds.",
    ["docker", "kubernetesTutorials", "kubernetes", "devopsRoadmapRepo"],
    ["docker", "kubernetes", "containers", "devops", "learning order"],
    ["fqMOX6JJhGo", "X48VuDVv0do"],
  ],
  [
    "aws-vs-azure-first",
    "Should I learn AWS or Azure first?",
    ["AWS vs Azure for a beginner cloud engineer", "Which cloud provider should I learn for jobs?"],
    "cloud",
    "comparison",
    "The skills transfer between providers, so the first one matters less than learning it deeply. Decide with local evidence rather than global market share arguments.\n\nRead twenty cloud job descriptions in your region and count providers. Companies that build on Microsoft tooling (.NET, Active Directory, Office 365) lean Azure; startups and many product companies lean AWS; data and analytics teams sometimes lean Google Cloud. Your current employer's provider, if any, is the strongest tie-breaker because you can practise on real systems.\n\nWhichever you pick, learn the provider-neutral fundamentals first: networking, identity and access, compute, storage, databases, infrastructure as code, monitoring and cost. Then the provider's implementation of each. A second provider takes weeks, not months, once the first is solid.\n\nBoth providers offer free official training (AWS Skill Builder, Microsoft Learn) and entry-level certifications; check their pages for current details. Avoid splitting your first six months across two providers; shallow knowledge of both is less useful than depth in one.",
    ["awsTraining", "azureTraining", "gcpLearn", "terraform"],
    ["aws", "azure", "cloud", "comparison", "learning order"],
    ["SOTamWNgDKc", "NKEFWyqJ5XA"],
  ],
];
