import type { Row } from "./schema";

/**
 * Interview preparation by role, portfolio guidance, certification decisions,
 * learning-resource questions and career switches. Resource answers describe
 * how to use the linked material; the cards underneath carry the links.
 */
export const preparationRows: Row[] = [
  [
    "python-developer-interview-prep",
    "How do I prepare for a Python developer interview?",
    ["What is asked in Python developer interviews?", "Python backend interview preparation plan", "Python interview questions for freshers"],
    "technical-interviews",
    "interview",
    "Python developer interviews mix language questions, coding exercises, backend concepts and a project discussion.\n\nLanguage: mutability and references, list versus tuple versus set versus dict and when to use each, comprehensions, generators and iterators, decorators, context managers, exceptions, the GIL at a conceptual level, and how modules and packaging work. Prepare a ten-line example for each rather than a definition.\n\nCoding: string and collection manipulation, recursion, sorting with keys, simple algorithm problems at an easy-to-medium level. Practise typing solutions without an IDE's help.\n\nBackend: HTTP methods and status codes, REST design, authentication basics, SQL joins and indexes, ORMs versus raw SQL, how you would structure a Django or FastAPI project, testing with pytest, and environment and dependency management.\n\nProject: walk through one service you built: the data model, one hard bug, one trade-off, and how you tested and deployed it.\n\nBehavioural: learning something quickly, disagreeing on a technical decision, and handling an incident or missed deadline.\n\nMock interview with a friend, out loud, using a timer. Reading the official tutorial's sections on classes, errors and modules the week before fills most language gaps.",
    ["python", "pytest", "fastapi", "django", "sql", "techInterviewHandbook"],
    ["python", "interview", "backend", "coding round", "fresher"],
    ["rfscVS0vtbw"],
  ],
  [
    "java-developer-interview-prep",
    "How do I prepare for a Java developer interview?",
    ["What is asked in Java interviews?", "Java backend interview preparation", "Core Java and Spring Boot interview questions preparation"],
    "technical-interviews",
    "interview",
    "Java interviews go deeper into language and design than most, because Java teams value structure.\n\nCore Java: object-oriented principles with examples, interfaces versus abstract classes, equals and hashCode, collections (ArrayList versus LinkedList, HashMap internals), generics, exceptions (checked versus unchecked), immutability, String handling, Java 8+ features (streams, lambdas, Optional), and memory basics (heap, stack, garbage collection at a conceptual level).\n\nConcurrency: threads, executors, synchronisation, common pitfalls; this area is asked more in Java interviews than elsewhere.\n\nSpring Boot: dependency injection, bean scopes, how a request moves through controllers and services, JPA and transactions, exception handling, profiles and configuration, and how you would test each layer.\n\nDatabases: SQL joins, indexes, transactions and isolation levels.\n\nCoding: collection manipulation and moderate algorithm problems; write clean, compilable code by hand.\n\nDesign: a class design exercise (model a parking lot, a library) and, for experienced roles, a system design conversation.\n\nProject: be ready to explain your layered architecture and one performance or concurrency decision.\n\nOracle's Java tutorials and the Spring Boot reference cover the ground; practise explaining concepts aloud in two sentences each.",
    ["javaTutorials", "javaLearn", "springBoot", "springGuides", "sql", "techInterviewHandbook"],
    ["java", "interview", "spring boot", "core java", "backend"],
    ["grEKMHGYyns"],
  ],
  [
    "frontend-interview-prep",
    "How do I prepare for a frontend developer interview?",
    ["What is asked in React interviews?", "Frontend interview preparation plan", "React developer interview questions preparation"],
    "technical-interviews",
    "interview",
    "Frontend interviews test JavaScript depth, framework understanding, CSS and layout, browser knowledge, and often a practical build.\n\nJavaScript: closures, this, prototypes, promises and the event loop, array methods, debouncing and throttling, and DOM events. Expect snippet questions asking what a piece of code prints.\n\nReact (or your framework): component lifecycle with hooks, state versus props, when effects run, keys, controlled inputs, context, memoisation and when it matters, and how you would structure a medium application. Explain server rendering if Next.js is on the job description.\n\nCSS and layout: flexbox and grid, responsive design, specificity, positioning, and how you would build a common component (a modal, a dropdown) accessibly.\n\nBrowser and performance: how a page loads, critical rendering path basics, caching, lazy loading, Core Web Vitals at a conceptual level, and security basics (XSS, CSRF).\n\nPractical: a take-home or live build of a small component or page with API data. Handle loading, error and empty states, and write one test if time allows.\n\nAccessibility questions are increasingly common: keyboard navigation, labels, focus management.\n\nBring a deployed project and be ready to walk through its structure and one hard bug. The Modern JavaScript Tutorial and the official React docs cover almost everything above.",
    ["javascriptInfo", "react", "webDev", "access", "techInterviewHandbook"],
    ["frontend", "react", "interview", "javascript", "css"],
    ["bMknfKXIFA8"],
  ],
  [
    "python-backend-portfolio",
    "What should a Python backend developer portfolio include?",
    ["Which Python projects impress employers?", "How do I build a backend portfolio in Python?"],
    "portfolio",
    "portfolio",
    "One deployed, tested, documented service is the core of a backend portfolio. Add a second project that shows a different shape of problem, and a small script collection that shows daily fluency.\n\nCore service: a REST API with users and ownership rules, a relational database with migrations, validation, authentication, pagination and filtering, tests with pytest, a Dockerfile, a CI workflow and a live URL. Choose a domain you understand (bookings, inventory, a job tracker) so the data model is realistic.\n\nSecond project: something asynchronous or data-heavy: a background job queue, a web scraper with scheduling and storage, an integration with a third-party API with retries and rate limits, or a small data pipeline.\n\nScripts: a handful of automation scripts with clear READMEs show you use Python the way working developers do.\n\nFor each repository: a README with what it does, how to run it, the architecture in a paragraph or diagram, decisions and trade-offs, and known limitations. Clean commit history and no secrets in the repo.\n\nWhat to avoid: tutorial clones without changes, notebooks passed off as services, and projects with no tests.\n\nA reviewer should be able to run your service in under five minutes and hit a working endpoint.",
    ["fastapi", "django", "pytest", "docker", "githubActions", "appIdeas", "projectBasedLearning"],
    ["python", "backend", "portfolio", "projects", "rest api"],
  ],
  [
    "frontend-portfolio",
    "What should a frontend developer portfolio include?",
    ["Which frontend projects impress recruiters?", "How do I build a React portfolio?"],
    "portfolio",
    "portfolio",
    "Frontend portfolios are judged in the browser first, so deploy everything and make the first impression fast and clean.\n\nProject 1: a complete application. Authentication, data from an API, several routes, forms with validation, loading and error states, responsive layout, keyboard accessibility and tests. Deploy it with a custom domain if you can.\n\nProject 2: a craft piece. A pixel-accurate implementation of a design, a small component library with documentation, or a performance case study where you measured and improved a page.\n\nProject 3: something that shows range: a data visualisation, an animation-heavy page, or a small tool people actually use.\n\nYour portfolio site itself is a project: fast, accessible, responsive, with a clear summary of each project, screenshots, live links and repository links. Check it on a phone and with a keyboard only.\n\nFor each project write the problem, your role, the stack, one difficult decision and what you would improve. Recruiters read these in under a minute; developers reviewing you read the code, so keep it consistent and linted.\n\nAvoid unfinished projects, broken links and generic to-do apps without a twist.",
    ["react", "webDev", "access", "designResources", "appIdeas"],
    ["frontend", "portfolio", "react", "projects", "deploy"],
  ],
  [
    "google-data-analytics-certificate-value",
    "Is the Google Data Analytics certificate worth doing?",
    ["Should I take the Google Data Analytics Professional Certificate?", "Do beginner data certificates help get analyst jobs?"],
    "certifications",
    "certification",
    "The Google Data Analytics certificate is a structured beginner course covering the analytics process, spreadsheets, SQL, basic R and Tableau, ending in a capstone. It is useful as a curriculum for someone starting from zero, and recognisable enough that recruiters know what it covers.\n\nIt helps most when you have no data background and want structure, when you finish the capstone and extend it into a real portfolio piece, and when you combine it with independent SQL practice, because its SQL depth is modest.\n\nIt does not by itself get an analyst job; employers screen on portfolio and interview performance, and many applicants hold the certificate. Treat it as a learning path, not a credential.\n\nBefore paying, check the Coursera page for current pricing, audit options and financial aid, since these change. Similar beginner programmes exist from other providers; compare their syllabi against ten job descriptions for the roles you want.\n\nA stronger combination: the certificate's structure plus a dashboard on real data, plus SQL exercises you can solve live, plus one written analysis with a recommendation.",
    ["googleDataAnalytics", "growGoogle", "sqlbolt", "kaggleLearn"],
    ["google data analytics", "certificate", "data analyst", "worth it", "coursera"],
  ],
  [
    "marketing-certifications-value",
    "Are free marketing certifications from Google and HubSpot useful?",
    ["Should I get Google Ads or HubSpot certified?", "Which digital marketing certifications are worth it?"],
    "certifications",
    "certification",
    "Free certifications from Google Skillshop (Ads, Analytics) and HubSpot Academy (inbound, content, email, SEO) are worth completing: they are free, provider-official, and recruiters recognise them as evidence you know the tools' vocabulary and interfaces.\n\nTheir limits: they test recall, not judgment, and many candidates hold them. They will not distinguish you on their own.\n\nUse them as a study structure while you run something real: a small paid campaign, a content site, a newsletter. Then present results and reasoning first and certificates second.\n\nPaid certifications in marketing are rarely required; check any job descriptions you are targeting before spending. Platform certifications expire and are periodically updated, so verify current versions on the provider sites.\n\nA practical order: Google Analytics fundamentals, then Google Ads Search, then HubSpot inbound and content marketing, each paired with a hands-on experiment you document.",
    ["skillshop", "hubspotAcademy", "semrushAcademy", "googleAnalyticsHelp"],
    ["marketing", "certification", "google skillshop", "hubspot", "worth it"],
  ],
  [
    "scrum-pmp-certification-value",
    "Do I need a Scrum or project management certification for product or project roles?",
    ["Is a Scrum Master certification worth it?", "Should I get PMP or a Scrum certification?"],
    "certifications",
    "certification",
    "It depends on the role type. Traditional project management roles in construction, infrastructure, government and large enterprises often list PMP or equivalent; software product and delivery roles rarely require any certification and hire on demonstrated delivery.\n\nScrum certifications are inexpensive and quick, and they give you the shared vocabulary of agile delivery; the Scrum Guide they are based on is free and short, so read it first. They help most for Scrum Master, delivery manager and some business analyst roles, and least for product manager roles, where product judgment matters more.\n\nPMP and similar credentials require documented experience and an exam; check the certifying body's current eligibility rules and fees directly rather than relying on summaries.\n\nDecide by counting mentions in twenty job descriptions for your target role. If a credential appears in most, it is a screening filter and worth planning for; if it appears in few, spend the time on delivering something measurable and documenting it.\n\nNo certification substitutes for having run a delivery, handled a slip and kept stakeholders informed; make sure you have at least one such story.",
    ["scrumGuide", "product", "productplan", "iiba"],
    ["scrum", "pmp", "certification", "project management", "product management"],
  ],
  [
    "acca-vs-ca-choice",
    "Should I pursue ACCA or CA?",
    ["ACCA vs CA for an accounting career", "Which accounting qualification should I choose?"],
    "accounting-finance",
    "comparison",
    "Both are respected accounting qualifications with different geographies and structures. Chartered Accountancy through ICAI is the statutory qualification in India with statutory audit rights there; ACCA is a UK-based global qualification recognised widely in the UK, Middle East, parts of Asia and by multinational employers.\n\nChoose CA if you plan to practise or work primarily in India, want audit signing authority, or target Indian firms and companies that specifically require it. Choose ACCA if you want international mobility, flexibility in exam scheduling, or work in multinational or outsourced finance teams. Some people do both, using exemptions.\n\nThe structures, exemptions, durations, practical experience requirements and fees are set by each body and change; read icai.org and accaglobal.com directly and confirm your own situation with them. I will not quote those details.\n\nBeyond the credential, employers hire on fundamentals, tool skills and practical exposure, so whichever you choose, build spreadsheet, accounting-software and tax-portal competence alongside the exams.",
    ["icai", "acca", "icmai", "khanFinance"],
    ["acca", "ca", "accounting", "qualification", "comparison"],
    ["CqZSxeo9gUQ"],
  ],
  [
    "free-python-resources",
    "What are the best free resources to learn Python?",
    ["Where can I learn Python for free?", "Free Python courses and books for beginners"],
    "learning-resources",
    "guidance",
    "You can learn Python to a job-ready level without paying, if you combine one structured course with daily practice and one real project.\n\nStructured start: the official Python Tutorial for the language itself, or freeCodeCamp's Python certification if you prefer exercises with checks. Automate the Boring Stuff is the best free book for people who want useful scripts immediately.\n\nPractice: solve small problems daily and read other people's solutions after your own attempt. The TheAlgorithms Python repository is useful for comparing implementations.\n\nProjects: pick from a curated list of ideas and finish one end to end with tests and a README; the App Ideas and Project Based Learning repositories are good sources.\n\nWhen you specialise: the FastAPI and Django tutorials for backend, pandas and Kaggle Learn for data.\n\nUse the resource cards below; the sequence matters more than the number of resources. One course, one book, one project at a time.",
    ["python", "freecodecamp", "automate", "pythonAlgorithms", "appIdeas", "projectBasedLearning", "awesomePython"],
    ["python", "free resources", "learn", "courses", "books"],
    ["rfscVS0vtbw", "8DvywoWv6fI"],
  ],
  [
    "free-web-development-resources",
    "What are the best free resources to learn web development?",
    ["Where can I learn JavaScript and web development for free?", "Free full stack web development courses"],
    "learning-resources",
    "guidance",
    "Web development has the richest free curricula of any field. Choose one path and follow it to the end rather than sampling all of them.\n\nComplete curricula: The Odin Project (project-heavy, full stack), Full Stack Open from the University of Helsinki (React, Node, TypeScript, testing), and freeCodeCamp's responsive web design and JavaScript certifications.\n\nReference and depth: MDN's learning area and web.dev for fundamentals, The Modern JavaScript Tutorial and Eloquent JavaScript for the language, the official React and Next.js docs for the framework.\n\nProjects and practice: the App Ideas repository for scoped projects; open-source issues labelled for beginners for real code review experience.\n\nA workable sequence: HTML and CSS from MDN, JavaScript from javascript.info, then Full Stack Open or The Odin Project, then a deployed project of your own. Use the cards below; each is free and maintained.",
    ["odin", "fullstackOpen", "freecodecamp", "web", "webDev", "javascriptInfo", "react", "nextjs", "appIdeas", "awesomeForBeginners"],
    ["web development", "free resources", "javascript", "react", "courses"],
    ["LzMnsfqjzkA", "jS4aFq5-91M"],
  ],
  [
    "free-data-science-resources",
    "What are the best free resources to learn data science?",
    ["Where can I learn data analytics and machine learning for free?", "Free data science courses and books"],
    "learning-resources",
    "guidance",
    "Free data science material is abundant; the discipline is in sequencing it and building projects between courses.\n\nFoundations: Kaggle Learn's short courses for Python, pandas, SQL and introductory machine learning, with practice notebooks; SQLBolt and Mode's tutorial for SQL; OpenIntro Statistics for statistics.\n\nStructured curricula: Microsoft's Data Science for Beginners and ML for Beginners on GitHub, and the Machine Learning Specialization on Coursera (auditable).\n\nDepth: An Introduction to Statistical Learning (free textbook with labs), the scikit-learn user guide, and fast.ai or Dive into Deep Learning when you reach neural networks.\n\nCommunity and datasets: Kaggle competitions and the Awesome Data Science list for datasets and reading.\n\nSequence: SQL and pandas, then statistics, then one classical ML course, then a project on real data, then deep learning only if your target roles need it. The cards below are all free or auditable.",
    ["kaggleLearn", "sqlbolt", "modeSql", "statistics", "dataScienceBeginners", "mlForBeginners", "mlSpecialization", "statLearning", "sklearn", "awesomeDataScience"],
    ["data science", "free resources", "machine learning", "courses", "analytics"],
    ["ua-CiDNNj30", "r-uOLxNrNk8"],
  ],
  [
    "free-generative-ai-resources",
    "What are the best free resources to learn generative AI and LLMs?",
    ["Where can I learn LLM engineering for free?", "Free courses on generative AI and prompt engineering"],
    "learning-resources",
    "guidance",
    "The best generative AI material is free and recent, because the field moves quickly and providers publish their own guides.\n\nConcepts: Karpathy's introduction to large language models (video) and the Prompt Engineering Guide.\n\nBuilding: Microsoft's Generative AI for Beginners course on GitHub, the DeepLearning.AI short courses on RAG, agents and evaluation, and the OpenAI Cookbook and Claude platform documentation for worked examples.\n\nInternals: Hugging Face Learn for transformers and fine-tuning, the LLM Course repository for a roadmap with notebooks, and Build a Large Language Model From Scratch for the full implementation.\n\nFrameworks: LangChain and LlamaIndex documentation for retrieval and agent patterns.\n\nSequence: concepts, then build three small applications, then evaluation, then internals if you want the model track. Use the cards below and keep one notebook of experiments you can show.",
    ["promptingGuide", "genaiBeginners", "dlaiShortCourses", "openaiCookbook", "claudeDocs", "hfLearn", "llmCourse", "llmsFromScratch", "langchain", "llamaindex"],
    ["generative ai", "llm", "free resources", "courses", "prompt engineering"],
    ["zjkBMFhNj_g", "mEsleV16qdo"],
  ],
  [
    "free-devops-cloud-resources",
    "What are the best free resources to learn DevOps and cloud?",
    ["Where can I learn AWS, Docker and Kubernetes for free?", "Free DevOps courses and labs"],
    "learning-resources",
    "guidance",
    "DevOps and cloud skills come from doing, so prefer resources with labs and build on a free-tier account.\n\nProvider training: AWS Skill Builder's free courses, Microsoft Learn's Azure paths with sandboxes, and Google Cloud Skills Boost.\n\nTools: the official Docker getting-started guide, Kubernetes interactive tutorials, Terraform tutorials and GitHub Actions documentation.\n\nRoadmaps and practice: the DevOps Roadmap repository for sequencing, DevOps Exercises for thousands of practice questions, and roadmap.sh for a visual map.\n\nReading: Google's free SRE books for how production systems are run well, and the Twelve-Factor App for service design.\n\nSequence: Linux and networking, Git, Docker, one cloud provider's core services, Terraform, CI/CD, Kubernetes, monitoring. Keep a repository of everything you build; it becomes your portfolio.",
    ["awsSkillBuilder", "azureTraining", "cloudSkillsBoost", "docker", "kubernetesTutorials", "terraform", "githubActions", "devopsRoadmapRepo", "devopsExercises", "sreBooks", "developerRoadmap"],
    ["devops", "cloud", "free resources", "aws", "docker", "kubernetes"],
    ["fqMOX6JJhGo", "1J2YOV6LcwY"],
  ],
  [
    "free-cybersecurity-resources",
    "What are the best free resources to learn cybersecurity?",
    ["Where can I practise cybersecurity legally for free?", "Free cybersecurity courses and labs for beginners"],
    "learning-resources",
    "guidance",
    "Cybersecurity has excellent free, legal practice environments; use them rather than testing on systems you do not own.\n\nCourses: Harvard CS50's cybersecurity course, Google's cybersecurity certificate introduction, and the NIST NICE framework for understanding work roles.\n\nHands-on labs: TryHackMe (free tier), Hack The Box, and PortSwigger's Web Security Academy for web application security.\n\nReference: the OWASP Top Ten and Cheat Sheet Series for application security, and curated lists such as Awesome Security for tools.\n\nCertification syllabi: CompTIA Security+ objectives and ISC2's entry credential outline are free to read and make good study checklists; check the provider sites for current exam details.\n\nSequence: networking and operating systems first, then defensive concepts and a SIEM lab, then web security labs, then offensive labs if that is your direction. Document every lab in write-ups.",
    ["cs50", "growGoogle", "security", "tryhackme", "hackthebox", "portswigger", "owaspTop10", "owaspCheatSheets", "awesomeSecurity", "comptiaSecurity", "isc2"],
    ["cybersecurity", "free resources", "labs", "ethical hacking", "courses"],
    ["9HOpanT0GRs", "ug8W0sFiVJo"],
  ],
  [
    "free-design-resources",
    "What are the best free resources to learn UI/UX design?",
    ["Where can I learn UX design for free?", "Free UI design courses and references"],
    "learning-resources",
    "guidance",
    "UX and UI design can be learned free with a combination of reading, tool practice and self-initiated projects.\n\nReading: Nielsen Norman Group articles for research-backed usability guidance, Laws of UX for psychology principles, and the Interaction Design Foundation's open literature.\n\nGuidelines: Material Design and Apple's Human Interface Guidelines show how mature design systems reason about components and accessibility; the W3C accessibility tutorials cover inclusive patterns.\n\nTools: Figma's Help Center and resource library, plus curated free assets from the Design Resources for Developers list.\n\nStructured course: Google's UX design certificate is a paid programme with a clear syllabus; check its page for current pricing and aid, and compare it against building three case studies on your own.\n\nSequence: fundamentals from reading, recreate existing screens in Figma, run a five-person usability test on a prototype, write case studies. The cards below cover each step.",
    ["nngroup", "lawsOfUx", "ixdf", "material", "hig", "access", "figmaHelp", "figmaLibrary", "designResources", "growGoogle"],
    ["ux", "ui design", "free resources", "figma", "courses"],
    ["c9Wg6Cb_YlU"],
  ],
  [
    "free-accounting-finance-resources",
    "What are the best free resources to learn accounting and finance?",
    ["Where can I learn accounting basics for free?", "Free finance courses and references"],
    "learning-resources",
    "guidance",
    "Accounting fundamentals are well covered by free material, and the official portals for tax and standards are the only reliable references for rules.\n\nFundamentals: Khan Academy's finance and accounting videos and full-length free accounting courses on video cover bookkeeping through the financial statements.\n\nSpreadsheets: Excel Easy and Microsoft's official Excel training for the functions accountants and analysts use daily.\n\nStandards and rules: the IFRS Foundation for international standards; in India, the GST portal, the Income Tax Department and the Ministry of Corporate Affairs for filing procedures; SEBI for markets regulation. Always read rules there rather than from summaries.\n\nProfessional bodies: ICAI, ICMAI, ICSI, ACCA and CFA Institute publish their own syllabi and, often, free study material for registered students.\n\nSequence: fundamentals, then spreadsheets, then one accounting package, then the compliance portals relevant to your role. The cards below link each.",
    ["khanFinance", "excelEasy", "excelSupport", "ifrs", "gst", "incomeTax", "mca", "sebi", "icai", "acca", "cfa", "tally"],
    ["accounting", "finance", "free resources", "excel", "gst"],
    ["v-djL7SPw4c", "m_SH0TOLsIc"],
  ],
  [
    "free-marketing-resources",
    "What are the best free resources to learn digital marketing?",
    ["Where can I learn SEO and digital marketing for free?", "Free digital marketing certifications and guides"],
    "learning-resources",
    "guidance",
    "Digital marketing has strong free training from the platforms themselves and from established tool vendors.\n\nPlatform training: Google Skillshop for Ads and Analytics, HubSpot Academy for inbound, content and email, and Semrush Academy for SEO and competitive research.\n\nSEO: Google's SEO Starter Guide and Search Central documentation, Moz's Beginner's Guide to SEO, and the Ahrefs and Backlinko blogs for practical guides.\n\nAnalytics: Google Analytics Help for measurement setup and reporting.\n\nUpdates: Google's Ads and Commerce blog for official product changes.\n\nSequence: analytics first (so you can measure), then SEO fundamentals, then one paid channel, then content and email. Run a real campaign or site alongside the courses so you have results to show.",
    ["skillshop", "hubspotAcademy", "semrushAcademy", "seo", "mozSeo", "ahrefsBlog", "backlinko", "googleAnalyticsHelp", "googleAdsBlog"],
    ["digital marketing", "free resources", "seo", "certifications", "courses"],
    ["kunkYTKFNtI", "xsVTqzratPs"],
  ],
  [
    "github-repositories-for-learning",
    "Which GitHub repositories are most useful for learning to code?",
    ["What are the best GitHub repos for developers who are learning?", "Free open-source curricula on GitHub"],
    "learning-resources",
    "guidance",
    "A few GitHub repositories are effectively free curricula, and they are maintained by large communities.\n\nRoadmaps and curricula: the developer-roadmap project behind roadmap.sh, OSSU's computer science curriculum, and Microsoft's beginner courses (web development, machine learning, data science, AI, generative AI).\n\nInterview preparation: Coding Interview University, the Tech Interview Handbook and the System Design Primer.\n\nProjects: Project Based Learning and App Ideas for scoped projects; Awesome for Beginners for open-source issues you can take.\n\nPractice and reference: TheAlgorithms implementations, Node.js Best Practices, OWASP Cheat Sheets, DevOps Exercises.\n\nHow to use them: pick one roadmap, one project source and one practice repository. Star the rest for later. Reading a curriculum is not progress; finishing a project from it is.",
    ["developerRoadmap", "ossu", "webDevBeginners", "mlForBeginners", "dataScienceBeginners", "aiForBeginners", "genaiBeginners", "codingInterviewUniversity", "techInterviewHandbook", "systemDesignPrimer", "projectBasedLearning", "appIdeas", "awesomeForBeginners", "pythonAlgorithms", "nodeBestPractices", "owaspCheatSheets", "devopsExercises"],
    ["github", "repositories", "free resources", "curriculum", "open source"],
  ],
  [
    "non-tech-graduate-to-software",
    "How can a non-technical graduate get into software development?",
    ["I have an arts or commerce degree; can I become a developer?", "How do I start programming with no technical background?"],
    "career-switching",
    "roadmap",
    "Plenty of developers came from non-technical degrees; what employers check is whether you can build and explain software, not what you studied.\n\nMonths 1-3: learn to program. CS50 or the first sections of The Odin Project give structure. Practise daily, finish small programs, and learn Git early. Do not buy anything yet.\n\nMonths 4-6: pick a track (web is the most accessible) and follow one complete free curriculum to the end. Build two projects of your own design and deploy them.\n\nMonths 7-9: fill computer science gaps that interviews test: data structures, basic algorithms, how the web and databases work. Contribute a small fix to an open-source project for code review experience.\n\nMonths 10-12: interview preparation, a portfolio site, a résumé that leads with projects, and applications to entry roles, internships and apprenticeships. Use your degree's strengths (writing, analysis, domain knowledge) as a differentiator, not something to hide.\n\nThe timeline stretches if you are working full time; consistency matters more than speed. Local bootcamps can compress it if you verify their outcomes and can afford them.\n\nReady when you can build a small application from a description without a tutorial, explain your code line by line, and describe what you would do differently.",
    ["cs50", "odin", "freecodecamp", "git", "awesomeForBeginners", "techInterviewHandbook"],
    ["non-technical", "career switch", "software developer", "beginner", "arts graduate", "commerce graduate"],
    ["GxmfcnU3feo"],
  ],
  [
    "tester-to-developer",
    "How do I move from software testing into a developer role?",
    ["I am a QA engineer; how do I become a software developer?", "Can a tester switch to development?"],
    "career-switching",
    "roadmap",
    "Testers understand requirements, edge cases and the product, which are strengths most junior developers lack. The gap is building features, data modelling and design.\n\nStep 1: if you already automate tests, you already program; deepen the language you use (data structures, classes, error handling, modules). If you do not, start there with one language for three months.\n\nStep 2: build features, not tests. Take the application you test and implement a small feature end to end in a personal copy or a similar toy app: interface, API, database, tests. Then a second one.\n\nStep 3: fundamentals developers are interviewed on: HTTP, databases and SQL, basic algorithms, version control workflows, and one framework properly.\n\nStep 4: use your position. Ask to fix small bugs in the codebase you test, pair with developers on reviews, and take developer-adjacent tickets. An internal move to a junior developer role is the most common route and keeps your domain knowledge valuable.\n\nOn the résumé, present your testing work in developer terms: the automation framework you designed, the CI pipeline you maintained, the bugs you diagnosed to root cause.\n\nReady when you can implement a feature from a ticket, explain your data model and defend a design choice in review.",
    ["fullstackOpen", "odin", "sql", "git", "techInterviewHandbook"],
    ["tester", "qa", "developer", "career switch", "software development"],
  ],
  [
    "reading-job-descriptions",
    "How do I use job descriptions to decide what to learn?",
    ["How do I work out which skills employers actually want?", "What should I look for in a job description when planning my learning?"],
    "job-search",
    "guidance",
    "Job descriptions are the most reliable free market data you have, if you read them systematically rather than one at a time.\n\nCollect twenty to thirty current postings for the exact role and location you want. Copy the requirements into a spreadsheet, one row per skill or tool, and count mentions. The top ten items are your curriculum; anything mentioned once is noise.\n\nSeparate what is required from what is preferred, and separate credentials from skills. A tool mentioned in most postings is worth learning even if you dislike it; a credential mentioned in most postings is a screening filter you must plan for; a credential mentioned in a few is optional.\n\nRead the responsibilities, not only the requirements: they tell you what a normal week contains, which is what you should practise and what your portfolio should demonstrate.\n\nRepeat the exercise every few months, because stacks shift. Keep the sheet; it also becomes your list of keywords for a tailored résumé and your list of questions to ask in interviews.\n\nAvoid the trap of adding every listed tool to your plan. Depth in the top five beats a checklist of twenty.",
    ["jobs", "blsOoh", "developerRoadmap", "occupations"],
    ["job descriptions", "skills", "learning plan", "market", "requirements"],
  ],
  [
    "first-job-in-new-domain",
    "How do I get my first job in a field where I have no experience?",
    ["How do I break into a new career with no relevant experience?", "Nobody hires without experience; how do I start?"],
    "job-search",
    "guidance",
    "Entry into a new field is a sequence of small credibility steps, not one leap. The aim is to make the hiring manager's risk small.\n\nCreate experience where none exists: projects that mirror the job's daily tasks, volunteer or freelance work scoped tightly, internships and apprenticeships, and contributions to open communities. Document each as work, with outcomes.\n\nTarget the right openings: entry-level and junior roles, roles in smaller companies where breadth matters more than titles, adjacent roles that use your existing strengths (support before engineering, analyst before scientist, coordinator before recruiter), and internal moves at your current employer.\n\nMake your application about them: a résumé that leads with relevant projects and skills, a short note explaining why this role and what you have done to prepare, and a portfolio link that opens instantly.\n\nUse people: informational conversations with people in the role, referrals after you have shown work, and communities where hiring managers see your questions and answers.\n\nExpect rejections and treat them as information: collect the reasons where you can and fix the most common one. Persistence with adjustment is what usually works, not volume alone.",
    ["jobs", "ilo", "apprentice", "theMuse", "resume"],
    ["first job", "no experience", "entry level", "career change", "job search"],
  ],
  [
    "learning-with-open-source",
    "How do I use open-source contribution to build experience?",
    ["Can open source replace work experience on a resume?", "How do I find open-source projects to contribute to as a beginner?"],
    "portfolio",
    "portfolio",
    "Open-source contribution is the closest thing to professional experience you can get without a job: real codebases, code review, collaboration and public evidence.\n\nStart small and real: documentation fixes, reproducing and confirming bugs, adding tests, then small features. Lists such as Awesome for Beginners collect projects that label beginner-friendly issues; also look at tools you already use.\n\nDo it properly: read the contributing guide, discuss before large changes, write clear pull request descriptions, respond to review promptly and without defensiveness, and follow the project's style. Maintainers remember contributors who make their lives easier.\n\nOn the résumé, list contributions like work: the project, what you changed, the effect, with links. Merged pull requests reviewed by strangers are strong evidence.\n\nIt complements rather than replaces personal projects: your own project shows you can build; contributions show you can collaborate. Employers value both, and the combination answers the 'no experience' objection convincingly.",
    ["awesomeForBeginners", "git", "codingInterviewUniversity"],
    ["open source", "contribution", "experience", "portfolio", "github"],
    ["RGOj5yH7evk"],
  ],
  [
    "system-design-interview-resources",
    "Which resources should I use to prepare for system design interviews?",
    ["Best free resources for system design preparation", "How do I study system design as a mid-level developer?"],
    "technical-interviews",
    "interview",
    "System design preparation works best in three layers: concepts, worked examples, and practice out loud.\n\nConcepts: the System Design Primer covers scalability, caching, databases, queues, load balancing and consistency with clear explanations; System Design 101 adds visual summaries. Google's SRE books explain how reliability is actually achieved.\n\nWorked examples: study how real companies solved problems in the Awesome Scalability reading list and in engineering blogs, noting the trade-offs they name.\n\nPractice: take a common prompt (URL shortener, news feed, chat, ride matching), set a timer for forty minutes, and talk through requirements, estimates, high-level design, data model, bottlenecks and trade-offs. Record yourself or use a peer. Structure and reasoning are what interviewers grade.\n\nPair the study with your own project: add caching, a queue or a read replica to something you built and measure the effect. Interviewers can tell the difference between recited architecture and experienced trade-offs.\n\nThe cards below are free; a paid course is optional and not necessary.",
    ["systemDesignPrimer", "systemDesign101", "awesomeScalability", "sreBooks", "twelveFactor"],
    ["system design", "interview", "resources", "scalability", "architecture"],
    ["F2FmTdLtb_4"],
  ],
  [
    "coding-interview-resources",
    "Which resources should I use to prepare for coding interviews?",
    ["Best free resources for data structures and algorithms practice", "How do I prepare for coding rounds without paying for courses?"],
    "technical-interviews",
    "interview",
    "Coding interview preparation is mostly deliberate practice; the resources exist to structure it.\n\nPlan: Coding Interview University is a thorough self-study checklist; the Tech Interview Handbook is a shorter, practical guide that also covers behavioural questions and résumés.\n\nPractice: NeetCode organises problems by pattern with explanations, which is more efficient than random problem lists; HackerRank is common in employer screens and worth a few sessions to learn its interface.\n\nDepth: the Algorithms for Competitive Programming site when you need more than interview basics.\n\nMethod: solve by pattern (two pointers, sliding window, hash maps, trees, graphs, dynamic programming), time yourself, explain your approach aloud before coding, and review every problem you could not solve two days later. Two focused hours a day for two to three months is a common preparation window; adjust to your target companies.\n\nDo not neglect the rest of the interview: projects, design and behavioural questions decide as many outcomes as algorithm rounds.",
    ["codingInterviewUniversity", "techInterviewHandbook", "neetcode", "hackerrank", "cpAlgorithms"],
    ["coding interview", "dsa", "resources", "leetcode", "practice"],
    ["RBSGKlAvoiM"],
  ],
];
