import type { KnowledgeEntry } from "../../lib/career-tutor/types";
import { type Row, expansionReviewNote, sources, toEntries } from "./schema";
import { roleRows } from "./roles";
import { skillRows } from "./skills";
import { educationRows } from "./education";
import { jobSearchRows } from "./job-search";
import { interviewRows } from "./interviews";
import { workplaceRows } from "./workplace";
import { techRoleRows } from "./tech-roles";
import { dataAiRows } from "./data-ai";
import { opsSecurityQaRows } from "./ops-security-qa";
import { businessRoleRows } from "./business-roles";
import { comparisonRows } from "./comparisons";
import { preparationRows } from "./preparation";
import { videoById, videoSource } from "./videos";

export { sources };

/**
 * Verified registry videos attached to entries authored before the video
 * registry existed. Each pairing was chosen by reading the entry; a video is
 * listed only where it teaches the entry's own subject.
 */
const videoAttachments: Record<string, string[]> = {
  "data-science-roadmap": ["ua-CiDNNj30", "uD8DfbJrqRI"],
  "ai-skills": ["i_LwzRVP7bg"],
  "frontend-roadmap": ["jS4aFq5-91M", "bMknfKXIFA8"],
  "backend-roadmap": ["Oe421EPjeBE"],
  "sql-learning": ["HXV3zeQKqGY"],
  "python-learning": ["rfscVS0vtbw"],
  "python-developer-to-ml": ["i_LwzRVP7bg"],
  "accounting-to-analytics": ["cnjhHZNJEDk"],
  "cybersecurity-entry": ["v7BNtpw53AA", "9HOpanT0GRs"],
  "cloud-roadmap": ["6eroP2XGtTI"],
  "devops-roadmap": ["1J2YOV6LcwY", "j5Zsa_eOXeY"],
  "ux-transition": ["c9Wg6Cb_YlU"],
  "product-entry": ["5nAeyqNuZYU"],
  "marketing-entry": ["kunkYTKFNtI", "h95cQkEWBx0"],
  "business-analyst-entry": ["UBVzucVpG7k", "YJucKlGa0ZE"],
  "resume-improvement": ["Tt08KmFfIYQ", "eGmZZFJ-8PY"],
  "fresher-no-experience": ["LcohcyoCXn8"],
  "behavioral-star": ["uQEuo7woEEk"],
  "interview-preparation": ["DHDrj0_bMQ0"],
  "tell-me-yourself": ["DHDrj0_bMQ0"],
  "system-design-prep": ["F2FmTdLtb_4"],
  "data-analyst-roadmap": ["YRJbhFLLPyE", "cnjhHZNJEDk"],
  "data-engineer-roadmap": ["PHsC_t0j1dU"],
  "ml-engineer-roadmap": ["PpiqSDMi4-4", "i_LwzRVP7bg"],
  "qa-automation-roadmap": ["sO8eGL6SFsA", "jydYq7oAtD8"],
  "mobile-developer-roadmap": ["VPvVD8t02U8"],
  "network-engineer-roadmap": ["qiQR5rTSshw"],
  "hr-career-roadmap": ["c8_avX9miag"],
  "javascript-learning": ["jS4aFq5-91M"],
  "react-learning": ["bMknfKXIFA8"],
  "git-learning": ["RGOj5yH7evk"],
  "linux-learning": ["ZtqBQ68cfJc"],
  "dsa-preparation": ["RBSGKlAvoiM"],
  "statistics-for-data": ["xxpc-HPKN28"],
  "excel-for-analysts": ["Vl0H-qTclOg"],
  "bi-tool-learning": ["FwjaHCVNBWA"],
  "docker-learning": ["fqMOX6JJhGo"],
  "hr-round-preparation": ["zIm_k9j0C50"],
};

const rows: Row[] = [
  ["career-discovery", "Which career is best for me?", ["How do I choose a career?", "I do not know what career to choose"], "career-guidance", "guidance", "There is no single best career independent of your interests, constraints, and the work you enjoy doing. Start by exploring the daily tasks, rather than choosing a title because it sounds impressive.\n\nTry this: list three activities you enjoy, two skills you can demonstrate, and any limits on location, study time, or income. Choose two possible roles and complete a small task from each: analyze a spreadsheet, build a simple page, interview a potential customer, or explain a financial statement. Compare how you felt about the actual work.\n\nWhat is your education, and which kinds of problems do you enjoy solving? With that context we can narrow the choices together.", ["occupations"], ["career", "choose", "interests", "direction"]],
  ["data-science-roadmap", "How can I become a Data Scientist?", ["How do I become a data scientist?", "What should I study to get a data science job?", "Give me a data science roadmap", "How do I get into data science?"], "data-science", "roadmap", "Start by learning to answer a useful question with data. You do not need to learn every machine-learning tool at once.\n\nRecommended roadmap\n1. Practice Python functions, collections, files, and debugging until you can clean a small dataset without copying a tutorial line by line.\n2. Learn SQL joins, grouping, and missing-value checks. Write queries that answer a business question and explain what each row represents.\n3. Study descriptive statistics, sampling, uncertainty, and experiments. These help you recognize when a convincing-looking result is misleading.\n4. Build a simple baseline model before a complex one. Keep evaluation data separate and investigate errors instead of reporting only a single accuracy number.\n5. Publish one end-to-end project with the question, data limitations, reproducible steps, and a plain-language conclusion.\n\nNext step: choose a small public dataset and write three questions you want to answer. What Python or statistics experience do you already have?", ["python", "sql", "ml"], ["data science", "data scientist", "roadmap", "python", "statistics"]],
  ["ai-skills", "What skills should I learn for AI jobs?", ["What should I learn to work in artificial intelligence?", "How do I start learning AI?"], "ai-ml", "roadmap", "First choose what kind of AI work interests you: building applications, training models, evaluating systems, or researching new methods. Those paths share foundations but need different depth.\n\nMy recommendation is to start with Python and basic software engineering, then SQL and practical statistics. Learn to evaluate a simple model on data it has not seen. For AI application work, add APIs, retrieval, test datasets, privacy controls, and failure handling. For model-development roles, spend more time on linear algebra, optimization, and experiments.\n\nBuild one modest application and document where it fails. A project that measures quality and acknowledges limits tells a stronger story than a demo that claims to solve everything. Which of these kinds of AI work appeals to you?", ["python", "ml"], ["AI", "artificial intelligence", "machine learning", "skills"]],
  ["after-bca", "What should I learn after BCA?", ["What can I do after a BCA degree?", "Career options after Bachelor of Computer Applications"], "education", "roadmap", "Use your BCA foundation to test a direction before committing to another qualification. A degree title alone does not determine the right next step.\n\nIf you enjoy building interfaces, practice HTML, CSS, JavaScript, accessibility, and a small complete web app. If you enjoy investigating numbers, start with SQL, spreadsheets, Python, and a short analysis project. If you enjoy systems, explore Linux, networking, and running a service reliably.\n\nCompare entry-level job descriptions in your target location and identify recurring skills you can actually demonstrate. Consider postgraduate study if its curriculum, eligibility, cost, and placement evidence fit a goal you can explain; check those details directly with the institution.\n\nNext step: choose one path for a short project, then review whether you enjoyed the work. Are you aiming for employment soon or considering further study?", ["web", "sql", "jobs"], ["BCA", "degree", "fresher", "education"]],
  ["interview-preparation", "How do I prepare for an interview?", ["Help me prepare for a job interview", "What is a good interview preparation plan?"], "interviews", "interview", "Prepare for the work the role involves, then practice explaining the evidence that you can do it. Memorizing answers often makes follow-up questions harder.\n\nStart with the job description. For each important responsibility, choose a project or work example. Prepare a short account of the situation, your responsibility, the actions you personally took, and the result. Keep your ownership and any numbers accurate.\n\nPractice one realistic task under a time limit, then explain your decisions aloud. Ask a friend to interrupt with questions about alternatives and mistakes. Finish by preparing questions about expectations, team support, and how success is assessed.\n\nWhich role are you interviewing for, and is the next round technical, behavioral, or a recruiter conversation?", [], ["interview", "prepare", "practice", "HR", "behavioral"]],
  ["certification-choice", "Which certifications are valuable?", ["How do I choose a certification?", "Are professional certifications worth it?"], "certifications", "certification", "A certification is worth considering when it closes a specific gap for your target work and you can afford the time and cost. Collecting badges without practical evidence can distract from your goal.\n\nReview several relevant job descriptions and note whether a credential is required, preferred, or absent. Compare the official syllabus with what you need to learn. Before paying, check the provider's current exam page for availability, prerequisites, fees, renewal rules, and the exact credential name.\n\nPair study with a small project that uses the skills. If employers in your target market do not mention the credential, the project and fundamentals may deserve priority.\n\nWhat role and country are you targeting? The provider catalogues below are places to verify details, not a blanket endorsement of every exam.", ["aws", "microsoft"], ["certification", "credential", "certificate", "valuable"]],
  ["resume-improvement", "How can I improve my resume?", ["How can I improve my CV?", "Help me write a better resume", "How do I make my resume stronger?"], "resume", "resume", "Make the resume easy to understand and honest about what you contributed. Begin with one target role so you can decide which evidence deserves the most space.\n\nFor each experience or project, explain the problem, your own action, and the result or scope. For example, describe the workflow you improved and how it was used. Add numbers only when you can substantiate them; a clear qualitative result is better than an invented percentage.\n\nUse recognizable section labels, consistent dates, and readable formatting. Check the employer's requested file format and inspect the exported document. Remove unsupported skills and wording you could not defend in an interview.\n\nNext step: choose one bullet that feels vague and tell me what you actually did. We can improve it without inventing achievements.", ["resume"], ["resume", "CV", "improve", "bullet", "writing"]],
  ["career-switch-risk", "How do I switch careers without quitting immediately?", ["Can I test a career change while employed?"], "career-switching", "roadmap", "Treat the transition as an experiment with a decision point. Keeping your current work while testing the new direction can help you learn what you enjoy and what preparation is missing.\n\nChoose a target role, speak with someone doing that work, and complete a representative task outside work using your own equipment and public data. Set a manageable weekly study commitment and a date to review evidence: did you finish the project, enjoy the task, and find plausible roles?\n\nMap transferable skills explicitly. Customer conversations may help in product work; reconciliation experience may help in analytics. Do not present those overlaps as experience you have not gained. Before leaving a job, make your financial and personal constraints part of the decision.", ["occupations"], ["switch", "transition", "career change", "employed"]],
  ["accounting-to-analytics", "How can I move from accounting into data analytics?", ["I am an accountant and want to become a data analyst"], "career-switching", "roadmap", "Use accounting knowledge as the context for your first analytics project. You already have a domain in which useful questions can be concrete; the task is to demonstrate an analytical workflow without overstating your technical experience.\n\nStart with SQL and spreadsheet data cleaning. Build a small synthetic receivables dataset, define ageing rules, reconcile the totals, and explain exceptions. Add a dashboard only after the underlying definitions are clear. Then introduce Python to automate a repetitive cleaning or validation step.\n\nWrite a case study that explains the question, checks, assumptions, and decision the analysis could inform. Use synthetic or approved public data, never confidential employer records. Look for roles where your accounting context is relevant and compare their actual requirements.", ["sql", "python"], ["accounting", "accountant", "data analytics", "switch"]],
  ["python-developer-to-ml", "How should an experienced Python developer move into machine learning?", ["I already know Python; how do I learn machine learning?"], "ai-ml", "roadmap", "You can probably spend less time on language basics, but do not skip the reasoning behind experiments. The biggest shift is from making code run correctly to deciding whether the result generalizes.\n\nPractice dataset splitting, leakage detection, baseline models, and selecting a metric that reflects the problem. Compare errors across meaningful groups and explain limitations. Build a reproducible training pipeline with tests for data assumptions, then package inference behind a small service.\n\nUse your engineering experience to show reliable delivery, but be explicit about which statistical concepts are new to you. For your first project, choose a simple model you can explain rather than a complex one you cannot evaluate.", ["ml"], ["Python developer", "machine learning", "experienced"]],
  ["frontend-roadmap", "How do I become a frontend developer?", ["What should I study for frontend jobs?", "How do I learn front end development?"], "software-engineering", "roadmap", "Start by building pages that work with ordinary browser features. Learn semantic HTML, responsive CSS, JavaScript functions and events, and how to debug requests in browser tools.\n\nBuild a small form-driven app with loading, empty, error, and success states. Test keyboard navigation and different screen sizes. Then learn a framework used in the roles you are targeting, and rebuild part of the app while explaining what the framework simplifies.\n\nAdd tests for important user actions and document setup. Your next milestone is an app another person can use and understand, not a long list of libraries on a resume.", ["web", "access"], ["frontend", "front end", "HTML", "JavaScript", "React"]],
  ["backend-roadmap", "How do I become a backend developer?", ["What should I learn for backend development?"], "software-engineering", "roadmap", "Pick one language and learn to build a small service from request to database response. Practice data structures, debugging, HTTP, SQL, and basic automated testing before adding several infrastructure tools.\n\nBuild a task or booking API with validation, authorization, database constraints, and clear error responses. Test that one account cannot access another account's records. Add logs that help explain failures without recording secrets.\n\nDocument the data model and an example request. Then deploy to a controlled environment and practice restoring from a backup. This gives you concrete decisions and tradeoffs to discuss in an interview.", ["sql", "python"], ["backend", "API", "server", "developer"]],
  ["fullstack-scope", "Should I learn frontend and backend at the same time?", ["How do I avoid getting overwhelmed learning full stack?"], "software-engineering", "guidance", "Learn enough of both to complete a small vertical slice, then deepen one side at a time. Trying to master every framework at once makes progress difficult to assess.\n\nFor example, build a form that saves a record and shows it back to the user. Learn the interface, request, validation, and database steps involved. Once that works, improve one concern such as accessibility or authorization rather than restarting with another stack.\n\nKeep a list of topics you are deliberately postponing. Choose your next topic based on a problem in the project or a recurring requirement in target roles.", ["web", "sql"], ["full stack", "frontend", "backend", "overwhelmed"]],
  ["sql-learning", "How should I practice SQL for a data job?", ["What is a practical SQL study plan?"], "data-science", "roadmap", "Practice translating questions into queries, then checking whether the result means what you think it means. Syntax alone is not enough.\n\nUse related tables such as orders, customers, and payments. Start with filters and grouping, then joins. Before running a join, predict how many rows it should produce and check for duplicates. Practice missing values, dates, and window functions after these foundations are comfortable.\n\nKeep a short explanation alongside each query: the unit of analysis, assumptions, and a manual check on a few rows. In interviews, explaining those checks can be as useful as writing the query quickly.", ["sql"], ["SQL", "queries", "joins", "practice"]],
  ["python-learning", "How should a beginner learn Python?", ["How do I start programming in Python?"], "skill-development", "roadmap", "Choose a small problem you understand and use it to practice the fundamentals. A personal expense summary or file organizer is a useful starting point.\n\nWork through variables, conditions, loops, functions, collections, and files. After each topic, change the example without looking at the solution. Practice reading error messages and inspecting intermediate values. Learn classes when you encounter a problem that benefits from grouping state and behavior.\n\nKeep your first project small enough to finish. You are ready to move on when you can explain the code, fix a mistake, and add a modest feature yourself.", ["python"], ["Python", "beginner", "programming", "fundamentals"]],
  ["ml-data-leakage", "How do I explain data leakage in a machine learning interview?", ["How can I demonstrate that my ML project avoids leakage?"], "technical-interviews", "interview", "Explain leakage as information reaching training or model selection that would not legitimately be available at prediction time. Then use an example from a project you understand.\n\nA useful practice example is fitting preprocessing on the whole dataset before splitting it. Describe how you would instead fit learned transformations on training data and apply them to validation data. For time-based predictions, explain why a random split may not reflect the future task.\n\nShow a check in your project and describe what changed when you corrected the process. Avoid presenting an improved evaluation procedure as proof that the model is ready for every real-world use.", ["ml"], ["leakage", "machine learning", "evaluation", "interview"]],
  ["data-portfolio", "What should I include in a data science portfolio?", ["How do I build a useful data science project portfolio?"], "portfolio", "portfolio", "Include projects that make your reasoning visible. A notebook with many models is difficult to assess if the question and evaluation are unclear.\n\nFor one project, show the decision you want to inform, the data source and permissions, cleaning checks, a simple baseline, evaluation choices, and limitations. Include instructions to reproduce the result and a short explanation for a nontechnical reader.\n\nChoose a second project only if it adds different evidence, such as SQL analysis or deployment. Remove confidential data and credentials before publishing. A smaller portfolio you can defend is a sensible goal.", ["ml", "sql"], ["data science", "portfolio", "projects"]],
  ["cybersecurity-entry", "How do I start a cybersecurity career?", ["What should I learn to work in cybersecurity?"], "cybersecurity", "roadmap", "Begin with how systems normally work: networking, operating systems, identity, and logs. Security tools are easier to understand when you can explain what they observe or protect.\n\nExplore different work such as monitoring, application security, governance, and incident response before choosing a path. Practice only in systems you own or are explicitly authorized to test. Build a small lab, document an event, explain the evidence, and recommend a proportionate fix.\n\nUse work-role descriptions to identify a narrow learning goal. A certificate can structure study, but first compare its current syllabus with the tasks you want to perform.", ["security"], ["cybersecurity", "security", "beginner", "SOC"]],
  ["security-portfolio", "How can I build a cybersecurity portfolio safely?", ["What can I publish from a security home lab?"], "cybersecurity", "portfolio", "Publish evidence of your investigation and judgment using a deliberately controlled lab. Do not scan or test real organizations without written authorization.\n\nDocument the lab's scope, a simulated event, the logs you examined, competing explanations, and the mitigation you tested. Remove secrets, identifiers, and anything belonging to another person. Explain what your lab does not represent about production environments.\n\nFor an entry-level portfolio, a clear incident timeline or an application-security fix with a regression test can be more informative than screenshots of tools alone.", ["security"], ["cybersecurity", "portfolio", "lab", "authorization"]],
  ["cloud-roadmap", "How do I prepare for cloud engineering roles?", ["What should I learn for a cloud engineer job?"], "cloud", "roadmap", "Start with networking, Linux, identity, and the lifecycle of a small application. Choose one cloud provider for practice rather than trying to collect vocabulary across every platform.\n\nDeploy a small service with limited permissions, configuration outside source code, basic monitoring, and a documented teardown. Set spending alerts and understand which resources remain chargeable when the application is idle. Practice a failed deployment and recovery.\n\nUse a provider's current learning material to fill gaps, then compare your project with actual job responsibilities. Check certification details directly with the provider before paying.", ["aws", "microsoft"], ["cloud", "AWS", "Azure", "engineering"]],
  ["devops-roadmap", "What should I learn to become a DevOps engineer?", ["How do I prepare for DevOps jobs?"], "devops", "roadmap", "Focus on making a small service repeatable and observable. Start with Linux, networking, Git, scripting, and how the application is built and tested.\n\nCreate a pipeline that tests a change and deploys it to a practice environment. Add configuration management, a rollback procedure, and useful logs or metrics. Introduce containers when you can explain the packaging problem they solve; study orchestration after running a simple deployment reliably.\n\nWrite a short incident report after intentionally breaking your practice service. Explain detection, impact, recovery, and one prevention step. This shows operational reasoning beyond naming tools.", [], ["DevOps", "CI/CD", "Linux", "deployment", "Docker"]],
  ["ux-transition", "How can I start a career in UX design?", ["What should I learn to become a UX designer?"], "ui-ux", "roadmap", "Start by understanding a user's task and observing where it becomes difficult. Visual polish matters, but it does not replace evidence about whether a design helps someone complete that task.\n\nChoose a small workflow, ask willing participants about their experience, sketch alternatives, and test a simple prototype. Record what changed after feedback and why. Include accessibility considerations from the beginning.\n\nBuild a case study around the problem, constraints, decisions, and limitations. If you used a fictional brief, label it clearly. Do not invent users, research findings, or business results to make the story appear stronger.", ["access"], ["UX", "design", "user research", "prototype"]],
  ["ux-case-study", "How do I write a UX case study without real clients?", ["Can a personal UX project be used in a portfolio?"], "ui-ux", "portfolio", "Use a self-initiated project and label it honestly. The goal is to show how you investigated a problem and changed the design, not to imply you were hired by a brand.\n\nDefine a narrow task and explain your assumptions. Test a prototype with consenting participants where practical, report the actual scope, and distinguish observations from hypotheses. Include a before-and-after decision with the reason for the change.\n\nAvoid invented conversion improvements or research quotes. End with what you would test next and what remained uncertain. That makes the work easier to discuss critically.", ["access"], ["UX", "case study", "portfolio", "clients"]],
  ["product-entry", "How can I move into product management?", ["What should I learn for a product manager role?"], "product-management", "roadmap", "Practice connecting a user problem to a measurable decision. Product work is easier to demonstrate through an investigation and a tradeoff than through a long feature list.\n\nChoose a workflow you understand. Describe the user, their difficulty, the evidence available, and several possible responses. Decide what you would test first and what result would change your mind. Include constraints such as engineering effort, accessibility, and business priorities.\n\nUse experience from support, engineering, operations, or another field as evidence of relevant work, while being precise about your ownership. Compare target roles carefully because product responsibilities vary by organization.", ["product"], ["product manager", "product management", "transition"]],
  ["marketing-entry", "How do I start learning digital marketing?", ["What skills should I learn for digital marketing jobs?"], "digital-marketing", "roadmap", "Choose one audience, one useful offer, and one channel to practice. Learning every advertising platform at once makes it hard to understand why a campaign works or fails.\n\nWrite a clear message, create a simple landing page or content piece, and decide what action you want someone to take. Learn basic analytics so you can separate visits from meaningful outcomes. For organic search, study the official guidance and improve content usefulness and discoverability.\n\nDocument your hypothesis and what you observed. Do not invent campaign results or promise rankings. Use a small controlled exercise before spending significant money on ads.", ["seo"], ["digital marketing", "SEO", "marketing", "analytics"]],
  ["finance-career-choice", "How do I choose between different finance careers?", ["Which finance career should I explore?"], "finance", "guidance", "Compare the work itself: analyzing a business, maintaining accurate records, managing risk, serving clients, or supporting internal decisions. These interests can point toward quite different roles.\n\nPick two roles and review their daily responsibilities, qualification requirements, and entry routes in your location. Try a representative exercise such as explaining a financial statement or comparing assumptions in a simple forecast. Ask a practitioner what junior staff actually spend time doing.\n\nDo not commit to an expensive qualification based only on the title's prestige. Confirm current recognition and eligibility with the relevant professional body and employers.", ["occupations"], ["finance", "accounting", "career choice"]],
  ["degree-or-projects", "Should I get another degree or focus on projects?", ["How do I decide between postgraduate study and work experience?"], "education", "guidance", "Start with the gap you need to close. Another degree may provide structured study or access to a particular route, while projects can help demonstrate practical ability. Neither is automatically the right next step.\n\nCompare the target role's actual requirements with your current evidence. For a programme, examine curriculum, assessment, cost, time, recognition, and independently checkable outcomes. For a project route, identify how you will get feedback and demonstrate progress.\n\nWrite down what would be different after each option. If you cannot explain the benefit beyond feeling more qualified, test the field with a small project or conversation before committing.", [], ["degree", "postgraduate", "projects", "education"]],
  ["internship-search", "How do I find my first internship?", ["How can a fresher get an internship without experience?"], "internships", "guidance", "Use a small piece of relevant work to make your application concrete. You do not need to describe a student project as professional experience.\n\nChoose a target role, prepare a concise resume, and build or document one task related to that role. Search official employer pages and credible career portals, then check the organization and application destination. Keep a record of the role, contact, date, and next action.\n\nAsk about supervision, duties, duration, and any payment terms before accepting. Be cautious about requests to pay for a promised job. A useful internship should give you a clear understanding of the work and support available.", ["jobs"], ["internship", "fresher", "first experience"]],
  ["fresher-no-experience", "What can I put on a resume if I have no work experience?", ["How does a fresher write a resume without employment history?"], "fresher-jobs", "resume", "Use projects, coursework, volunteering, and responsibilities that provide relevant evidence. Clearly label each category so the reader can distinguish study from employment.\n\nChoose an example where you made a decision or produced something useful. Explain the task, what you personally did, the tools used, and the result or deliverable. Include a link only if it works and is safe to share.\n\nDo not fill the page with unsupported claims such as expert or excellent communicator. A short explanation of a presentation, team task, or project makes the claim more concrete. Tailor the order to the role you are applying for.", ["resume"], ["fresher", "resume", "no experience", "student"]],
  ["ats-format", "How do I make my resume ATS friendly?", ["How should I optimize my CV for an applicant tracking system?"], "ats", "resume", "Aim for a document that is straightforward to read and extract. There is no universal ATS score that guarantees an interview, and employers use different systems and workflows.\n\nFollow the employer's file-format instructions. Use familiar section headings and place important information in ordinary text. Export the document, copy its text into a plain editor, and check that names, dates, and bullets remain in a sensible order.\n\nUse relevant terminology from the job description only when it accurately describes your experience. Avoid hidden text, repeated keywords, or claims you cannot explain. Treat automated feedback as a prompt for inspection rather than proof that your resume will pass a filter.", [], ["ATS", "resume", "parsing", "format", "keywords"]],
  ["resume-no-metrics", "How do I write achievement bullets when I have no metrics?", ["Can my resume be strong without percentages?"], "resume", "resume", "Describe a real change, deliverable, or responsibility with enough context to understand it. A number is useful only if you can explain where it came from.\n\nFor example, explain which manual step you automated, which people used a tool, or what issue you resolved. Separate what you owned from what the team accomplished. If a result was not measured, say what was delivered rather than inventing an improvement.\n\nYou can also identify evidence you could collect responsibly in future, such as approved task counts or documented feedback. Do not reconstruct confidential or uncertain figures merely to make a bullet sound impressive.", [], ["resume", "metrics", "percentage", "achievements"]],
  ["resume-gap", "How should I explain an employment gap on my resume?", ["How do I talk about a career break?"], "resume", "resume", "Give a brief, accurate explanation at the level of detail you are comfortable sharing. You do not need to turn private circumstances into a long story.\n\nKeep dates consistent. If you did relevant study, volunteering, or projects, describe the actual activities without presenting the whole break as employment. In an interview, acknowledge the gap, explain your readiness now, and bring the discussion back to evidence for the role.\n\nIf you are returning after time away, choose one practical refresher task and ask for feedback. That gives you something current to discuss without disguising your history.", [], ["resume", "employment gap", "career break", "return"]],
  ["cover-letter-purpose", "What should a good cover letter include?", ["How do I write a cover letter that is not generic?"], "resume", "resume", "Use the letter to connect a small number of relevant examples to the role. It should add context rather than repeat every line of the resume.\n\nExplain why the work interests you using something specific you verified about the role. Then choose an example showing a related skill or decision and make your contribution clear. Close with a simple expression of interest in discussing the position.\n\nKeep it concise and factual. Check the organization and role names carefully, and do not claim familiarity with a company's culture based on assumptions.", ["resume"], ["cover letter", "application", "writing"]],
  ["linkedin-profile", "How can I improve my LinkedIn profile for a job search?", ["What should my LinkedIn headline say?"], "linkedin", "guidance", "Make it easy to understand the work you are pursuing and the evidence you bring. Write a headline that names your direction and genuine skills instead of stacking broad labels.\n\nUse the About section to explain your background, target work, and a relevant example. Keep experience dates consistent with your resume. Add selected work you can discuss, with confidential material removed.\n\nBefore changing visibility or contact settings, review what you want others to see. A clear profile supports conversations; it does not replace targeted applications and useful professional relationships.", [], ["LinkedIn", "headline", "profile", "networking"]],
  ["networking-intro", "How do I network when I do not know anyone in my field?", ["How can I ask someone for career advice without being awkward?"], "networking", "guidance", "Begin with a small, specific request for perspective. You are more likely to have a useful conversation when you have already done some basic research.\n\nExplain the direction you are exploring and ask about one concrete issue, such as a typical junior task or a skill that is difficult to learn from courses. Make it easy to decline and respect the person's time.\n\nAfter a conversation, act on something useful and thank them. Avoid immediately asking a stranger to endorse abilities they have not seen. A relationship can grow from thoughtful follow-through rather than repeated requests for a referral.", [], ["networking", "connections", "informational interview"]],
  ["referral-request", "How should I ask for a job referral?", ["What information should I send when requesting a referral?"], "networking", "guidance", "First check that the role fits your background and that the person is comfortable helping. A referral request should give them enough information to make an honest decision.\n\nSend the specific role link, a concise description of your relevant experience, and a current resume. If they have not worked with you, acknowledge that rather than asking them to vouch for skills they cannot assess.\n\nKeep the request brief and accept a no or no response gracefully. Continue using the normal application route where appropriate; a referral is not a promise of an interview.", [], ["referral", "networking", "request"]],
  ["technical-interview-stuck", "What should I do when I get stuck in a coding interview?", ["How do I recover when I cannot solve an interview problem?"], "technical-interviews", "interview", "Make your reasoning visible and reduce the problem to something you can test. Silence and random changes make it difficult for the interviewer to understand where you need help.\n\nRestate the requirement, confirm an example, and describe a straightforward approach even if it is not optimal. Check a small input manually. Explain the specific uncertainty and ask a focused question or hint if needed.\n\nIf you find a bug, walk through why it happened and how you would test the fix. Do not pretend a solution works when you have not checked it. Practice this recovery process, not only solving familiar problems quickly.", [], ["coding interview", "stuck", "problem solving"]],
  ["system-design-prep", "How should I prepare for a system design interview?", ["What is a practical system design interview study plan?"], "technical-interviews", "interview", "Practice making assumptions explicit before drawing components. Start by asking what users need, which operations matter, and what constraints the interviewer wants you to consider.\n\nSketch a simple design, then examine a few concrete failure modes: duplicate requests, unavailable dependencies, slow queries, or unauthorized access. Explain a tradeoff before adding a cache, queue, or replica.\n\nUse one familiar application and revisit it with different constraints. The goal is to reason about behavior and tradeoffs, not to recite an architecture that fits every problem.", [], ["system design", "interview", "architecture", "tradeoffs"]],
  ["behavioral-star", "How do I structure a behavioral interview answer?", ["How do I use STAR without sounding scripted?"], "hr-interviews", "interview", "Use situation, task, action, and result as a checklist rather than a speech to memorize. The listener needs enough context to understand what you did and why.\n\nKeep the setup short, explain your responsibility, and spend most of the answer on your actions and decisions. State the outcome accurately, including limits or an unexpected result. Add what you learned when it is relevant.\n\nPractice with follow-up questions about alternatives and your personal contribution. If an example was a team effort, acknowledge others and be precise about your part.", [], ["STAR", "behavioral", "HR interview", "story"]],
  ["tell-me-yourself", "How should I answer tell me about yourself?", ["How do I introduce myself in an interview?"], "hr-interviews", "interview", "Give a short professional introduction that helps the interviewer understand your fit for this conversation. You do not need to narrate your whole life.\n\nExplain your current background, one or two relevant examples, and what kind of work you want to do next. A fresher can use a project or coursework; an experienced applicant can use a responsibility or recent outcome.\n\nPractice until the order feels natural, but leave room to adapt. Avoid claims such as expert or passionate unless the examples make their meaning clear.", [], ["tell me about yourself", "introduction", "interview"]],
  ["weakness-interview", "How do I answer an interview question about weaknesses?", ["What weakness should I discuss in an HR interview?"], "hr-interviews", "interview", "Choose a genuine, manageable development area and explain what you are doing about it. A disguised boast rarely helps the interviewer understand your self-awareness.\n\nDescribe a specific situation where the gap mattered, the action you took, and how you assess progress. For example, if presenting was difficult, explain the preparation and feedback routine you now use. Do not invent a weakness or a story.\n\nKeep the answer proportionate and work-related. You can discuss improvement honestly without disclosing private matters unrelated to the role.", [], ["weakness", "HR", "interview", "self awareness"]],
  ["interview-questions-employer", "What questions should I ask the interviewer?", ["What should I ask at the end of a job interview?"], "interviews", "interview", "Ask questions that help you understand the work and whether the environment fits your needs. Choose a few that have not already been answered.\n\nUseful topics include the first problems the new person will work on, how success is assessed, how feedback is given, and what support is available while learning. Ask for a concrete example when an answer is vague.\n\nAdapt the questions to the person: a recruiter may clarify the process, while a future teammate can describe collaboration. Keep notes so you can compare opportunities using evidence rather than impressions alone.", [], ["interviewer questions", "interview", "team", "expectations"]],
  ["interview-rejection", "How do I learn from a rejected job interview?", ["What should I do after interview rejection?"], "job-search", "interview", "Separate what you know from what you are guessing. A rejection alone does not tell you whether the issue was skill, role fit, timing, or another applicant's evidence.\n\nWrite down the questions, where your examples were weak, and any feedback actually provided. Choose one improvement you can practice, such as explaining a project or checking edge cases. If appropriate, ask politely for feedback once.\n\nTrack patterns across several conversations instead of rebuilding your entire plan after one result. Continue applying while you improve a specific gap.", [], ["rejection", "interview", "feedback"]],
  ["negotiation-preparation", "How should I prepare to negotiate a job offer?", ["How do I approach salary negotiation professionally?"], "salary-negotiation", "current-facts", "Prepare your priorities and the evidence behind your request before responding. Consider the whole offer: responsibilities, fixed and variable compensation, benefits, location, learning, and any conditions you need clarified.\n\nUse current, location- and role-specific information from sources you can assess. Do not treat a broad online average as a promise about your situation, and never invent a competing offer. Ask whether there is flexibility and make a reasoned request.\n\nRequest the final terms in writing and take time to understand them. If you share the role, location, experience level, and offer components without personal identifiers, we can organize the comparison; I will not guess a market salary.", [], ["salary negotiation", "offer", "compensation"]],
  ["job-search-routine", "How do I organize my job search?", ["What should my weekly job search plan look like?"], "job-search", "guidance", "Build a routine around actions you can control and evidence you can review. Applying to many unrelated roles can make it difficult to understand why the search is not progressing.\n\nSet aside time for finding suitable roles, tailoring applications, practicing a relevant skill, and following up where appropriate. Track the role, source, date, requirements, status, and next action. Review whether applications are turning into conversations and where the process slows down.\n\nAdjust one part at a time. If suitable applications receive no response, inspect the evidence and clarity of your resume before simply increasing volume. Choose a pace that leaves time to learn and recover.", ["jobs"], ["job search", "routine", "applications", "tracking"]],
  ["job-scam-check", "How do I check whether a job offer is genuine?", ["How can I spot a fake recruiter or job scam?"], "job-search", "guidance", "Verify the organization and the opportunity through a channel you locate independently. A polished message or a familiar logo is not enough.\n\nCheck the role on the employer's official career site where possible, examine the sender's domain carefully, and contact the organization through its published details if uncertain. Be cautious about demands for payment, pressure to act immediately, or requests for sensitive documents before a clear process exists.\n\nDo not open unusual attachments or send bank details just to secure an interview. Keep records and pause when details cannot be verified. I can help you examine a redacted message, but cannot certify an offer as genuine from its wording alone.", ["jobs"], ["job scam", "fake recruiter", "offer", "verification"]],
  ["remote-readiness", "How do I prepare for a remote job?", ["What skills help someone work remotely?"], "remote-jobs", "roadmap", "Demonstrate that you can make progress visible without relying on constant meetings. Remote work preparation includes communication and reliability as well as the role's technical skills.\n\nPractice writing a short update that states the outcome, what changed, any blocker, and the decision needed. Keep documentation and handoffs clear. Build a routine for focused work, availability, and asking for help early.\n\nBefore accepting a role, clarify time-zone expectations, equipment, security practices, and whether the employer can hire in your location. Do not assume remote means work from any country.", [], ["remote", "work from home", "communication", "time zone"]],
  ["freelance-first-client", "How can I get my first freelance client?", ["How do I start freelancing without client experience?"], "freelancing", "guidance", "Offer a narrow service you can deliver reliably and show a relevant sample. A clear small outcome is easier to discuss than a claim that you can do everything.\n\nDefine the deliverable, required inputs, scope, timeline, revision process, and acceptance criteria. Use a personal sample honestly labeled as such if you have no client work. Ask questions before quoting, and record agreed terms through an appropriate written process.\n\nDo not use confidential work as a sample without permission. Start with a manageable engagement and review what you learned about estimation and communication before expanding the service.", [], ["freelance", "client", "scope", "first project"]],
  ["freelance-scope-creep", "How do I handle scope creep on a freelance project?", ["What should I do when a client keeps adding work?"], "freelancing", "guidance", "Make the change visible before agreeing to absorb it. A calm discussion about deliverables is usually more useful than allowing frustration to build.\n\nCompare the request with the agreed scope and explain the effect on effort, schedule, or other deliverables. Offer a choice: replace an existing item, schedule a separate phase, or agree revised terms. Record the decision before proceeding.\n\nFor future work, define what completion means and how changes are requested. If the disagreement involves contractual rights or payment enforcement, use qualified local advice rather than assuming a general rule applies.", [], ["freelance", "scope creep", "client changes"]],
  ["international-career-plan", "How should I plan an international job search?", ["How do I prepare to apply for jobs abroad?"], "international-careers", "guidance", "Choose a target country and role before comparing pathways. Work authorization, qualification recognition, hiring practices, and costs can differ substantially, so a generic move-abroad checklist is not enough.\n\nResearch employers that hire for your work and verify any sponsorship or eligibility details through official employer and government sources. Adapt your application format using local guidance and prepare evidence of your experience that can be checked.\n\nBudget for uncertainty and avoid paying an intermediary based on a promised visa or job. Tell me the country and role you are considering so the next discussion can focus on facts that can be verified.", [], ["international", "abroad", "country", "relocation"]],
  ["communication-technical", "How can I explain technical work to nontechnical people?", ["How do I improve communication with business stakeholders?"], "communication", "guidance", "Begin with the decision or outcome the listener cares about. Explain enough technical detail to help them act, and add more only when it changes the choice.\n\nTry this order: the problem, the impact, the available options, and your recommendation with its uncertainty. Replace internal terminology with a concrete example. Ask the listener to summarize the decision so you can check whether your explanation worked.\n\nPractice with a real project update and ask someone outside your specialty what was unclear. Improving one explanation from feedback is more useful than memorizing presentation phrases.", [], ["communication", "nontechnical", "stakeholder", "explain"]],
  ["workplace-feedback", "How do I ask my manager for useful feedback?", ["How can I get actionable feedback at work?"], "workplace-skills", "guidance", "Ask about a specific piece of work and the standard you are trying to meet. Broad questions such as whether you are doing well often produce broad answers.\n\nShare a recent example and ask what you should continue, change, or practice next. Request an observable example if the feedback uses a vague label. Agree on one action and a time to review whether it helped.\n\nListen before defending the work, but clarify facts when necessary. Feedback is information to evaluate; it does not require accepting every interpretation without discussion.", [], ["manager", "feedback", "workplace", "development"]],
  ["promotion-evidence", "How do I prepare a case for promotion?", ["What evidence should I collect before a promotion discussion?"], "promotions", "guidance", "Understand the expectations for the next level and collect examples against them. Working hard matters, but the decision needs evidence of the responsibilities you are ready to handle.\n\nDiscuss the criteria with your manager. Keep a record of relevant outcomes, decisions, collaboration, and feedback, while distinguishing your contribution from the team's. Look for gaps and agree on an opportunity to demonstrate the missing responsibility.\n\nAsk about the process and timing without assuming a particular outcome. If expectations keep changing, document the agreed criteria and revisit them calmly.", [], ["promotion", "career growth", "evidence", "level"]],
  ["first-leadership-role", "How do I prepare for my first team lead role?", ["What should a new team lead focus on?"], "leadership", "roadmap", "Start by learning how the team works and what support each person needs. Being the strongest individual contributor does not automatically tell you how to coordinate other people's work.\n\nClarify goals, responsibilities, decision ownership, and how blockers are raised. Practice delegating an outcome with context and an agreed check-in, rather than prescribing every step or disappearing entirely. Give specific feedback privately and recognize contributions accurately.\n\nKeep room for your own learning. Ask your manager how your responsibilities differ from those of a people manager and where decisions need escalation.", [], ["team lead", "leadership", "delegation", "manager"]],
  ["learning-consistency", "How do I stay consistent while learning after work?", ["How do I make a realistic study plan with a full time job?"], "skill-development", "guidance", "Design a plan you can repeat during an ordinary week, not only when you feel motivated. Choose a small outcome and protect a manageable block of time.\n\nCombine short practice sessions with one slightly longer session to connect the pieces. End each session by writing the next small action so restarting is easier. Use a project or exercise to check understanding instead of counting only videos watched.\n\nReview the plan when work or personal demands change. Reducing scope is often more sustainable than treating a missed session as failure. What amount of time can you realistically protect each week?", [], ["study plan", "consistency", "after work", "learning"]],
  ["tutorial-dependence", "How do I stop depending on tutorials when coding?", ["How do I escape tutorial hell?"], "skill-development", "guidance", "Change the task after following an example. The useful test is whether you can explain and adapt the code when the instructions no longer match.\n\nRebuild a small feature from memory, then add a requirement the tutorial did not cover. When stuck, write down what you expected, what happened, and a small experiment to isolate the cause. Use documentation for the specific gap instead of restarting the whole course.\n\nKeep a brief record of mistakes and fixes. Finish a modest independent project before choosing another course that covers the same foundations.", ["web"], ["tutorial hell", "coding", "independent", "practice"]],
  ["ai-career-uncertainty", "Will AI replace my career?", ["How should I plan my career when AI tools keep changing?"], "future-trends", "guidance", "I cannot reliably predict whether your particular role will disappear. It is more useful to examine which tasks are changing and what evidence you can gather about your own field.\n\nList the tasks you do, test where approved AI tools help, and identify what still needs judgment, domain understanding, communication, or accountability. Learn to check outputs rather than trusting fluent responses.\n\nBuild adaptable foundations and review real job descriptions over time. Avoid making an expensive career decision based on a dramatic forecast or a single headline. Which role or task are you most concerned about?", [], ["AI replace", "future", "automation", "uncertainty"]],
  ["portfolio-confidentiality", "How can I show work in my portfolio when it is confidential?", ["What can I share from an employer project?"], "portfolio", "portfolio", "Get permission before sharing employer or client material. Removing a logo may still leave sensitive information in screenshots, data, code, or the description.\n\nIf sharing is not allowed, create a separate demonstration using synthetic data and your own implementation. Explain the type of problem and your responsibilities at an approved level of detail. Label a recreated example clearly so it is not mistaken for the original work.\n\nFor an interview, prepare a discussion of decisions and tradeoffs that does not disclose protected details. When uncertain, ask the owner of the information rather than guessing what is safe to publish.", [], ["portfolio", "confidential", "NDA", "employer work"]],
  ["accessibility-career", "How can I demonstrate accessibility skills as a developer?", ["What accessibility work should I put in my portfolio?"], "software-engineering", "portfolio", "Choose a complete user task and show how you made it usable with different interaction methods. A tool score alone does not explain the experience.\n\nFor example, build a form with labels, clear errors, visible focus, and sensible keyboard order. Test it without a mouse and document the problems you found. Use authoritative accessibility guidance to understand the patterns, and seek feedback from users when you can do so respectfully.\n\nPublish the changes and the tests you performed, including limitations. Describe your actual scope rather than claiming the whole product is accessible after a single automated check.", ["access"], ["accessibility", "developer", "portfolio", "keyboard"]],
  ["business-analyst-entry", "How do I prepare for a business analyst role?", ["What should I learn to become a business analyst?"], "business", "roadmap", "Practice turning an unclear business request into an understandable problem, process, and set of decisions. Begin with interviewing, process mapping, basic data analysis, and clear writing.\n\nChoose a familiar workflow and document who uses it, where delays or mistakes occur, and what evidence would confirm the problem. Write a small set of requirements with examples of acceptable behavior. Check them with someone who understands the workflow.\n\nAdd SQL or a reporting tool when it helps investigate the question. Your portfolio should show how you clarified uncertainty, not only polished diagrams.", ["sql"], ["business analyst", "requirements", "process"]],
  ["internship-to-offer", "How can I make the most of an internship?", ["What should I focus on during my first internship?"], "internships", "guidance", "Agree on what a useful outcome looks like and ask how to get feedback. An internship is an opportunity to learn how work is done, not a reason to hide every uncertainty.\n\nKeep brief notes on tasks, decisions, and questions. Attempt a sensible first step before asking for help, then explain what you tried. Share progress early enough that someone can correct the direction.\n\nNear the end, summarize your actual contributions and ask what you should improve next. If you are interested in a continuing role, ask about the process directly without assuming a good experience guarantees an offer.", [], ["internship", "feedback", "return offer", "learning"]],
  ["job-description-gaps", "Should I apply if I do not meet every job requirement?", ["Can I apply when I am missing some listed skills?"], "job-search", "guidance", "Read the wording carefully and distinguish required credentials or conditions from preferences. Do not assume every line has equal weight, but do not ignore an explicit eligibility condition.\n\nCompare the central responsibilities with evidence you already have. If the main work is a reasonable fit and the gaps are learnable, an honest application may be worthwhile. Explain related experience and what you are doing to close a gap without claiming proficiency you do not have.\n\nIf an essential condition is unclear, seek clarification through the employer's normal channel. Focus your effort on roles where you can explain a credible fit.", [], ["job description", "requirements", "missing skills", "apply"]],
  ["career-confidence", "How do I handle feeling behind in my career?", ["Everyone seems ahead of me professionally; what should I do?"], "career-guidance", "guidance", "Comparison often hides differences in opportunity, responsibilities, and personal constraints. It can help to replace a broad judgment about being behind with a specific next decision.\n\nWrite down what you want to change: the kind of work, income stability, confidence in a skill, or time outside work. Choose one action you can complete and assess, such as finishing a small project or asking for feedback on a resume.\n\nUse your own progress and circumstances as context. If the feeling is persistently affecting your wellbeing, consider support from someone you trust or a qualified professional alongside career planning.", [], ["behind", "confidence", "comparison", "career"]],
];

export const expansionRows: Row[] = [
  ...techRoleRows,
  ...dataAiRows,
  ...opsSecurityQaRows,
  ...businessRoleRows,
  ...comparisonRows,
  ...preparationRows,
];

export const seedEntries: KnowledgeEntry[] = [
  ...toEntries([
    ...rows,
    ...roleRows,
    ...skillRows,
    ...educationRows,
    ...jobSearchRows,
    ...interviewRows,
    ...workplaceRows,
  ]).map(entry => {
    const videos = videoAttachments[entry.id];
    if (!videos) return entry;
    return {...entry, youtube_resources: videos.map(id => { const video = videoById(id); if (!video) throw new Error(`Unknown video ${id} for ${entry.id}`); return videoSource(video); })};
  }),
  ...toEntries(expansionRows, expansionReviewNote),
];
for (const id of Object.keys(videoAttachments)) if (!seedEntries.some(entry => entry.id === id)) throw new Error(`Video attachment for unknown entry ${id}`);
const dataRoadmap = seedEntries.find(entry => entry.id === "data-science-roadmap")!;
dataRoadmap.variants = {
  entry: "For an entry-level starting point, prioritize a complete small SQL and Python analysis before advanced modeling. You can use coursework or a personal project as evidence; label it accurately.",
  python: "Since you have listed Python, first test your comfort with cleaning data and writing reusable functions. If those are comfortable, put more study time into statistics, leakage checks, and evaluation rather than repeating language basics.",
};
