import type { Row } from "./schema";

// How to practise a specific skill and how to show it. Answers describe study
// sequences and evidence, never a required proficiency for any employer.
export const skillRows: Row[] = [
  ["javascript-learning", "How should I learn JavaScript properly?", ["What is a good way to study JavaScript?", "How do I get past the basics of JavaScript?"], "skill-development", "roadmap", "Most people stall in JavaScript at the same place: they can follow along but cannot predict what their own code will do. The fix is to practise the parts that cause surprise rather than to move on to another framework.\n\nSpend real time on values and references, scope and closures, asynchronous behaviour, and the difference between what the language does and what the browser provides. When something behaves unexpectedly, form a hypothesis, test it in the console, and only then look up the explanation. That loop is what converts familiarity into understanding.\n\nBuild small things without a framework first so you know which problems the framework is actually solving. Then pick one framework and stay with it. Reading the official documentation rather than only video courses is worth the initial discomfort, because reference-reading is a daily part of the job.", ["javascript", "web"], ["JavaScript", "closures", "async", "browser", "fundamentals"]],

  ["react-learning", "How should I learn React for a job?", ["What is the right way to study React?", "How much React do I need before applying for jobs?"], "skill-development", "roadmap", "Learn enough JavaScript first that React's syntax is not competing for your attention. Struggling with React is very often struggling with array methods, destructuring, or asynchronous code in disguise.\n\nThen focus on the model rather than the API surface: what causes a re-render, where state should live, why lifting state up solves certain bugs, and how effects relate to things outside your component. Fetching data, showing loading and error states, and handling forms cover most real work.\n\nBuild one application with several screens, real data from an API, and proper handling of slow and failed requests. Add basic accessibility: labels, focus behaviour, and keyboard use. Being able to explain a re-render problem you diagnosed is a stronger interview signal than having used many libraries briefly.", ["react", "javascript"], ["React", "components", "state", "hooks", "frontend"]],

  ["git-learning", "How do I get comfortable with Git?", ["What Git commands do I actually need at work?", "How do I stop being afraid of Git?"], "skill-development", "roadmap", "Git becomes much easier once you stop memorising commands and learn the model: commits are snapshots, branches are pointers, and most confusion comes from not knowing which of the three areas your change is currently in.\n\nLearn the everyday path first: branch, stage, commit with a message someone else could understand, push, open a change for review, and update your branch when the main line moves. Then learn to inspect and recover, because that is what turns anxiety into confidence.\n\nPractise the frightening operations deliberately in a scratch repository you do not care about. Undo a commit, recover one you thought you lost, and resolve a conflict you created on purpose. Knowing that almost nothing committed is truly gone changes how you work with other people's code.", ["git"], ["Git", "version control", "branching", "merge", "collaboration"]],

  ["linux-learning", "How much Linux do I need for technical work?", ["Should I learn Linux commands for a technical job?", "How do I start learning the Linux command line?"], "skill-development", "roadmap", "For most technical roles, comfort at the command line matters more than administration expertise. The bar is being able to move around, inspect what is happening, and fix your own environment without needing someone else.\n\nStart with navigation, files and permissions, reading and searching text, processes, and how to find out why something will not start. Add package management, environment variables, and secure remote access. Learning to read a manual page rather than searching for a copied command is the habit that compounds.\n\nInstall a distribution in a virtual machine and use it for something real for a while. Break it, repair it, and keep notes on what you diagnosed. Infrastructure, security, and backend roles all assume this foundation, so it is rarely wasted effort whichever direction you take.", ["linux"], ["Linux", "command line", "shell", "permissions", "processes"]],

  ["dsa-preparation", "How should I practise data structures and algorithms?", ["How do I get better at coding problems?", "What is an effective way to prepare for coding rounds?"], "technical-interviews", "roadmap", "Practise for understanding rather than for volume. Solving many problems shallowly produces recognition without transfer; solving fewer problems thoroughly produces the reasoning that survives an unfamiliar question.\n\nWork in topic blocks. Take arrays and strings, then hashing, then two pointers and sliding windows, then trees and graphs, then dynamic programming. For each problem, attempt it honestly, then read the reasoning behind a better solution, then re-solve it from scratch a few days later. If you cannot re-solve it, you have not learned it yet.\n\nAlways state the complexity out loud and explain your approach before coding, because that is what the interview actually assesses. Spaced repetition of problems you found hard beats a longer list of problems you found easy. Keep a short log of the technique each problem taught you, not just whether it passed.", ["python"], ["algorithms", "data structures", "coding interview", "practice", "complexity"]],

  ["statistics-for-data", "How much statistics do I need for a data role?", ["What statistics should I study for analytics work?", "Do I need to be good at maths for data jobs?"], "data-science", "roadmap", "You need enough statistics to avoid confidently reporting something untrue. That is a lower bar than a degree and a higher bar than a weekend course.\n\nPrioritise the ideas that change conclusions: variability and why a single number can mislead, sampling and who is missing from your data, correlation against causation, uncertainty in an estimate, and what a comparison test does and does not tell you. Understanding why a result might be noise is more valuable day to day than deriving formulas.\n\nLearn it by applying it. Take a dataset, make a claim, then try seriously to disprove your own claim by looking for confounding, selection effects, or an unstable subgroup. Writing the caveats section of your own analysis is the exercise that builds real statistical judgement.", ["statistics", "sql"], ["statistics", "sampling", "uncertainty", "causation", "analysis"]],

  ["excel-for-analysts", "How good do I need to be at spreadsheets for analyst work?", ["Are spreadsheets still worth learning for data jobs?", "What spreadsheet skills matter for analysis?"], "data-science", "roadmap", "Spreadsheets remain the most common analytical tool in most organisations, and being genuinely quick in one is a practical advantage rather than a fallback.\n\nLearn lookups and joins between sheets, pivot tables, conditional aggregation, text and date handling, and how to structure a sheet so it can be audited by someone else. Then learn the failure modes: silent errors from mismatched types, ranges that do not expand, and copied formulas that quietly reference the wrong cell.\n\nThe professional habit is separating raw data, calculations, and presentation rather than mixing them on one sheet. Rebuild a report you have seen so that someone else could check every number back to its source. Knowing when a task has outgrown a spreadsheet and should move to a database is itself a valued judgement.", ["spreadsheet"], ["spreadsheets", "Excel", "pivot tables", "analysis", "auditing"]],

  ["bi-tool-learning", "How do I learn a business intelligence tool well?", ["What should I practise in a dashboard tool?", "How do I get good at building dashboards?"], "data-science", "roadmap", "Tool proficiency is quick to acquire; dashboard judgement is not. The common failure is a dense, attractive dashboard that nobody uses because it does not answer a question anyone was asking.\n\nStart from the decision. Ask who will look at this, what they will do differently depending on what they see, and how often. Then design the fewest views that support that decision, make the definitions explicit, and remove everything else. Consistent, documented metric definitions matter more than visual variety.\n\nPractise on data with real messiness rather than a clean sample. Then have someone unfamiliar with it try to answer a question using your dashboard while you watch silently. That exercise teaches more about layout and labelling than any tutorial, and the resulting before-and-after story is good portfolio material.", ["powerbi", "spreadsheet"], ["business intelligence", "dashboards", "metrics", "visualisation", "reporting"]],

  ["api-learning", "How do I learn to work with APIs?", ["What should I understand about REST APIs?", "How do I practise using and building APIs?"], "skill-development", "roadmap", "Begin as a consumer. Call a public API by hand, read the response carefully, and notice how it communicates success, failure, and pagination. Much of professional work is understanding someone else's interface rather than designing your own.\n\nThen learn the shape of the contract: methods, status codes, headers, authentication, rate limiting, and versioning. Build a small service of your own that validates its input, returns useful errors, and documents its endpoints. Handling the unhappy paths well is what separates a demo from something usable.\n\nPractise the failure cases deliberately: a slow response, an expired token, a partial result, a request sent twice. Being able to explain how your code behaves when the network misbehaves is a routine interview topic and a routine source of production incidents.", ["web", "python"], ["API", "REST", "HTTP", "authentication", "integration"]],

  ["testing-habits", "How do I start writing tests for my own code?", ["Why should I write tests and where do I begin?", "How do I add testing to my projects?"], "skill-development", "roadmap", "Begin with the part of your project you would be most afraid to change. Tests are most valuable where breakage would be expensive or hard to notice, not where coverage is easiest to raise.\n\nWrite tests that describe behaviour rather than implementation, so that refactoring does not break them. Cover the main path, the boundaries, and one realistic failure. Resist testing trivial details; a suite that fails constantly for unimportant reasons gets ignored and then deleted.\n\nA good habit for learning is to reproduce every bug you find as a failing test before fixing it. That builds a suite shaped by real problems rather than by guesses, and it gives you a concrete interview story about how you work. Keep tests fast, independent, and readable, because a slow suite stops being run.", ["testing"], ["testing", "unit tests", "coverage", "refactoring", "bugs"]],

  ["docker-learning", "Why should I learn containers and how do I start?", ["How do I get started with Docker?", "What do I need to understand about containers?"], "infrastructure", "roadmap", "Containers solve a problem you have probably already had: something works on your machine and not somewhere else. Learning them removes a recurring source of wasted time and is assumed in many backend, data, and infrastructure roles.\n\nStart by containerising an application you already wrote. Write the build file yourself rather than copying one, so you understand each layer. Then learn images against containers, mounting data so it survives a restart, environment configuration, networking between two containers, and why image size and layer order matter.\n\nOnce a multi-container setup runs locally, you have covered most day-to-day use. Orchestration is a separate and larger topic worth learning only when you need it. Being able to hand someone a repository that runs with one command is a small thing that reviewers notice.", ["docker"], ["Docker", "containers", "images", "environments", "deployment"]],

  ["english-communication", "How can I improve my professional English for interviews?", ["I am not confident speaking English at work. How do I improve?", "How do I communicate better in a second language professionally?"], "communication", "interview", "Aim for clarity rather than sophistication. Short sentences, concrete nouns, and a clear structure are more professional than complex vocabulary, and they are also easier to deliver under pressure.\n\nPractise in the format you will be assessed in. Record yourself answering a question for two minutes, listen back, and note where you lost the thread rather than where your grammar slipped. Prepare the shape of frequent answers, not a script, so you can adapt without freezing. Learning the specific vocabulary of your field is higher value than general study.\n\nIt is entirely acceptable to slow down, ask for a question to be repeated, or take a moment before answering; interviewers read that as composure. Speaking regularly with other people, even briefly, improves fluency faster than solitary study, so look for a practice group or a colleague willing to have short technical conversations.", ["writing"], ["English", "communication", "interviews", "fluency", "confidence"]],

  ["professional-writing", "How can I improve my writing at work?", ["How do I write clearer emails and documents?", "Why does written communication matter for technical roles?"], "communication", "roadmap", "Written communication is how most decisions are actually made in distributed teams, so it compounds more than almost any other soft skill. The goal is that a busy reader can act correctly after one pass.\n\nPut the conclusion or request first, then the reasoning, then the detail. Say explicitly what you want the reader to do and by when. Prefer specifics to hedged generalities, and delete every sentence that does not change what the reader knows or does.\n\nPractise by rewriting your own messages before sending for a couple of weeks; you will find most can be half the length. Reading your draft aloud catches tangled sentences quickly. For longer documents, add a short summary at the top and assume many readers will read only that.", ["writing"], ["writing", "communication", "documentation", "clarity", "email"]],

  ["accessibility-basics", "What accessibility basics should every developer know?", ["How do I make my projects accessible?", "Where do I start with web accessibility?"], "accessibility", "roadmap", "Accessibility is mostly a set of habits applied early rather than a specialist audit applied late. A handful of basics resolve a large share of common barriers.\n\nUse the correct element for the job so keyboard and assistive technology behaviour comes for free. Label every form control. Keep text contrast sufficient. Make sure everything usable with a mouse is reachable and operable with a keyboard, and that focus is always visible. Provide meaningful alternative text, and let genuinely decorative images be ignored.\n\nTest by putting the mouse aside and navigating your own project with the keyboard alone. Automated checkers catch only part of the problem, so pair them with that manual pass. Being able to describe a specific barrier you found and fixed is a distinctive thing to bring to a frontend interview.", ["a11y", "access"], ["accessibility", "WCAG", "keyboard", "contrast", "semantics"]],

  ["security-basics-developers", "What security basics should a developer know?", ["How do I write more secure code?", "What security knowledge is expected of a normal developer?"], "security", "roadmap", "You are not expected to be a security specialist, but you are expected not to introduce the well-known problems. Most of those come from trusting input, mishandling identity, or leaking secrets.\n\nLearn to treat all external input as untrusted, to separate data from instructions when talking to a database or a shell, and to distinguish authentication from authorisation — checking who someone is does not check whether they may do this to that record. Keep secrets out of source control, use the platform's own storage for them, and rotate them when exposed.\n\nAlso learn the boring operational half: keep dependencies updated, read the advisories that affect you, log enough to investigate without recording sensitive data, and fail closed rather than open. Practise on a deliberately vulnerable training application rather than on any system you do not own.", ["security"], ["security", "input validation", "authorisation", "secrets", "dependencies"]],

  ["learning-with-ai", "How should I use AI tools while learning to code?", ["Will using AI assistants stop me learning?", "How do I use coding assistants without becoming dependent?"], "skill-development", "guidance", "The risk is not using the tool; it is accepting output you could not have produced or checked. That habit creates fluent-looking work you cannot debug or defend in an interview.\n\nA workable rule while learning is to attempt first, then compare. Write your own version, then ask for an alternative and study the difference. Use the tool freely for things you already understand and are simply typing out, and cautiously for concepts you are still forming. Always run and test the result rather than assuming it is correct.\n\nBe aware that generated code can be confidently wrong, subtly insecure, or out of date, and that some employers restrict what may be pasted into external tools. Check your organisation's policy. The durable skill is judgement about when the output is wrong, and that only develops if you keep reading and testing carefully.", ["python"], ["AI tools", "learning", "code assistants", "verification", "dependency"]],

  ["choosing-first-language", "Which programming language should I learn first?", ["What is the best language for a beginner?", "Does it matter which language I start with?"], "skill-development", "roadmap", "The choice matters less than most beginners fear, because the transferable part is problem decomposition rather than syntax. What matters more is picking one and staying with it long enough to build something real.\n\nLet your target work guide the decision rather than popularity. Data and automation work commonly points one way, browser interfaces another, mobile another again, and systems programming another. Read a sample of job descriptions for the roles you want in your own area and notice what keeps appearing.\n\nThen commit for several months. Switching languages early is usually avoidance of the difficult middle stage, where nothing is new but nothing is easy yet. Once you can build, debug, and test in one language, the second takes a fraction of the time, which is exactly why the first choice is not the high-stakes decision it feels like.", ["python", "javascript"], ["first language", "beginner", "programming", "choice", "fundamentals"]],

  ["reading-code", "How do I get better at reading other people's code?", ["I struggle to understand an existing codebase. What should I do?", "How do I onboard to a large codebase?"], "skill-development", "roadmap", "Reading code is a separate skill from writing it, and it is the one you use most in a job. Trying to understand everything before touching anything is the usual mistake.\n\nStart from a behaviour rather than a file. Pick something the system does, find where it enters, and follow that one path through, ignoring everything off it. Run the code and use a debugger or logging to confirm your guesses rather than reading statically. Draw the path as you go; the drawing is disposable but the understanding is not.\n\nThen make a tiny safe change and watch what it affects. Fixing a small bug teaches more about a codebase than a week of reading. Keep a private list of the questions you could not answer and ask them in batches; needing to ask is normal and expected of a new joiner.", ["git"], ["reading code", "onboarding", "codebase", "debugging", "navigation"]],

  ["debugging-skill", "How do I get better at debugging?", ["I get stuck for hours on bugs. How do I improve?", "What is a systematic way to debug?"], "skill-development", "roadmap", "Debugging is an investigation, and most lost time comes from changing things before understanding them. The discipline is to narrow the search space rather than to try fixes.\n\nStart by reproducing the problem reliably; an intermittent bug you cannot trigger cannot be verified as fixed. Then read the actual error and the trace carefully rather than skimming. Form one hypothesis, decide what evidence would prove it wrong, and test that specifically. Halve the problem space where you can by removing parts until the failure disappears.\n\nKeep notes during long investigations so you do not repeat checks, and take a break when you find yourself repeating the same steps, because that is a symptom of a fixed and incorrect assumption. Being able to narrate a hard bug you solved and what misled you is a question that comes up often in interviews.", ["python"], ["debugging", "troubleshooting", "hypothesis", "reproduction", "problem solving"]],

  ["skill-gap-identification", "How do I work out which skills I am actually missing?", ["How can I identify my skill gaps for a target role?", "How do I know what to learn next for my goal?"], "career-guidance", "roadmap", "Use real job descriptions as the reference rather than a curriculum. Collect several postings for the role you want in the market you want, and extract the requirements into a single list.\n\nGroup what recurs. Something that appears in most postings is a genuine expectation; something in one is that employer's preference. Then rate yourself honestly against each: can you do it unaided, can you do it with help, or have you only read about it. The middle category is usually where the fastest progress is available.\n\nAttack the recurring items you cannot yet do unaided, one at a time, and produce a small piece of evidence for each. Re-run the exercise every couple of months, because both your skills and the postings change. This also gives you accurate language for your resume, since you are describing capabilities you have actually tested.", ["jobs", "occupations"], ["skill gaps", "job descriptions", "self assessment", "learning plan", "evidence"]],

  ["learning-plan-structure", "How do I structure a self-study plan that I will finish?", ["How do I make a realistic learning schedule?", "My study plans always collapse. How do I fix that?"], "skill-development", "roadmap", "Most plans fail because they are built around available enthusiasm rather than available time. Start from the hours you genuinely have in a normal, tiring week, not a good one.\n\nDefine the outcome as something you can demonstrate rather than something you will have consumed. Finishing a course is not evidence; building a thing that works is. Break that outcome into weekly deliverables small enough that a bad week costs you one item rather than the whole plan.\n\nBuild in review and slack. Schedule one lighter week in four for consolidation and unexpected life, and revisit the plan monthly against what actually happened rather than what you intended. A plan you have adjusted twice and are still following beats an ambitious one you abandoned in week three.", ["writing"], ["study plan", "self study", "consistency", "goals", "scheduling"]],
];
