import type { Row } from "./schema";

/**
 * Software engineering role roadmaps and skill paths. Each question is authored
 * so that "How do I become a <role>?" resolves through the roadmap matcher, and
 * every answer names concrete skills, a portfolio piece and readiness signals
 * without promising hiring outcomes.
 */
export const techRoleRows: Row[] = [
  [
    "python-backend-roadmap",
    "How do I become a Python backend developer?",
    ["How do I become a Python developer?", "Give me a Python backend developer roadmap", "What should I learn for Python developer jobs?", "Python developer roadmap for beginners", "How do I get a job as a Python backend developer?"],
    "software-engineering",
    "roadmap",
    "Phase 1: language fluency. Work through the official tutorial and write small scripts every day: file processing, a command-line to-do app, a script that calls a public API and saves the results. Learn functions, classes, exceptions, virtual environments, pip and how to read a traceback without panic. Add Git from the first week.\n\nPhase 2: the web layer. Backend work is HTTP plus data. Learn what a request and response contain, status codes, JSON, and how routing works. Build a small REST API with FastAPI or Django REST Framework, connect it to PostgreSQL, and learn SQL well enough to write joins and aggregates by hand rather than through an ORM alone. Add authentication, input validation and pagination, because interviewers ask about all three.\n\nPhase 3: production habits. Write unit and integration tests with pytest, containerise the service with Docker, add a GitHub Actions workflow that runs the tests, and deploy it somewhere public. Learn logging, environment-based configuration and basic caching. Read the Twelve-Factor App once and apply it.\n\nPortfolio project: a job-tracker or expense API with users, ownership rules, filtering, tests and a README that explains the design decisions. One finished, deployed service with tests says more than five unfinished ones.\n\nYou are ready to apply when you can explain how a request travels from the browser to the database and back, debug a failing test without a tutorial, and describe one trade-off you made in your project. Read ten current Python developer job descriptions and list the tools they repeat; adjust the plan to match them.",
    ["python", "fastapi", "django", "sql", "pytest", "docker", "twelveFactor", "developerRoadmap", "projectBasedLearning"],
    ["python", "backend", "developer", "fastapi", "django", "rest api", "postgresql", "roadmap"],
    ["jBzwzrDvZ18", "tLKKmouUams"],
  ],
  [
    "java-developer-roadmap",
    "How do I become a Java developer?",
    ["How do I become a Java backend developer?", "Java developer roadmap", "What should I learn for Java developer jobs?", "How do I start a career as a Java programmer?"],
    "software-engineering",
    "roadmap",
    "Phase 1: the language and object-oriented design. Use Oracle's Learn Java path and write programs that force you to use classes, interfaces, collections, generics, exceptions and streams. Learn how the JVM runs code, what the classpath is, and how to build with Maven or Gradle. Java rewards people who understand types and structure, so slow down on design rather than rushing to frameworks.\n\nPhase 2: Spring Boot and data. Most Java backend jobs name Spring. Build a REST service with Spring Boot, Spring Data JPA and PostgreSQL or MySQL, then add validation, exception handling, security with Spring Security, and profiles for configuration. Learn SQL independently of JPA so you can explain what the ORM generates.\n\nPhase 3: quality and delivery. Write tests with JUnit and Mockito, learn Docker, add a CI workflow, and deploy the service. Read about concurrency basics (threads, executors, synchronisation) because they appear in interviews for Java roles more than for most other languages.\n\nPortfolio project: an inventory or booking service with layered architecture (controller, service, repository), meaningful tests, and a document explaining why you structured it that way. Include one performance consideration, such as pagination or an index you added.\n\nReadiness signals: you can explain the difference between an interface and an abstract class with an example from your own code, describe how Spring dependency injection works, and read a stack trace across framework layers. Compare your project against five real Java job descriptions before applying.",
    ["javaLearn", "javaTutorials", "springGuides", "springBoot", "sql", "awesomeJava"],
    ["java", "spring boot", "backend", "jvm", "maven", "junit", "roadmap"],
    ["grEKMHGYyns", "9SGDpanrc8U"],
  ],
  [
    "typescript-developer-roadmap",
    "How do I become a TypeScript developer?",
    ["How do I learn TypeScript for a job?", "TypeScript roadmap after JavaScript", "Should I learn TypeScript before applying for frontend jobs?"],
    "software-engineering",
    "roadmap",
    "TypeScript is JavaScript with a type system, so the path starts with solid JavaScript: closures, promises, async/await, modules, array methods and the event loop. If those are shaky, TypeScript will feel like fighting the compiler rather than being helped by it.\n\nThen work through the official handbook in order: basic types, interfaces and type aliases, unions and narrowing, generics, utility types and modules. Convert one of your existing JavaScript projects to TypeScript file by file; the errors it reveals are the lesson. Learn to read library type definitions, because that is how you understand an unfamiliar API at work.\n\nApply it in a framework: React with TypeScript on the frontend or Node with Express or NestJS on the backend. Learn how to type props, API responses and form state, and how to validate external data at the boundary with a schema library instead of trusting a type assertion.\n\nPortfolio: a small full-stack app where the frontend and backend share types, with strict mode on and no any escapes you cannot justify. Add a short write-up on two bugs the compiler caught for you.\n\nYou are ready when you can explain the difference between an interface and a type alias, write a generic function without looking it up, and describe why runtime validation still matters in a typed codebase.",
    ["typescript", "javascriptInfo", "react", "nodeLearn", "fullstackOpen"],
    ["typescript", "javascript", "types", "generics", "frontend", "roadmap"],
    ["30LWjhZzg50"],
  ],
  [
    "react-developer-roadmap",
    "How do I become a React developer?",
    ["How do I become a Next.js developer?", "React developer roadmap", "What should I learn for React developer jobs?", "How do I get a React job as a fresher?"],
    "software-engineering",
    "roadmap",
    "Foundations first: semantic HTML, CSS layout with flexbox and grid, and enough JavaScript to be comfortable with functions, arrays, objects, fetch and promises. React assumes all of this.\n\nCore React: read the official Learn React sequence end to end. Components, props, state, events, lists and keys, controlled forms, effects and when not to use them, and lifting state up. Build three small interfaces from scratch without a tutorial: a searchable list, a multi-step form, and a dashboard that loads data from an API and handles loading and error states.\n\nThe modern stack: TypeScript, a router, data fetching with caching (TanStack Query or a framework's own loaders), and Next.js for server rendering and routing. Learn how rendering on the server differs from the client and what that means for data and state. Add accessibility basics: keyboard navigation, labels and focus management.\n\nQuality: component tests with Testing Library, end-to-end tests with Playwright, ESLint, and a CI workflow. Learn to profile a slow render and fix it.\n\nPortfolio: one polished, deployed application with authentication, real data, responsive layout and tests, plus a README with screenshots and decisions. Recruiters open the deployed link first.\n\nReady-to-apply signals: you can explain when a component re-renders, what a key does, how you would structure state for a form, and how server components change data loading in Next.js.",
    ["react", "nextjs", "typescript", "webDev", "testing", "access", "fullstackOpen"],
    ["react", "next.js", "frontend", "hooks", "typescript", "components", "roadmap"],
    ["bMknfKXIFA8", "wm5gMKuwSYk"],
  ],
  [
    "fullstack-developer-roadmap",
    "How do I become a full stack developer?",
    ["Full stack developer roadmap", "What should I learn to be a full-stack web developer?", "How do I become a full-stack engineer?", "Give me a roadmap for full stack development"],
    "software-engineering",
    "roadmap",
    "Full stack means you can ship a complete feature: interface, API, database and deployment. The mistake most people make is studying both halves in parallel at shallow depth. Instead, build one thin vertical slice early, then deepen each layer.\n\nMonth-scale outline. First, HTML, CSS and JavaScript until you can build a responsive page and manipulate it with events and fetch. Second, one frontend framework (React is the most common in job descriptions) with routing, forms and data loading. Third, one backend: Node with Express or NestJS if you want a single language, or Python with FastAPI or Django, or Java with Spring Boot if local job descriptions favour it. Learn HTTP properly, REST design, authentication with sessions or JWTs, and input validation. Fourth, a relational database with real SQL: schema design, joins, indexes, migrations. Fifth, delivery: Git branching, tests on both sides, Docker, CI, and a deployed app with environment configuration and logging.\n\nPortfolio project: a multi-user application (bookings, tickets, inventory, a job tracker) where users own their data, with search, pagination, file upload or email, tests, and a written architecture overview. Deploy it and keep it running; a live URL is your strongest evidence.\n\nReady when you can trace a feature from a click to a database row and back, explain one security decision you made, and add a new field end to end in under an hour. Full Stack Open and The Odin Project are the two most complete free curricula if you want structure.",
    ["fullstackOpen", "odin", "webDev", "nodeLearn", "sql", "docker", "githubActions", "developerRoadmap"],
    ["full stack", "fullstack", "web developer", "react", "node", "sql", "deployment", "roadmap"],
    ["LzMnsfqjzkA", "Je_KYIM9QJc"],
  ],
  [
    "nodejs-backend-roadmap",
    "How do I become a Node.js backend developer?",
    ["Node.js developer roadmap", "What should I learn for Node.js backend jobs?", "How do I build backend services with JavaScript?"],
    "software-engineering",
    "roadmap",
    "Start by understanding what Node is: a JavaScript runtime with an event loop, non-blocking I/O and a module system. Learn asynchronous programming deeply (callbacks, promises, async/await, streams) because almost every Node bug in interviews is an async bug.\n\nBuild an HTTP server with plain Node once, then move to Express or Fastify for routing and middleware, or NestJS if you want a more structured, TypeScript-first framework. Add PostgreSQL with a query builder or ORM (Prisma, Drizzle, Knex) and learn the SQL underneath. Implement authentication, validation with a schema library, rate limiting, error handling that does not leak internals, and structured logging.\n\nQuality and operations: tests with Jest or Vitest and Supertest, environment configuration, Docker, a CI pipeline, and deployment. Read the Node.js Best Practices repository; it is effectively a checklist of what senior reviewers look for.\n\nPortfolio: an API with users, roles, background jobs (a queue or scheduled task) and webhooks or email, plus documentation generated from an OpenAPI spec.\n\nReadiness: you can explain the event loop and why blocking it matters, design a schema for a small domain, secure an endpoint, and describe how you would handle a slow third-party API call without freezing your service.",
    ["nodeLearn", "nodeBestPractices", "typescript", "sql", "jest", "docker", "twelveFactor"],
    ["node.js", "express", "nestjs", "backend", "javascript", "api", "roadmap"],
    ["Oe421EPjeBE"],
  ],
  [
    "software-engineer-roadmap",
    "How do I become a software engineer?",
    ["Software engineer roadmap for beginners", "How do I start a career in software engineering?", "What should I learn to become a software developer?", "How do I get into software development with no experience?"],
    "software-engineering",
    "roadmap",
    "Software engineering is broader than one language, so start with foundations that transfer: how programs run, how data is structured, how to break a problem into steps, and how to read and change code you did not write.\n\nPhase 1: pick one language and build fluency. Python or JavaScript are the fastest to start with; Java or C# are fine if local employers favour them. CS50 is the best free structured entry if you want a university-style grounding. Practise daily with small programs and learn Git immediately.\n\nPhase 2: computer science that matters at work. Data structures (arrays, hash maps, trees, graphs), algorithmic complexity, basic databases and SQL, how the web works (HTTP, DNS, APIs), and operating-system basics (processes, memory, files). You do not need to finish a degree's worth, but you need the vocabulary and the ability to reason about cost.\n\nPhase 3: build and ship. Choose a specialisation (web frontend, backend, mobile, data, infrastructure), build two projects to completion, write tests, use a CI pipeline and deploy. Contribute a small fix to an open-source project to learn code review.\n\nPhase 4: interview readiness. Practise problem solving out loud, prepare stories about debugging and trade-offs from your own projects, and learn to explain a system you built at a whiteboard.\n\nYou are ready when you can build a small, working, tested application from an ambiguous description, explain your choices, and estimate what a change would cost. The roadmap.sh guides are a good map of specialisations once you have chosen one.",
    ["cs50", "ossu", "developerRoadmap", "git", "projectBasedLearning", "techInterviewHandbook", "blsOoh"],
    ["software engineer", "software developer", "programming", "computer science", "beginner", "roadmap"],
    ["GxmfcnU3feo", "RBSGKlAvoiM"],
  ],
  [
    "spring-boot-learning",
    "How do I learn Spring Boot?",
    ["What is the right way to study Spring Boot?", "How much Spring do I need for Java backend jobs?", "Where do I start with Spring Framework?"],
    "skill-development",
    "roadmap",
    "Learn Spring Boot after you are comfortable with core Java, because the framework hides a lot and you need to know what it is hiding. Start with the official Spring Guides: build a REST service, then add data access with Spring Data JPA, then security. Each guide takes an hour and produces working code.\n\nThen build one application of your own without copying a guide: entities, repositories, a service layer, controllers, DTOs, validation, global exception handling and profiles for local versus production configuration. Add Flyway or Liquibase migrations so the schema is versioned. Learn what auto-configuration does by reading the startup logs and by deliberately breaking a bean.\n\nTesting is where Spring knowledge shows: write slice tests with @WebMvcTest and @DataJpaTest, and one full-context integration test using Testcontainers against a real database.\n\nRead the Spring Boot reference documentation's sections on configuration, actuator and logging; interviewers ask about them. Baeldung-style tutorials are useful for specific problems but should not replace the reference.\n\nYou know enough when you can explain dependency injection and bean scopes, describe how a request moves through the MVC stack, and debug a startup failure from the exception alone.",
    ["springGuides", "springBoot", "javaLearn", "sql", "docker"],
    ["spring boot", "spring", "java", "jpa", "rest", "backend"],
    ["9SGDpanrc8U"],
  ],
  [
    "flutter-learning",
    "How do I learn Flutter for mobile app jobs?",
    ["How do I start with Flutter?", "Is Flutter a good way into mobile development?", "What should I build to learn Flutter?"],
    "skill-development",
    "roadmap",
    "Flutter lets you build Android and iOS apps from one Dart codebase, so the first step is Dart itself: variables, null safety, classes, async and futures, collections. Two or three days on the language pays off, because most Flutter confusion is really Dart confusion.\n\nNext, the widget model. Work through the official documentation's first app codelab, then learn the difference between stateless and stateful widgets, layout widgets (Row, Column, Stack, Expanded), navigation, forms and theming. Build screens without copying code until layout feels natural.\n\nThen the parts real apps need: state management (start with Provider or Riverpod; learn one well rather than three shallowly), calling a REST API with error and loading states, local storage, and platform permissions. Add tests: widget tests for screens and unit tests for logic.\n\nPortfolio: one published or at least installable app with authentication, a list-detail flow, offline handling and a README with screenshots. If you cannot publish to a store, a signed APK and a demo video are acceptable evidence.\n\nYou are job-ready for entry roles when you can explain how state flows through your app, build a responsive screen from a design mock, and describe how you handled a slow network in the interface.",
    ["flutter", "android", "projectBasedLearning"],
    ["flutter", "dart", "mobile", "android", "ios", "app development"],
    ["VPvVD8t02U8"],
  ],
  [
    "javascript-fundamentals-for-jobs",
    "Which JavaScript concepts do interviewers expect a junior developer to know?",
    ["What JavaScript topics come up in frontend interviews?", "How much JavaScript do I need before applying for developer jobs?"],
    "skill-development",
    "guidance",
    "Junior JavaScript interviews test whether you understand the language rather than a framework. The topics that come up repeatedly: variable scope and hoisting, closures, the this keyword and arrow functions, prototypes and classes, array methods (map, filter, reduce) and when to use each, promises and async/await, the event loop and why a long loop freezes the page, event delegation in the DOM, and how fetch and JSON work. Expect small exercises such as debouncing a function, flattening an array, or explaining the output of a snippet with setTimeout and promises.\n\nPrepare by writing the answers as code, not by reading explanations. For each concept, produce a ten-line example that demonstrates it and a sentence about where you used it in a project. The Modern JavaScript Tutorial and Eloquent JavaScript cover all of this with exercises.\n\nIf you also know TypeScript basics and can explain how you would test a function, you are ahead of most entry-level candidates. Do not memorise trivia lists; be able to explain one concept deeply when asked.",
    ["javascriptInfo", "eloquentJs", "javascript", "techInterviewHandbook"],
    ["javascript", "interview", "closures", "promises", "event loop", "junior"],
    ["jS4aFq5-91M"],
  ],
  [
    "api-design-basics",
    "How do I design a good REST API for a portfolio project?",
    ["What makes a REST API well designed?", "How should I structure endpoints in my backend project?"],
    "skill-development",
    "guidance",
    "Design the resources first, then the endpoints. Write down the nouns in your domain (users, jobs, applications), how they relate, and who is allowed to see or change each one. Endpoints then follow naturally: plural nouns, HTTP verbs for actions, nested paths only where ownership is real.\n\nRules that reviewers notice: consistent naming and casing; correct status codes (201 for creation, 404 for missing, 422 or 400 for validation, 401 versus 403 for authentication versus permission); validation of every input with clear error bodies; pagination on every list; filtering and sorting through query parameters; and no internal identifiers or stack traces leaking in responses.\n\nDocument it with an OpenAPI specification and generate the docs page; FastAPI and NestJS do this for free. Version the API from the start, even if only v1 exists.\n\nAdd the operational pieces that separate a demo from a service: authentication, rate limiting, request logging with a correlation id, and tests that hit the endpoints. Test the unhappy paths as carefully as the happy ones.\n\nIn interviews, be ready to explain one idempotency decision, how you would handle a long-running operation, and what you would change if the API needed to serve a mobile app as well.",
    ["fastapi", "postmanLearning", "nodeBestPractices", "twelveFactor"],
    ["rest api", "api design", "endpoints", "openapi", "backend", "portfolio"],
  ],
  [
    "clean-code-habits",
    "How do I write cleaner code that reviewers will accept?",
    ["What does clean code mean in practice?", "How do I improve code quality as a junior developer?"],
    "skill-development",
    "guidance",
    "Clean code is code another person can change safely. Judge your own work by that standard rather than by style rules alone.\n\nHabits that matter most: small functions that do one thing and are named for what they do; variables named for meaning rather than type; no duplicated logic; early returns instead of deep nesting; errors handled where you can do something about them; and comments that explain why, not what. Keep modules focused and dependencies pointing in one direction.\n\nLearn to refactor deliberately. Refactoring.Guru catalogues code smells and the moves that fix them; practise one at a time on your own projects. Use a formatter and a linter so style never comes up in review.\n\nTests are part of clean code: a function that is hard to test is usually badly shaped. Write a test first when adding a bug fix, so the fix is provable.\n\nIn code review, read the reviewer's comment as information about how your code reads to someone else. Ask what would make it clearer rather than defending it. After a few reviews you will predict the comments before you push, which is the real goal.",
    ["refactoringGuru", "martinFowler", "nodeBestPractices"],
    ["clean code", "code quality", "refactoring", "code review", "junior developer"],
  ],
  [
    "mobile-vs-web-choice",
    "Should I specialise in mobile or web development?",
    ["Mobile developer or web developer: which should I choose?", "Is mobile development a better career than web development?"],
    "software-engineering",
    "comparison",
    "Both are healthy specialisations; the better one is the one whose daily work you enjoy and whose local job descriptions you match.\n\nWeb development has more openings in most markets, a faster feedback loop (refresh the browser), a larger share of remote roles, and skills that transfer into backend and full-stack work. Mobile development has fewer but often deeper roles, a more constrained environment (battery, permissions, offline, store review), and strong demand in product companies that live on apps. Mobile learning has a steeper setup cost and slower iteration, but cross-platform frameworks such as Flutter and React Native narrow the gap.\n\nDecide with evidence: build one small project in each, note which problems you found interesting rather than merely finishable, and read twenty local job descriptions for each track to see which skills they repeat. If you are undecided, start with web; the JavaScript and API knowledge transfers directly to React Native later, and the reverse transfer is weaker.",
    ["webDev", "flutter", "android", "developerRoadmap"],
    ["mobile", "web", "career choice", "flutter", "react native", "specialisation"],
    ["VPvVD8t02U8", "GxmfcnU3feo"],
  ],
];
